// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif
extension V1EventsMethods {
    public struct GetEventsOptions: Codable {
        public var created: GetEventsParameter?
        public var deliverySuccess: Bool?
        public var endingBefore: String?
        public var expand: [String]?
        public var limit: Int?
        public var startingAfter: String?
        public var type: String?
        public var types: [String]?

        public init() {}
    }

    /// Lists events created within the last 30 days. Use `created`, `type`, or `types` to filter results and `starting_after` or `ending_before` to traverse the list; do not provide `type` and `types` together.
    ///
    /// List events, going back up to 30 days. Each event data is rendered according to Stripe API version at its creation time, specified in event object api_version attribute (not according to your current Stripe API version or Stripe-Version header).
    ///
    /// - Parameters:
    /// - created: Only return events that were created during the given date
    ///   interval.
    /// - deliverySuccess: Filter events by whether all webhooks were successfully
    ///   delivered. If false, events which are still pending or have failed all
    ///   delivery attempts to a webhook endpoint will be returned.
    /// - endingBefore: A cursor for use in pagination. `ending_before` is an object
    ///   ID that defines your place in the list. For instance, if you make a list
    ///   request and receive 100 objects, starting with `obj_bar`, your subsequent
    ///   call can include `ending_before=obj_bar` in order to fetch the previous page
    ///   of the list.
    /// - expand: Specifies which fields in the response should be expanded.
    /// - limit: A limit on the number of objects to be returned. Limit can range
    ///   between 1 and 100, and the default is 10.
    /// - startingAfter: A cursor for use in pagination. `starting_after` is an
    ///   object ID that defines your place in the list. For instance, if you make a
    ///   list request and receive 100 objects, ending with `obj_foo`, your subsequent
    ///   call can include `starting_after=obj_foo` in order to fetch the next page of
    ///   the list.
    /// - type: A string containing a specific event name, or group of events using
    ///   * as a wildcard. The list will be filtered to include only events with a
    ///   matching event property.
    /// - types: An array of up to 20 strings containing specific event names. The
    ///   list will be filtered to include only events with a matching event property.
    ///   You may pass either `type` or `types`, but not both.
    public static func getEvents(config: ClientConfig, options: GetEventsOptions) async throws -> GetEventsResponse {
        if let endingBefore = options.endingBefore {
            try validateLength("ending_before", endingBefore, max: 5000)
        }

        if let startingAfter = options.startingAfter {
            try validateLength("starting_after", startingAfter, max: 5000)
        }

        if let type = options.type {
            try validateLength("type", type, max: 5000)
        }

        return try (await sdkRequest("GET", "/v1/events", config: config, query: [
            SdkQueryParameter("created", value: options.created),
            SdkQueryParameter("delivery_success", value: options.deliverySuccess),
            SdkQueryParameter("ending_before", value: options.endingBefore),
            SdkQueryParameter("expand", values: options.expand, style: "deepObject", explode: true),
            SdkQueryParameter("limit", value: options.limit),
            SdkQueryParameter("starting_after", value: options.startingAfter),
            SdkQueryParameter("type", value: options.type),
            SdkQueryParameter("types", values: options.types, style: "deepObject", explode: true),
        ], decoder: .json, operationId: "GetEvents")).data
    }
}
