// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif
extension V1SubscriptionSchedulesMethods {
    public struct GetSubscriptionSchedulesOptions: Codable {
        public var canceledAt: GetSubscriptionSchedulesParameter?
        public var completedAt: GetSubscriptionSchedulesParameterX59211e93?
        public var created: GetSubscriptionSchedulesParameterX43a7efae?
        public var customer: String?
        public var customerAccount: String?
        public var endingBefore: String?
        public var expand: [String]?
        public var limit: Int?
        public var releasedAt: GetSubscriptionSchedulesParameterX2bc3ad22?
        public var scheduled: Bool?
        public var startingAfter: String?

        public init() {}
    }

    /// Lists subscription schedules that match the supplied lifecycle, customer, account, and creation-time filters. Use `starting_after` and `ending_before` to navigate the cursor-paginated results, and use `limit` to control the page size. By default, the results include schedules regardless of lifecycle state unless filters narrow the selection.
    ///
    /// Retrieves the list of your subscription schedules.
    ///
    /// - Parameters:
    /// - canceledAt: Only return subscription schedules that were created canceled
    ///   the given date interval.
    /// - completedAt: Only return subscription schedules that completed during the
    ///   given date interval.
    /// - created: Only return subscription schedules that were created during the
    ///   given date interval.
    /// - customer: Only return subscription schedules for the given customer. The
    ///   response will not include subscription schedules for customers with a test
    ///   clock attached if this parameter is not set.
    /// - customerAccount: Only return subscription schedules for the given account.
    /// - endingBefore: A cursor for use in pagination. `ending_before` is an object
    ///   ID that defines your place in the list. For instance, if you make a list
    ///   request and receive 100 objects, starting with `obj_bar`, your subsequent
    ///   call can include `ending_before=obj_bar` in order to fetch the previous page
    ///   of the list.
    /// - expand: Specifies which fields in the response should be expanded.
    /// - limit: A limit on the number of objects to be returned. Limit can range
    ///   between 1 and 100, and the default is 10.
    /// - releasedAt: Only return subscription schedules that were released during
    ///   the given date interval.
    /// - scheduled: Only return subscription schedules that have not started yet.
    /// - startingAfter: A cursor for use in pagination. `starting_after` is an
    ///   object ID that defines your place in the list. For instance, if you make a
    ///   list request and receive 100 objects, ending with `obj_foo`, your subsequent
    ///   call can include `starting_after=obj_foo` in order to fetch the next page of
    ///   the list.
    public static func getSubscriptionSchedules(config: ClientConfig, options: GetSubscriptionSchedulesOptions) async throws -> GetSubscriptionSchedulesResponse {
        if let customer = options.customer {
            try validateLength("customer", customer, max: 5000)
        }

        if let customerAccount = options.customerAccount {
            try validateLength("customer_account", customerAccount, max: 5000)
        }

        if let endingBefore = options.endingBefore {
            try validateLength("ending_before", endingBefore, max: 5000)
        }

        if let startingAfter = options.startingAfter {
            try validateLength("starting_after", startingAfter, max: 5000)
        }

        return try (await sdkRequest("GET", "/v1/subscription_schedules", config: config, query: [
            SdkQueryParameter("canceled_at", value: options.canceledAt),
            SdkQueryParameter("completed_at", value: options.completedAt),
            SdkQueryParameter("created", value: options.created),
            SdkQueryParameter("customer", value: options.customer),
            SdkQueryParameter("customer_account", value: options.customerAccount),
            SdkQueryParameter("ending_before", value: options.endingBefore),
            SdkQueryParameter("expand", values: options.expand, style: "deepObject", explode: true),
            SdkQueryParameter("limit", value: options.limit),
            SdkQueryParameter("released_at", value: options.releasedAt),
            SdkQueryParameter("scheduled", value: options.scheduled),
            SdkQueryParameter("starting_after", value: options.startingAfter),
        ], decoder: .json, operationId: "GetSubscriptionSchedules")).data
    }
}
