// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation
@testable import OctriStripe
import XCTest

extension SdkMethodTests {
    func testDeleteTaxIdsIdDeleteTaxIdsIdReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.taxIds.deleteId(
            id: decoded("\"id-1\"")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture27Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "deleteTaxIdsId decoded a response " +
                "that differs from the mock"
        )
    }

    func testDeleteTerminalConfigurationsConfigurationDeleteTerminalConfigX79ed1c6887ReachesMockAndDecodesResponse(
    ) async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.terminal.configurations.deleteTerminalConfiguration(
            configuration: decoded("\"configuration\"")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture28Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "deleteTerminalConfigurationsConfiguration decoded a response " +
                "that differs from the mock"
        )
    }

    func testDeleteTerminalLocationsLocationDeleteTerminalLocationsLocationReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.terminal.locations.deleteTerminalLocation(
            location: decoded("\"location\"")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture29Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "deleteTerminalLocationsLocation decoded a response " +
                "that differs from the mock"
        )
    }

    func testDeleteTerminalReadersReaderDeleteTerminalReadersReaderReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.terminal.readers.deleteTerminalReader(
            reader: decoded("\"reader\"")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture30Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "deleteTerminalReadersReader decoded a response " +
                "that differs from the mock"
        )
    }

    func testDeleteTestHelpersTestClocksTestClockDeleteTestHelpersTestClocksTestClockReachesMockAndDecodesResponse(
    ) async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.testHelpers.testClocks.deleteTestHelpersTestClock(
            testClock: decoded("\"test_clock\"")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture31Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "deleteTestHelpersTestClocksTestClock decoded a response " +
                "that differs from the mock"
        )
    }

    func testDeleteWebhookEndpointsWebhookEndpointDeleteWebhookEndpointsWeX004e9f1578ReachesMockAndDecodesResponse(
    ) async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.webhookEndpoints.deleteWebhookEndpoint(
            webhookEndpoint: decoded("\"webhook_endpoint\"")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture32Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "deleteWebhookEndpointsWebhookEndpoint decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetAccountGetAccountReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.accounts.getAccount(
            account: decoded("\"sample\""),
            expand: decoded("[\"expand\"]")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture33Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getAccount decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetAccountsGetAccountsReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.accounts.get(
            created: decoded("{\"gt\":1,\"gte\":1,\"lt\":1,\"lte\":1}"),
            endingBefore: decoded("\"ending_before\""),
            expand: decoded("[\"expand\"]"),
            limit: decoded("1"),
            startingAfter: decoded("\"starting_after\"")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture34Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getAccounts decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetAccountsAccountGetAccountsAccountReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.accounts.capabilities.getAccountsAccount(
            account: decoded("\"account\""),
            expand: decoded("[\"expand\"]")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture35Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getAccountsAccount decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetAccountsAccountBankAccountsIdGetAccountsAccountBankAccountsIdReachesMockAndDecodesResponse(
    ) async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.accounts.bankAccounts.getAccountsAccountId(
            account: decoded("\"account\""),
            id: decoded("\"id-1\""),
            expand: decoded("[\"expand\"]")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture36Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getAccountsAccountBankAccountsId decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetAccountsAccountCapabilitiesGetAccountsAccountCapabilitiesReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.accounts.capabilities.getAccountsAccount(
            account: decoded("\"account\""),
            expand: decoded("[\"expand\"]")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture37Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getAccountsAccountCapabilities decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetAccountsAccountCapabilitiesCapabilityGetAccountsAccountCapX03e44d8602ReachesMockAndDecodesResponse(
    ) async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.accounts.capabilities.getAccountsAccountCapability(
            account: decoded("\"account\""),
            capability: decoded("\"capability\""),
            expand: decoded("[\"expand\"]")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture38Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getAccountsAccountCapabilitiesCapability decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetAccountsAccountExternalAccountsGetAccountsAccountExternalAccountsReachesMockAndDecodesResponse(
    ) async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.accounts.externalAccounts.getAccountsAccount(
            account: decoded("\"account\""),
            endingBefore: decoded("\"ending_before\""),
            expand: decoded("[\"expand\"]"),
            limit: decoded("1"),
            object: decoded("\"bank_account\""),
            startingAfter: decoded("\"starting_after\"")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture39Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getAccountsAccountExternalAccounts decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetAccountsAccountExternalAccountsIdGetAccountsAccountExternalAccountsIdReachesMockAndDecodesResponse(
    ) async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.accounts.externalAccounts.getAccountsAccountId(
            account: decoded("\"account\""),
            id: decoded("\"id-1\""),
            expand: decoded("[\"expand\"]")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture40Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getAccountsAccountExternalAccountsId decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetAccountsAccountPeopleGetAccountsAccountPeopleReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.accounts.people.getAccountsAccount(
            account: decoded("\"account\""),
            endingBefore: decoded("\"ending_before\""),
            expand: decoded("[\"expand\"]"),
            limit: decoded("1"),
            relationship: decoded(sdkMethodFixture41Value1),
            startingAfter: decoded("\"starting_after\"")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture41Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getAccountsAccountPeople decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetAccountsAccountPeoplePersonGetAccountsAccountPeoplePersonReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.accounts.people.getAccountsAccountPerson(
            account: decoded("\"account\""),
            person: decoded("\"person\""),
            expand: decoded("[\"expand\"]")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture42Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getAccountsAccountPeoplePerson decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetAccountsAccountPersonsGetAccountsAccountPersonsReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.accounts.persons.getAccountsAccount(
            account: decoded("\"account\""),
            endingBefore: decoded("\"ending_before\""),
            expand: decoded("[\"expand\"]"),
            limit: decoded("1"),
            relationship: decoded(sdkMethodFixture43Value1),
            startingAfter: decoded("\"starting_after\"")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture43Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getAccountsAccountPersons decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetAccountsAccountPersonsPersonGetAccountsAccountPersonsPersonReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.accounts.persons.getAccountsAccountPerson(
            account: decoded("\"account\""),
            person: decoded("\"person\""),
            expand: decoded("[\"expand\"]")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture44Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getAccountsAccountPersonsPerson decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetApplePayDomainsGetApplePayDomainsReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.applePay.domains.getApplePay(
            domainName: decoded("\"Example Name\""),
            endingBefore: decoded("\"ending_before\""),
            expand: decoded("[\"expand\"]"),
            limit: decoded("1"),
            startingAfter: decoded("\"starting_after\"")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture45Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getApplePayDomains decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetApplePayDomainsDomainGetApplePayDomainsDomainReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.applePay.domains.getApplePayDomain(
            domain: decoded("\"domain\""),
            expand: decoded("[\"expand\"]")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture46Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getApplePayDomainsDomain decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetApplicationFeesGetApplicationFeesReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.applicationFees.get(
            charge: decoded("\"charge\""),
            created: decoded("{\"gt\":1,\"gte\":1,\"lt\":1,\"lte\":1}"),
            endingBefore: decoded("\"ending_before\""),
            expand: decoded("[\"expand\"]"),
            limit: decoded("1"),
            startingAfter: decoded("\"starting_after\"")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture47Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getApplicationFees decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetApplicationFeesFeeRefundsIdGetApplicationFeesFeeRefundsIdReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.applicationFees.refunds.getApplicationFeesFeeId(
            fee: decoded("\"fee\""),
            id: decoded("\"id-1\""),
            expand: decoded("[\"expand\"]")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture48Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getApplicationFeesFeeRefundsId decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetApplicationFeesIdGetApplicationFeesIdReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.applicationFees.refunds.getApplicationFeesId(
            id: decoded("\"id-1\""),
            endingBefore: decoded("\"sample\""),
            expand: decoded("[\"expand\"]"),
            limit: decoded("\"sample\""),
            startingAfter: decoded("\"sample\"")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture49Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getApplicationFeesId decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetApplicationFeesIdRefundsGetApplicationFeesIdRefundsReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.applicationFees.refunds.getApplicationFeesId(
            id: decoded("\"id-1\""),
            endingBefore: decoded("\"ending_before\""),
            expand: decoded("[\"expand\"]"),
            limit: decoded("1"),
            startingAfter: decoded("\"starting_after\"")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture50Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getApplicationFeesIdRefunds decoded a response " +
                "that differs from the mock"
        )
    }

    func testGetAppsSecretsGetAppsSecretsReachesMockAndDecodesResponse() async throws {
        guard let client = configuredClient() else {
            return
        }
        _ = client
        let actual = try await client.v1.apps.secrets.find.getAppsSecrets(
            name: decoded("\"sample\""),
            scope: decoded("{\"type\":\"account\",\"user\":\"user\"}"),
            expand: decoded("[\"expand\"]")
        )
        let expected = try JSONSerialization.jsonObject(
            with: Data(sdkMethodFixture51Expected.utf8),
            options: [.fragmentsAllowed]
        )
        XCTAssertNil(
            try mismatch(jsonValue(actual), expected),
            "getAppsSecrets decoded a response " +
                "that differs from the mock"
        )
    }
}
