// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif

/// Canonical v1PaymentMethodConfigurations operation model declarations
public struct PostPaymentMethodConfigurationsConfigurationRequestBodyBillieXba187f0457: Codable {
    public var preference: PostPaymentMethodConfigurationsConfigurationRequestBodyBillieXd0ccc298d5?

    enum CodingKeys: String, CodingKey {
        case preference
    }

    init() {
        preference = nil
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyBillieXba187f0457 {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        preference = try container.sdkDecodeIfPresent(.preference)
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyBillieXba187f0457 {
    init(preference: PostPaymentMethodConfigurationsConfigurationRequestBodyBillieXd0ccc298d5? = nil) {
        self.init()
        self.preference = preference
    }
}

/// Boleto is an official (regulated by the Central Bank of Brazil) payment method in Brazil. Check this page for
/// more details.
public struct PostPaymentMethodConfigurationsConfigurationRequestBodyBoleto: Codable {
    /// display_preference_param
    public var displayPreference: PostPaymentMethodConfigurationsConfigurationRequestBodyBoletoX284f091f54?

    enum CodingKeys: String, CodingKey {
        case displayPreference = "display_preference"
    }

    init() {
        displayPreference = nil
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyBoleto {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        displayPreference = try container.sdkDecodeIfPresent(.displayPreference)
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyBoleto {
    init(displayPreference: PostPaymentMethodConfigurationsConfigurationRequestBodyBoletoX284f091f54? = nil) {
        self.init()
        self.displayPreference = displayPreference
    }
}

public struct PostPaymentMethodConfigurationsRequestBodyPaycoDisplayPreference: Codable {
    public var preference: PostPaymentMethodConfigurationsRequestBodyPaycoDisplayPrefereX24150dd35f?

    enum CodingKeys: String, CodingKey {
        case preference
    }

    init() {
        preference = nil
    }
}

public extension PostPaymentMethodConfigurationsRequestBodyPaycoDisplayPreference {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        preference = try container.sdkDecodeIfPresent(.preference)
    }
}

public extension PostPaymentMethodConfigurationsRequestBodyPaycoDisplayPreference {
    init(preference: PostPaymentMethodConfigurationsRequestBodyPaycoDisplayPrefereX24150dd35f? = nil) {
        self.init()
        self.preference = preference
    }
}

public struct PostPaymentMethodConfigurationsConfigurationRequestBodyBanconX78a4792469: Codable {
    public var preference: PostPaymentMethodConfigurationsConfigurationRequestBodyBanconX49dae7a80d?

    enum CodingKeys: String, CodingKey {
        case preference
    }

    init() {
        preference = nil
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyBanconX78a4792469 {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        preference = try container.sdkDecodeIfPresent(.preference)
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyBanconX78a4792469 {
    init(preference: PostPaymentMethodConfigurationsConfigurationRequestBodyBanconX49dae7a80d? = nil) {
        self.init()
        self.preference = preference
    }
}

public struct PostPaymentMethodConfigurationsConfigurationRequestBodyMultibXae5dcabc63: Codable {
    public var preference: PostPaymentMethodConfigurationsConfigurationRequestBodyMultibX0a4d1cabba?

    enum CodingKeys: String, CodingKey {
        case preference
    }

    init() {
        preference = nil
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyMultibXae5dcabc63 {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        preference = try container.sdkDecodeIfPresent(.preference)
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyMultibXae5dcabc63 {
    init(preference: PostPaymentMethodConfigurationsConfigurationRequestBodyMultibX0a4d1cabba? = nil) {
        self.init()
        self.preference = preference
    }
}

public struct PostPaymentMethodConfigurationsConfigurationRequestBodyZipDisX5edb4d457b: Codable {
    public var preference: PostPaymentMethodConfigurationsConfigurationRequestBodyZipDisX6be50daab9?

    enum CodingKeys: String, CodingKey {
        case preference
    }

    init() {
        preference = nil
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyZipDisX5edb4d457b {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        preference = try container.sdkDecodeIfPresent(.preference)
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyZipDisX5edb4d457b {
    init(preference: PostPaymentMethodConfigurationsConfigurationRequestBodyZipDisX6be50daab9? = nil) {
        self.init()
        self.preference = preference
    }
}

public struct PostPaymentMethodConfigurationsConfigurationRequestBodyAlipayX5fe7a2dea7: Codable {
    public var preference: PostPaymentMethodConfigurationsConfigurationRequestBodyAlipayXe5e8edfa06?

    enum CodingKeys: String, CodingKey {
        case preference
    }

    init() {
        preference = nil
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyAlipayX5fe7a2dea7 {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        preference = try container.sdkDecodeIfPresent(.preference)
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyAlipayX5fe7a2dea7 {
    init(preference: PostPaymentMethodConfigurationsConfigurationRequestBodyAlipayXe5e8edfa06? = nil) {
        self.init()
        self.preference = preference
    }
}

public struct PostPaymentMethodConfigurationsRequestBodyCustomerBalanceDispX5a3c570892: Codable {
    public var preference: PostPaymentMethodConfigurationsRequestBodyCustomerBalanceDispXf054630a88?

    enum CodingKeys: String, CodingKey {
        case preference
    }

    init() {
        preference = nil
    }
}

public extension PostPaymentMethodConfigurationsRequestBodyCustomerBalanceDispX5a3c570892 {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        preference = try container.sdkDecodeIfPresent(.preference)
    }
}

public extension PostPaymentMethodConfigurationsRequestBodyCustomerBalanceDispX5a3c570892 {
    init(preference: PostPaymentMethodConfigurationsRequestBodyCustomerBalanceDispXf054630a88? = nil) {
        self.init()
        self.preference = preference
    }
}

/// Twint is a payment method popular in Switzerland. It allows customers to pay using their mobile phone. Check
/// this page for more details.
public struct PostPaymentMethodConfigurationsConfigurationRequestBodyTwint: Codable {
    /// display_preference_param
    public var displayPreference: PostPaymentMethodConfigurationsConfigurationRequestBodyTwintDX17a66b567b?

    enum CodingKeys: String, CodingKey {
        case displayPreference = "display_preference"
    }

    init() {
        displayPreference = nil
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyTwint {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        displayPreference = try container.sdkDecodeIfPresent(.displayPreference)
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyTwint {
    init(displayPreference: PostPaymentMethodConfigurationsConfigurationRequestBodyTwintDX17a66b567b? = nil) {
        self.init()
        self.displayPreference = displayPreference
    }
}

public struct PostPaymentMethodConfigurationsConfigurationRequestBodyAfterpX8cabfcd767: Codable {
    public var preference: PostPaymentMethodConfigurationsConfigurationRequestBodyAfterpXe9e4e0d66d?

    enum CodingKeys: String, CodingKey {
        case preference
    }

    init() {
        preference = nil
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyAfterpX8cabfcd767 {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        preference = try container.sdkDecodeIfPresent(.preference)
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyAfterpX8cabfcd767 {
    init(preference: PostPaymentMethodConfigurationsConfigurationRequestBodyAfterpXe9e4e0d66d? = nil) {
        self.init()
        self.preference = preference
    }
}

/// Financial Process Exchange (FPX) is a Malaysia-based payment method that allows customers to complete
/// transactions online using their bank credentials. Bank Negara Malaysia (BNM), the Central Bank of Malaysia, and
/// eleven other major Malaysian financial institutions are members of the PayNet Group, which owns and operates
/// FPX. It is one of the most popular online payment methods in Malaysia, with nearly 90 million transactions in
/// 2018 according to BNM. Check this page for…
public struct PostPaymentMethodConfigurationsConfigurationRequestBodyFpx: Codable {
    /// display_preference_param
    public var displayPreference: PostPaymentMethodConfigurationsConfigurationRequestBodyFpxDisX68e60172d3?

    enum CodingKeys: String, CodingKey {
        case displayPreference = "display_preference"
    }

    init() {
        displayPreference = nil
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyFpx {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        displayPreference = try container.sdkDecodeIfPresent(.displayPreference)
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyFpx {
    init(displayPreference: PostPaymentMethodConfigurationsConfigurationRequestBodyFpxDisX68e60172d3? = nil) {
        self.init()
        self.displayPreference = displayPreference
    }
}

/// Unified Payment Interface (UPI) is India's leading payment method with exponential growth since it launched in
/// 2016.
public struct PostPaymentMethodConfigurationsConfigurationRequestBodyUpi: Codable {
    /// display_preference_param
    public var displayPreference: PostPaymentMethodConfigurationsConfigurationRequestBodyUpiDisX682d616685?

    enum CodingKeys: String, CodingKey {
        case displayPreference = "display_preference"
    }

    init() {
        displayPreference = nil
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyUpi {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        displayPreference = try container.sdkDecodeIfPresent(.displayPreference)
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyUpi {
    init(displayPreference: PostPaymentMethodConfigurationsConfigurationRequestBodyUpiDisX682d616685? = nil) {
        self.init()
        self.displayPreference = displayPreference
    }
}

/// Billie is a single-use payment method that offers businesses Pay by Invoice where they offer payment terms
/// ranging from 7-120 days. Customers are redirected from your website or app, authorize the payment with Billie,
/// then return to your website or app. You get immediate notification of whether the payment succeeded or failed.
public struct PostPaymentMethodConfigurationsRequestBodyBillie: Codable {
    /// display_preference_param
    public var displayPreference: PostPaymentMethodConfigurationsRequestBodyBillieDisplayPreference?

    enum CodingKeys: String, CodingKey {
        case displayPreference = "display_preference"
    }

    init() {
        displayPreference = nil
    }
}

public extension PostPaymentMethodConfigurationsRequestBodyBillie {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        displayPreference = try container.sdkDecodeIfPresent(.displayPreference)
    }
}

public extension PostPaymentMethodConfigurationsRequestBodyBillie {
    init(displayPreference: PostPaymentMethodConfigurationsRequestBodyBillieDisplayPreference? = nil) {
        self.init()
        self.displayPreference = displayPreference
    }
}

public struct PostPaymentMethodConfigurationsRequestBodyBacsDebitDisplayPreference: Codable {
    public var preference: PostPaymentMethodConfigurationsRequestBodyBacsDebitDisplayPreX4e0ff8c9c0?

    enum CodingKeys: String, CodingKey {
        case preference
    }

    init() {
        preference = nil
    }
}

public extension PostPaymentMethodConfigurationsRequestBodyBacsDebitDisplayPreference {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        preference = try container.sdkDecodeIfPresent(.preference)
    }
}

public extension PostPaymentMethodConfigurationsRequestBodyBacsDebitDisplayPreference {
    init(preference: PostPaymentMethodConfigurationsRequestBodyBacsDebitDisplayPreX4e0ff8c9c0? = nil) {
        self.init()
        self.preference = preference
    }
}

/// Stripe users can accept Apple Pay in iOS applications in iOS 9 and later, and on the web in Safari starting with
/// iOS 10 or macOS Sierra. There are no additional fees to process Apple Pay payments, and the pricing is the same
/// as other card transactions. Check this page for more details.
public struct PostPaymentMethodConfigurationsConfigurationRequestBodyApplePay: Codable {
    /// display_preference_param
    public var displayPreference: PostPaymentMethodConfigurationsConfigurationRequestBodyApplePXb8a4496944?

    enum CodingKeys: String, CodingKey {
        case displayPreference = "display_preference"
    }

    init() {
        displayPreference = nil
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyApplePay {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        displayPreference = try container.sdkDecodeIfPresent(.displayPreference)
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyApplePay {
    init(displayPreference: PostPaymentMethodConfigurationsConfigurationRequestBodyApplePXb8a4496944? = nil) {
        self.init()
        self.displayPreference = displayPreference
    }
}

/// Google Pay allows customers to make payments in your app or website using any credit or debit card saved to
/// their Google Account, including those from Google Play, YouTube, Chrome, or an Android device. Use the Google
/// Pay API to request any credit or debit card stored in your customer's Google account. Check this page for more
/// details.
public struct PostPaymentMethodConfigurationsConfigurationRequestBodyGooglePay: Codable {
    /// display_preference_param
    public var displayPreference: PostPaymentMethodConfigurationsConfigurationRequestBodyGoogleXefb0ca776f?

    enum CodingKeys: String, CodingKey {
        case displayPreference = "display_preference"
    }

    init() {
        displayPreference = nil
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyGooglePay {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        displayPreference = try container.sdkDecodeIfPresent(.displayPreference)
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyGooglePay {
    init(displayPreference: PostPaymentMethodConfigurationsConfigurationRequestBodyGoogleXefb0ca776f? = nil) {
        self.init()
        self.displayPreference = displayPreference
    }
}

/// Klarna gives customers a range of payment options during checkout. Available payment options vary depending on
/// the customer's billing address and the transaction amount. These payment options make it convenient for
/// customers to purchase items in all price ranges. Check this page for more details.
public struct PostPaymentMethodConfigurationsRequestBodyKlarna: Codable {
    /// display_preference_param
    public var displayPreference: PostPaymentMethodConfigurationsRequestBodyKlarnaDisplayPreference?

    enum CodingKeys: String, CodingKey {
        case displayPreference = "display_preference"
    }

    init() {
        displayPreference = nil
    }
}

public extension PostPaymentMethodConfigurationsRequestBodyKlarna {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        displayPreference = try container.sdkDecodeIfPresent(.displayPreference)
    }
}

public extension PostPaymentMethodConfigurationsRequestBodyKlarna {
    init(displayPreference: PostPaymentMethodConfigurationsRequestBodyKlarnaDisplayPreference? = nil) {
        self.init()
        self.displayPreference = displayPreference
    }
}

/// Cash App is a popular consumer app in the US that allows customers to bank, invest, send, and receive money
/// using their digital wallet. Check this page for more details.
public struct PostPaymentMethodConfigurationsConfigurationRequestBodyCashapp: Codable {
    /// display_preference_param
    public var displayPreference: PostPaymentMethodConfigurationsConfigurationRequestBodyCashapX56d8590073?

    enum CodingKeys: String, CodingKey {
        case displayPreference = "display_preference"
    }

    init() {
        displayPreference = nil
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyCashapp {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        displayPreference = try container.sdkDecodeIfPresent(.displayPreference)
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyCashapp {
    init(displayPreference: PostPaymentMethodConfigurationsConfigurationRequestBodyCashapX56d8590073? = nil) {
        self.init()
        self.displayPreference = displayPreference
    }
}

public struct PostPaymentMethodConfigurationsRequestBodyBlikDisplayPreference: Codable {
    public var preference: PostPaymentMethodConfigurationsRequestBodyBlikDisplayPreferenX84ba01e71f?

    enum CodingKeys: String, CodingKey {
        case preference
    }

    init() {
        preference = nil
    }
}

public extension PostPaymentMethodConfigurationsRequestBodyBlikDisplayPreference {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        preference = try container.sdkDecodeIfPresent(.preference)
    }
}

public extension PostPaymentMethodConfigurationsRequestBodyBlikDisplayPreference {
    init(preference: PostPaymentMethodConfigurationsRequestBodyBlikDisplayPreferenX84ba01e71f? = nil) {
        self.init()
        self.preference = preference
    }
}

/// Uses a customer’s cash balance for the payment. The cash balance can be funded via a bank transfer. Check this
/// page for more details.
public struct PostPaymentMethodConfigurationsConfigurationRequestBodyCustomerBalance: Codable {
    /// display_preference_param
    public var displayPreference: PostPaymentMethodConfigurationsConfigurationRequestBodyCustomXa6326d3acd?

    enum CodingKeys: String, CodingKey {
        case displayPreference = "display_preference"
    }

    init() {
        displayPreference = nil
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyCustomerBalance {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        displayPreference = try container.sdkDecodeIfPresent(.displayPreference)
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyCustomerBalance {
    init(displayPreference: PostPaymentMethodConfigurationsConfigurationRequestBodyCustomXa6326d3acd? = nil) {
        self.init()
        self.displayPreference = displayPreference
    }
}

public struct PostPaymentMethodConfigurationsRequestBodyFpxDisplayPreference: Codable {
    public var preference: PostPaymentMethodConfigurationsRequestBodyFpxDisplayPreferencePreference?

    enum CodingKeys: String, CodingKey {
        case preference
    }

    init() {
        preference = nil
    }
}

public extension PostPaymentMethodConfigurationsRequestBodyFpxDisplayPreference {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        preference = try container.sdkDecodeIfPresent(.preference)
    }
}

public extension PostPaymentMethodConfigurationsRequestBodyFpxDisplayPreference {
    init(preference: PostPaymentMethodConfigurationsRequestBodyFpxDisplayPreferencePreference? = nil) {
        self.init()
        self.preference = preference
    }
}

public struct PostPaymentMethodConfigurationsConfigurationRequestBodyCustomXa6326d3acd: Codable {
    public var preference: PostPaymentMethodConfigurationsConfigurationRequestBodyCustomX52fe88dd55?

    enum CodingKeys: String, CodingKey {
        case preference
    }

    init() {
        preference = nil
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyCustomXa6326d3acd {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        preference = try container.sdkDecodeIfPresent(.preference)
    }
}

public extension PostPaymentMethodConfigurationsConfigurationRequestBodyCustomXa6326d3acd {
    init(preference: PostPaymentMethodConfigurationsConfigurationRequestBodyCustomX52fe88dd55? = nil) {
        self.init()
        self.preference = preference
    }
}
