// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif

// Canonical v1BillingMeters operation model declarations
/// The default settings to aggregate a meter's events with.
public struct PostBillingMetersRequestBodyDefaultAggregation: Codable {
    public var formula: PostBillingMetersRequestBodyDefaultAggregationFormula

    enum CodingKeys: String, CodingKey {
        case formula
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostBillingMetersRequestBodyDefaultAggregation {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.formula) else {
            throw SdkValidationError(field: "formula", code: "required", message: "Validation failed for 'formula': value is required")
        }
        self.formula = try container.sdkDecodeRequired(.formula)
    }
}

public extension PostBillingMetersRequestBodyDefaultAggregation {
    public init(formula: PostBillingMetersRequestBodyDefaultAggregationFormula) {
        self.formula = formula
    }
}

/// Fields that specify how to map a meter event to a customer.
public struct PostBillingMetersRequestBodyCustomerMapping: Codable {
    public var eventPayloadKey: String
    public var type: PostBillingMetersRequestBodyCustomerMappingType

    enum CodingKeys: String, CodingKey {
        case eventPayloadKey = "event_payload_key"
        case type
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostBillingMetersRequestBodyCustomerMapping {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.eventPayloadKey) else {
            throw SdkValidationError(field: "event_payload_key", code: "required", message: "Validation failed for 'event_payload_key': value is required")
        }
        guard container.contains(.type) else {
            throw SdkValidationError(field: "type", code: "required", message: "Validation failed for 'type': value is required")
        }
        self.eventPayloadKey = try container.sdkDecodeRequired(.eventPayloadKey)
        self.type = try container.sdkDecodeRequired(.type)
            try validateLength("event_payload_key", self.eventPayloadKey, min: nil, max: 100)
    }
}

public extension PostBillingMetersRequestBodyCustomerMapping {
    public init(eventPayloadKey: String, type: PostBillingMetersRequestBodyCustomerMappingType) throws {
        (self.eventPayloadKey, self.type) = (eventPayloadKey, type)
            try validateLength("event_payload_key", self.eventPayloadKey, min: nil, max: 100)
    }
}

public struct GetBillingMetersResponse: Codable {
    public var data: [BillingMeter]
    /// True if this list has another page of items after this one that can be fetched.
    public var hasMore: Bool
    /// String representing the object's type. Objects of the same type share the same value. Always has the value
    /// `list`.
    public var object: GetBillingMetersResponseObject
    /// The URL where this list can be accessed.
    public var url: String

    enum CodingKeys: String, CodingKey {
        case data
        case hasMore = "has_more"
        case object
        case url
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension GetBillingMetersResponse {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.data) else {
            throw SdkValidationError(field: "data", code: "required", message: "Validation failed for 'data': value is required")
        }
        guard container.contains(.hasMore) else {
            throw SdkValidationError(field: "has_more", code: "required", message: "Validation failed for 'has_more': value is required")
        }
        guard container.contains(.object) else {
            throw SdkValidationError(field: "object", code: "required", message: "Validation failed for 'object': value is required")
        }
        guard container.contains(.url) else {
            throw SdkValidationError(field: "url", code: "required", message: "Validation failed for 'url': value is required")
        }
        self.data = try container.sdkDecodeRequired(.data)
        self.hasMore = try container.sdkDecodeRequired(.hasMore)
        self.object = try container.sdkDecodeRequired(.object)
        self.url = try container.sdkDecodeRequired(.url)
            try validateLength("url", self.url, min: nil, max: 5000)
            try sdkValidatePattern("url", self.url, sdkPatterna5aab75f5191)
    }
}

public extension GetBillingMetersResponse {
    public init(data: [BillingMeter], hasMore: Bool, object: GetBillingMetersResponseObject, url: String) throws {
        (self.data, self.hasMore) = (data, hasMore)
        (self.object, self.url) = (object, url)
            try validateLength("url", self.url, min: nil, max: 5000)
            try sdkValidatePattern("url", self.url, sdkPatterna5aab75f5191)
    }
}

/// Fields that specify how to calculate a meter event's value.
public struct PostBillingMetersRequestBodyValueSettings: Codable {
    public var eventPayloadKey: String

    enum CodingKeys: String, CodingKey {
        case eventPayloadKey = "event_payload_key"
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostBillingMetersRequestBodyValueSettings {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.eventPayloadKey) else {
            throw SdkValidationError(field: "event_payload_key", code: "required", message: "Validation failed for 'event_payload_key': value is required")
        }
        self.eventPayloadKey = try container.sdkDecodeRequired(.eventPayloadKey)
            try validateLength("event_payload_key", self.eventPayloadKey, min: nil, max: 100)
    }
}

public extension PostBillingMetersRequestBodyValueSettings {
    public init(eventPayloadKey: String) throws {
        self.eventPayloadKey = eventPayloadKey
            try validateLength("event_payload_key", self.eventPayloadKey, min: nil, max: 100)
    }
}
