// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif

// Canonical v1AccountsPeople operation model declarations
public enum PostAccountsAccountPeoplePersonRequestBodyMetadata {
    case dictionary([String: String])
    case stringValue(String)
}

extension PostAccountsAccountPeoplePersonRequestBodyMetadata: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostAccountsAccountPeoplePersonRequestBodyMetadata")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode([String: String].self) { return .dictionary(value) }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .dictionary(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public struct PostAccountsAccountPeopleRequestBodyDobVariant0: Codable {
    public var day: Int
    public var month: Int
    public var year: Int

    enum CodingKeys: String, CodingKey {
        case day
        case month
        case year
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostAccountsAccountPeopleRequestBodyDobVariant0 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.day) else {
            throw SdkValidationError(field: "day", code: "required", message: "Validation failed for 'day': value is required")
        }
        guard container.contains(.month) else {
            throw SdkValidationError(field: "month", code: "required", message: "Validation failed for 'month': value is required")
        }
        guard container.contains(.year) else {
            throw SdkValidationError(field: "year", code: "required", message: "Validation failed for 'year': value is required")
        }
        self.day = try container.sdkDecodeRequired(.day)
        self.month = try container.sdkDecodeRequired(.month)
        self.year = try container.sdkDecodeRequired(.year)
    }
}

public extension PostAccountsAccountPeopleRequestBodyDobVariant0 {
    public init(day: Int, month: Int, year: Int) {
        (self.day, self.month) = (day, month)
        self.year = year
    }
}

public enum PostAccountsAccountPeoplePersonRequestBodyDocumentsCompanyAutX6641d4dab2 {
    case stringValue(String)
    case stringValue1(String)
}

extension PostAccountsAccountPeoplePersonRequestBodyDocumentsCompanyAutX6641d4dab2: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostAccountsAccountPeoplePersonRequestBodyDocumentsCompanyAutX6641d4dab2")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        if let value = try? container.decode(String.self) { return .stringValue1(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .stringValue1(value): try container.encode(value); return true
        }
    }

}

/// Demographic data related to the person.
public struct PostAccountsAccountPeopleRequestBodyUsCfpbData: Codable {
    /// us_cfpb_ethnicity_details_specs
    public var ethnicityDetails: PostAccountsAccountPeopleRequestBodyUsCfpbDataEthnicityDetails?
    /// us_cfpb_race_details_specs
    public var raceDetails: PostAccountsAccountPeopleRequestBodyUsCfpbDataRaceDetails?
    public var selfIdentifiedGender: String?

    enum CodingKeys: String, CodingKey {
        case ethnicityDetails = "ethnicity_details"
        case raceDetails = "race_details"
        case selfIdentifiedGender = "self_identified_gender"
    }

    init() {
        (self.ethnicityDetails, self.raceDetails, self.selfIdentifiedGender) = (nil, nil, nil)
    }
}

public extension PostAccountsAccountPeopleRequestBodyUsCfpbData {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.ethnicityDetails = try container.sdkDecodeIfPresent(.ethnicityDetails)
        self.raceDetails = try container.sdkDecodeIfPresent(.raceDetails)
        self.selfIdentifiedGender = try container.sdkDecodeIfPresent(.selfIdentifiedGender)
        if let value = self.selfIdentifiedGender {
            try validateLength("self_identified_gender", value, min: nil, max: 5000)
        }
    }
}

public extension PostAccountsAccountPeopleRequestBodyUsCfpbData {
    public init(ethnicityDetails: PostAccountsAccountPeopleRequestBodyUsCfpbDataEthnicityDetails? = nil, raceDetails: PostAccountsAccountPeopleRequestBodyUsCfpbDataRaceDetails? = nil, selfIdentifiedGender: String? = nil) throws {
        self.init()
        (self.ethnicityDetails, self.raceDetails) = (ethnicityDetails, raceDetails)
        self.selfIdentifiedGender = selfIdentifiedGender
        if let value = self.selfIdentifiedGender {
            try validateLength("self_identified_gender", value, min: nil, max: 5000)
        }
    }
}

/// Demographic data related to the person.
public struct PostAccountsAccountPeoplePersonRequestBodyUsCfpbData: Codable {
    /// us_cfpb_ethnicity_details_specs
    public var ethnicityDetails: PostAccountsAccountPeoplePersonRequestBodyUsCfpbDataEthnicityDetails?
    /// us_cfpb_race_details_specs
    public var raceDetails: PostAccountsAccountPeoplePersonRequestBodyUsCfpbDataRaceDetails?
    public var selfIdentifiedGender: String?

    enum CodingKeys: String, CodingKey {
        case ethnicityDetails = "ethnicity_details"
        case raceDetails = "race_details"
        case selfIdentifiedGender = "self_identified_gender"
    }

    init() {
        (self.ethnicityDetails, self.raceDetails, self.selfIdentifiedGender) = (nil, nil, nil)
    }
}

public extension PostAccountsAccountPeoplePersonRequestBodyUsCfpbData {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.ethnicityDetails = try container.sdkDecodeIfPresent(.ethnicityDetails)
        self.raceDetails = try container.sdkDecodeIfPresent(.raceDetails)
        self.selfIdentifiedGender = try container.sdkDecodeIfPresent(.selfIdentifiedGender)
        if let value = self.selfIdentifiedGender {
            try validateLength("self_identified_gender", value, min: nil, max: 5000)
        }
    }
}

public extension PostAccountsAccountPeoplePersonRequestBodyUsCfpbData {
    public init(ethnicityDetails: PostAccountsAccountPeoplePersonRequestBodyUsCfpbDataEthnicityDetails? = nil, raceDetails: PostAccountsAccountPeoplePersonRequestBodyUsCfpbDataRaceDetails? = nil, selfIdentifiedGender: String? = nil) throws {
        self.init()
        (self.ethnicityDetails, self.raceDetails) = (ethnicityDetails, raceDetails)
        self.selfIdentifiedGender = selfIdentifiedGender
        if let value = self.selfIdentifiedGender {
            try validateLength("self_identified_gender", value, min: nil, max: 5000)
        }
    }
}

public typealias PostAccountsAccountPeoplePersonRequestBodyUsCfpbDataEthnicityXcc9aca482d = [PostAccountsAccountPeoplePersonRequestBodyUsCfpbDataEthnicityX2f377b7752]

public struct PostAccountsAccountPeoplePersonRequestBodyUsCfpbDataEthnicityDetails: Codable {
    public var ethnicity: PostAccountsAccountPeoplePersonRequestBodyUsCfpbDataEthnicityXcc9aca482d?
    public var ethnicityOther: String?

    enum CodingKeys: String, CodingKey {
        case ethnicity
        case ethnicityOther = "ethnicity_other"
    }

    init() {
        (self.ethnicity, self.ethnicityOther) = (nil, nil)
    }
}

public extension PostAccountsAccountPeoplePersonRequestBodyUsCfpbDataEthnicityDetails {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.ethnicity = try container.sdkDecodeIfPresent(.ethnicity)
        self.ethnicityOther = try container.sdkDecodeIfPresent(.ethnicityOther)
        if let value = self.ethnicityOther {
            try validateLength("ethnicity_other", value, min: nil, max: 5000)
        }
    }
}

public extension PostAccountsAccountPeoplePersonRequestBodyUsCfpbDataEthnicityDetails {
    public init(ethnicity: PostAccountsAccountPeoplePersonRequestBodyUsCfpbDataEthnicityXcc9aca482d? = nil, ethnicityOther: String? = nil) throws {
        self.init()
        (self.ethnicity, self.ethnicityOther) = (ethnicity, ethnicityOther)
        if let value = self.ethnicityOther {
            try validateLength("ethnicity_other", value, min: nil, max: 5000)
        }
    }
}

public struct PostAccountsAccountPeoplePersonRequestBodyVerificationDocument: Codable {
    public var back: String?
    public var front: String?

    enum CodingKeys: String, CodingKey {
        case back
        case front
    }

    init() {
        (self.back, self.front) = (nil, nil)
    }
}

public extension PostAccountsAccountPeoplePersonRequestBodyVerificationDocument {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.back = try container.sdkDecodeIfPresent(.back)
        self.front = try container.sdkDecodeIfPresent(.front)
        if let value = self.back {
            try validateLength("back", value, min: nil, max: 500)
        }
        if let value = self.front {
            try validateLength("front", value, min: nil, max: 500)
        }
    }
}

public extension PostAccountsAccountPeoplePersonRequestBodyVerificationDocument {
    public init(back: String? = nil, front: String? = nil) throws {
        self.init()
        (self.back, self.front) = (back, front)
        if let value = self.back {
            try validateLength("back", value, min: nil, max: 500)
        }
        if let value = self.front {
            try validateLength("front", value, min: nil, max: 500)
        }
    }
}

/// The relationship that this person has with the account's legal entity.
public struct PostAccountsAccountPeopleRequestBodyRelationship: Codable {
    public var authorizer: Bool?
    public var director: Bool?
    public var executive: Bool?
    public var legalGuardian: Bool?
    public var owner: Bool?
    public var percentOwnership: PostAccountsAccountPeopleRequestBodyRelationshipPercentOwnership?
    public var representative: Bool?
    public var title: String?

    enum CodingKeys: String, CodingKey {
        case authorizer
        case director
        case executive
        case legalGuardian = "legal_guardian"
        case owner
        case percentOwnership = "percent_ownership"
        case representative
        case title
    }

    init() {
        (self.authorizer, self.director, self.executive, self.legalGuardian, self.owner) = (nil, nil, nil, nil, nil)
        (self.percentOwnership, self.representative, self.title) = (nil, nil, nil)
    }
}

public extension PostAccountsAccountPeopleRequestBodyRelationship {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.authorizer = try container.sdkDecodeIfPresent(.authorizer)
        self.director = try container.sdkDecodeIfPresent(.director)
        self.executive = try container.sdkDecodeIfPresent(.executive)
        self.legalGuardian = try container.sdkDecodeIfPresent(.legalGuardian)
        self.owner = try container.sdkDecodeIfPresent(.owner)
        self.percentOwnership = try container.sdkDecodeIfPresent(.percentOwnership)
        self.representative = try container.sdkDecodeIfPresent(.representative)
        self.title = try container.sdkDecodeIfPresent(.title)
        if let value = self.title {
            try validateLength("title", value, min: nil, max: 5000)
        }
    }
}

public extension PostAccountsAccountPeopleRequestBodyRelationship {
    public init(authorizer: Bool? = nil, director: Bool? = nil, executive: Bool? = nil, legalGuardian: Bool? = nil, owner: Bool? = nil, percentOwnership: PostAccountsAccountPeopleRequestBodyRelationshipPercentOwnership? = nil, representative: Bool? = nil, title: String? = nil) throws {
        self.init()
        (self.authorizer, self.director) = (authorizer, director)
        (self.executive, self.legalGuardian) = (executive, legalGuardian)
        (self.owner, self.percentOwnership) = (owner, percentOwnership)
        (self.representative, self.title) = (representative, title)
        if let value = self.title {
            try validateLength("title", value, min: nil, max: 5000)
        }
    }
}

public struct GetAccountsAccountPeopleParameter: Codable {
    public var authorizer: Bool?
    public var director: Bool?
    public var executive: Bool?
    public var legalGuardian: Bool?
    public var owner: Bool?
    public var representative: Bool?

    enum CodingKeys: String, CodingKey {
        case authorizer
        case director
        case executive
        case legalGuardian = "legal_guardian"
        case owner
        case representative
    }

    init() {
        (self.authorizer, self.director, self.executive, self.legalGuardian, self.owner) = (nil, nil, nil, nil, nil)
        self.representative = nil
    }
}

public extension GetAccountsAccountPeopleParameter {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.authorizer = try container.sdkDecodeIfPresent(.authorizer)
        self.director = try container.sdkDecodeIfPresent(.director)
        self.executive = try container.sdkDecodeIfPresent(.executive)
        self.legalGuardian = try container.sdkDecodeIfPresent(.legalGuardian)
        self.owner = try container.sdkDecodeIfPresent(.owner)
        self.representative = try container.sdkDecodeIfPresent(.representative)
    }
}

public extension GetAccountsAccountPeopleParameter {
    public init(authorizer: Bool? = nil, director: Bool? = nil, executive: Bool? = nil, legalGuardian: Bool? = nil, owner: Bool? = nil, representative: Bool? = nil) {
        self.init()
        (self.authorizer, self.director) = (authorizer, director)
        (self.executive, self.legalGuardian) = (executive, legalGuardian)
        (self.owner, self.representative) = (owner, representative)
    }
}

public typealias PostAccountsAccountPeopleRequestBodyDocumentsPassportFilesList = [PostAccountsAccountPeopleRequestBodyDocumentsPassportFilesItem]

public struct PostAccountsAccountPeopleRequestBodyDocumentsPassport: Codable {
    public var files: PostAccountsAccountPeopleRequestBodyDocumentsPassportFilesList?

    enum CodingKeys: String, CodingKey {
        case files
    }

    init() {
        self.files = nil
    }
}

public extension PostAccountsAccountPeopleRequestBodyDocumentsPassport {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.files = try container.sdkDecodeIfPresent(.files)
    }
}

public extension PostAccountsAccountPeopleRequestBodyDocumentsPassport {
    public init(files: PostAccountsAccountPeopleRequestBodyDocumentsPassportFilesList? = nil) {
        self.init()
        self.files = files
    }
}

/// Details on the legal guardian's or authorizer's acceptance of the required Stripe agreements.
public struct PostAccountsAccountPeopleRequestBodyAdditionalTosAcceptances: Codable {
    /// settings_terms_of_service_specs
    public var account: PostAccountsAccountPeopleRequestBodyAdditionalTosAcceptancesAccount?

    enum CodingKeys: String, CodingKey {
        case account
    }

    init() {
        self.account = nil
    }
}

public extension PostAccountsAccountPeopleRequestBodyAdditionalTosAcceptances {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.account = try container.sdkDecodeIfPresent(.account)
    }
}

public extension PostAccountsAccountPeopleRequestBodyAdditionalTosAcceptances {
    public init(account: PostAccountsAccountPeopleRequestBodyAdditionalTosAcceptancesAccount? = nil) {
        self.init()
        self.account = account
    }
}

/// The person's address.
public struct PostAccountsAccountPeopleRequestBodyAddress: Codable {
    public var city: String?
    public var country: String?
    public var line1: String?
    public var line2: String?
    public var postalCode: String?
    public var state: String?

    enum CodingKeys: String, CodingKey {
        case city
        case country
        case line1
        case line2
        case postalCode = "postal_code"
        case state
    }

    init() {
        (self.city, self.country, self.line1, self.line2, self.postalCode) = (nil, nil, nil, nil, nil)
        self.state = nil
    }
}

public extension PostAccountsAccountPeopleRequestBodyAddress {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.city = try container.sdkDecodeIfPresent(.city)
        self.country = try container.sdkDecodeIfPresent(.country)
        self.line1 = try container.sdkDecodeIfPresent(.line1)
        self.line2 = try container.sdkDecodeIfPresent(.line2)
        self.postalCode = try container.sdkDecodeIfPresent(.postalCode)
        self.state = try container.sdkDecodeIfPresent(.state)
        if let value = self.city {
            try validateLength("city", value, min: nil, max: 100)
        }
        if let value = self.country {
            try validateLength("country", value, min: nil, max: 5000)
        }
        if let value = self.line1 {
            try validateLength("line1", value, min: nil, max: 200)
        }
        if let value = self.line2 {
            try validateLength("line2", value, min: nil, max: 200)
        }
        if let value = self.postalCode {
            try validateLength("postal_code", value, min: nil, max: 5000)
        }
        if let value = self.state {
            try validateLength("state", value, min: nil, max: 5000)
        }
    }
}

public extension PostAccountsAccountPeopleRequestBodyAddress {
    public init(city: String? = nil, country: String? = nil, line1: String? = nil, line2: String? = nil, postalCode: String? = nil, state: String? = nil) throws {
        self.init()
        (self.city, self.country) = (city, country)
        (self.line1, self.line2) = (line1, line2)
        (self.postalCode, self.state) = (postalCode, state)
        if let value = self.city {
            try validateLength("city", value, min: nil, max: 100)
        }
        if let value = self.country {
            try validateLength("country", value, min: nil, max: 5000)
        }
        if let value = self.line1 {
            try validateLength("line1", value, min: nil, max: 200)
        }
        if let value = self.line2 {
            try validateLength("line2", value, min: nil, max: 200)
        }
        if let value = self.postalCode {
            try validateLength("postal_code", value, min: nil, max: 5000)
        }
        if let value = self.state {
            try validateLength("state", value, min: nil, max: 5000)
        }
    }
}

public struct PostAccountsAccountPeoplePersonRequestBodyDobVariant0: Codable {
    public var day: Int
    public var month: Int
    public var year: Int

    enum CodingKeys: String, CodingKey {
        case day
        case month
        case year
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostAccountsAccountPeoplePersonRequestBodyDobVariant0 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.day) else {
            throw SdkValidationError(field: "day", code: "required", message: "Validation failed for 'day': value is required")
        }
        guard container.contains(.month) else {
            throw SdkValidationError(field: "month", code: "required", message: "Validation failed for 'month': value is required")
        }
        guard container.contains(.year) else {
            throw SdkValidationError(field: "year", code: "required", message: "Validation failed for 'year': value is required")
        }
        self.day = try container.sdkDecodeRequired(.day)
        self.month = try container.sdkDecodeRequired(.month)
        self.year = try container.sdkDecodeRequired(.year)
    }
}

public extension PostAccountsAccountPeoplePersonRequestBodyDobVariant0 {
    public init(day: Int, month: Int, year: Int) {
        (self.day, self.month) = (day, month)
        self.year = year
    }
}
