// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif

// Canonical v1Subscriptions operation model declarations
extension PostSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioX8e5498b12e {
    public init(amount: Int? = nil, amountIncludesIof: PostSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioX3b5f9f6d1c? = nil, endDate: String? = nil, paymentSchedule: PostSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioX43aef06710? = nil) throws {
        self.init()
        (self.amount, self.amountIncludesIof) = (amount, amountIncludesIof)
        (self.endDate, self.paymentSchedule) = (endDate, paymentSchedule)
        if let value = self.endDate {
            try validateLength("end_date", value, min: nil, max: 5000)
        }
    }
}

public enum PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiXbba21c2de1 {
    case postSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiX5ccb2792cf(
        PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiX5ccb2792cf
    )
    case stringValue(String)
}

extension PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiXbba21c2de1: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiXbba21c2de1")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiX5ccb2792cf.self
        ) {
            return             .postSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiX5ccb2792cf(value)
        }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiX5ccb2792cf(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public enum PostSubscriptionsRequestBodyDiscounts {
    case postSubscriptionsRequestBodyDiscountsVariant0ItemList([PostSubscriptionsRequestBodyDiscountsVariant0Item])
    case stringValue(String)
}

extension PostSubscriptionsRequestBodyDiscounts: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostSubscriptionsRequestBodyDiscounts")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            [PostSubscriptionsRequestBodyDiscountsVariant0Item].self
        ) {
            return             .postSubscriptionsRequestBodyDiscountsVariant0ItemList(value)
        }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postSubscriptionsRequestBodyDiscountsVariant0ItemList(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public struct PostSubscriptionsRequestBodyPendingInvoiceItemIntervalVariant0: Codable {
    public var interval: PostSubscriptionsRequestBodyPendingInvoiceItemIntervalVariant0Interval
    public var intervalCount: Int?

    enum CodingKeys: String, CodingKey {
        case interval
        case intervalCount = "interval_count"
    }

    private init(sdkCopy value: Self) { self = value }
}

extension PostSubscriptionsRequestBodyPendingInvoiceItemIntervalVariant0 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.interval) else {
            throw SdkValidationError(field: "interval", code: "required", message: "Validation failed for 'interval': value is required")
        }
        self.interval = try container.sdkDecodeRequired(.interval)
        self.intervalCount = try container.sdkDecodeIfPresent(.intervalCount)
    }
}

extension PostSubscriptionsRequestBodyPendingInvoiceItemIntervalVariant0 {
    public init(interval: PostSubscriptionsRequestBodyPendingInvoiceItemIntervalVariant0Interval, intervalCount: Int? = nil) {
        (self.interval, self.intervalCount) = (interval, intervalCount)
    }
}

public struct PostSubscriptionsRequestBodyAddInvoiceItemsItemPriceData: Codable {
    public var currency: String
    public var product: String
    public var taxBehavior: PostSubscriptionsRequestBodyAddInvoiceItemsItemPriceDataTaxBehavior?
    public var unitAmount: Int?
    public var unitAmountDecimal: String?

    enum CodingKeys: String, CodingKey {
        case currency
        case product
        case taxBehavior = "tax_behavior"
        case unitAmount = "unit_amount"
        case unitAmountDecimal = "unit_amount_decimal"
    }

    private init(sdkCopy value: Self) { self = value }
}

extension PostSubscriptionsRequestBodyAddInvoiceItemsItemPriceData {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.currency) else {
            throw SdkValidationError(field: "currency", code: "required", message: "Validation failed for 'currency': value is required")
        }
        guard container.contains(.product) else {
            throw SdkValidationError(field: "product", code: "required", message: "Validation failed for 'product': value is required")
        }
        self.currency = try container.sdkDecodeRequired(.currency)
        self.product = try container.sdkDecodeRequired(.product)
        self.taxBehavior = try container.sdkDecodeIfPresent(.taxBehavior)
        self.unitAmount = try container.sdkDecodeIfPresent(.unitAmount)
        self.unitAmountDecimal = try container.sdkDecodeIfPresent(.unitAmountDecimal)
            try validateLength("product", self.product, min: nil, max: 5000)
    }
}

extension PostSubscriptionsRequestBodyAddInvoiceItemsItemPriceData {
    public init(currency: String, product: String, taxBehavior: PostSubscriptionsRequestBodyAddInvoiceItemsItemPriceDataTaxBehavior? = nil, unitAmount: Int? = nil, unitAmountDecimal: String? = nil) throws {
        (self.currency, self.product) = (currency, product)
        (self.taxBehavior, self.unitAmount) = (taxBehavior, unitAmount)
        self.unitAmountDecimal = unitAmountDecimal
            try validateLength("product", self.product, min: nil, max: 5000)
    }
}

public enum PostSubscriptionsSubscriptionExposedIdRequestBodyItemsItemMetadata {
    case dictionary([String: String])
    case stringValue(String)
}

extension PostSubscriptionsSubscriptionExposedIdRequestBodyItemsItemMetadata: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostSubscriptionsSubscriptionExposedIdRequestBodyItemsItemMetadata")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode([String: String].self) { return .dictionary(value) }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .dictionary(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public struct PostSubscriptionsSubscriptionExposedIdRequestBodyBillingSchedX11ad497db1: Codable {
    public var type: PostSubscriptionsSubscriptionExposedIdRequestBodyBillingSchedXf13a2283eb
    public var price: String?

    enum CodingKeys: String, CodingKey {
        case type
        case price
    }

    private init(sdkCopy value: Self) { self = value }
}

extension PostSubscriptionsSubscriptionExposedIdRequestBodyBillingSchedX11ad497db1 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.type) else {
            throw SdkValidationError(field: "type", code: "required", message: "Validation failed for 'type': value is required")
        }
        self.type = try container.sdkDecodeRequired(.type)
        self.price = try container.sdkDecodeIfPresent(.price)
        if let value = self.price {
            try validateLength("price", value, min: nil, max: 5000)
        }
    }
}

extension PostSubscriptionsSubscriptionExposedIdRequestBodyBillingSchedX11ad497db1 {
    public init(type: PostSubscriptionsSubscriptionExposedIdRequestBodyBillingSchedXf13a2283eb, price: String? = nil) throws {
        (self.type, self.price) = (type, price)
        if let value = self.price {
            try validateLength("price", value, min: nil, max: 5000)
        }
    }
}

public enum PostSubscriptionsSubscriptionExposedIdRequestBodyTrialEnd {
    case stringValue(String)
    case intValue(Int)
}

extension PostSubscriptionsSubscriptionExposedIdRequestBodyTrialEnd: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostSubscriptionsSubscriptionExposedIdRequestBodyTrialEnd")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        if let value = try? container.decode(Int.self) { return .intValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .intValue(value): try container.encode(value); return true
        }
    }

}

public enum GetSubscriptionsParameterX3b560d97 {
    case getSubscriptionsParameterVariant0Xc5adc99b(GetSubscriptionsParameterVariant0Xc5adc99b)
    case intValue(Int)
}

extension GetSubscriptionsParameterX3b560d97: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for GetSubscriptionsParameterX3b560d97")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            GetSubscriptionsParameterVariant0Xc5adc99b.self
        ) {
            return             .getSubscriptionsParameterVariant0Xc5adc99b(value)
        }
        if let value = try? container.decode(Int.self) { return .intValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .getSubscriptionsParameterVariant0Xc5adc99b(value): try container.encode(value); return true
        case let .intValue(value): try container.encode(value); return true
        }
    }

}

public enum PostSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioX3c979b7e14 {
    case postSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioXa3b73acea5(
        PostSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioXa3b73acea5
    )
    case stringValue(String)
}

extension PostSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioX3c979b7e14: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioX3c979b7e14")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PostSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioXa3b73acea5.self
        ) {
            return             .postSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioXa3b73acea5(value)
        }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioXa3b73acea5(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public enum PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiX1e72cf7655 {
    case postSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiX5c0dc046b3(
        PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiX5c0dc046b3
    )
    case stringValue(String)
}

extension PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiX1e72cf7655: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiX1e72cf7655")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiX5c0dc046b3.self
        ) {
            return             .postSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiX5c0dc046b3(value)
        }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiX5c0dc046b3(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public enum PostSubscriptionsRequestBodyCancelAt {
    case intValue(Int)
    case stringValue(String)
}

extension PostSubscriptionsRequestBodyCancelAt: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostSubscriptionsRequestBodyCancelAt")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(Int.self) { return .intValue(value) }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .intValue(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public enum PostSubscriptionsRequestBodyApplicationFeePercent {
    case doubleValue(Double)
    case stringValue(String)
}

extension PostSubscriptionsRequestBodyApplicationFeePercent: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostSubscriptionsRequestBodyApplicationFeePercent")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(Double.self) { return .doubleValue(value) }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .doubleValue(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public struct PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiXa1a4f63b71: Codable {
    /// mandate_options_param
    public var mandateOptions: PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiX16120ea044?
    public var network: PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiXaeadcb3b8a?
    public var requestThreeDSecure: PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiXf51e648d14?

    enum CodingKeys: String, CodingKey {
        case mandateOptions = "mandate_options"
        case network
        case requestThreeDSecure = "request_three_d_secure"
    }

    init() {
        (self.mandateOptions, self.network, self.requestThreeDSecure) = (nil, nil, nil)
    }
}

extension PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiXa1a4f63b71 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.mandateOptions = try container.sdkDecodeIfPresent(.mandateOptions)
        self.network = try container.sdkDecodeIfPresent(.network)
        self.requestThreeDSecure = try container.sdkDecodeIfPresent(.requestThreeDSecure)
        if let value = self.network {
            try validateLength("network", sdkWireString(value), min: nil, max: 5000)
        }
    }
}

extension PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiXa1a4f63b71 {
    public init(mandateOptions: PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiX16120ea044? = nil, network: PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiXaeadcb3b8a? = nil, requestThreeDSecure: PostSubscriptionsSubscriptionExposedIdRequestBodyPaymentSettiXf51e648d14? = nil) throws {
        self.init()
        (self.mandateOptions, self.network) = (mandateOptions, network)
        self.requestThreeDSecure = requestThreeDSecure
        if let value = self.network {
            try validateLength("network", sdkWireString(value), min: nil, max: 5000)
        }
    }
}

public struct PostSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioX06d380d236: Codable {
    /// mandate_options_param
    public var mandateOptions: PostSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioX2dc08403d7?
    public var verificationMethod: PostSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioXb77a108e0f?

    enum CodingKeys: String, CodingKey {
        case mandateOptions = "mandate_options"
        case verificationMethod = "verification_method"
    }

    init() {
        (self.mandateOptions, self.verificationMethod) = (nil, nil)
    }
}

extension PostSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioX06d380d236 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.mandateOptions = try container.sdkDecodeIfPresent(.mandateOptions)
        self.verificationMethod = try container.sdkDecodeIfPresent(.verificationMethod)
    }
}

extension PostSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioX06d380d236 {
    public init(mandateOptions: PostSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioX2dc08403d7? = nil, verificationMethod: PostSubscriptionsRequestBodyPaymentSettingsPaymentMethodOptioXb77a108e0f? = nil) {
        self.init()
        (self.mandateOptions, self.verificationMethod) = (mandateOptions, verificationMethod)
    }
}

public struct PostSubscriptionsRequestBodyAddInvoiceItemsItemPeriodStart: Codable {
    public var type: PostSubscriptionsRequestBodyAddInvoiceItemsItemPeriodStartType
    public var timestamp: Int?

    enum CodingKeys: String, CodingKey {
        case type
        case timestamp
    }

    private init(sdkCopy value: Self) { self = value }
}

extension PostSubscriptionsRequestBodyAddInvoiceItemsItemPeriodStart {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.type) else {
            throw SdkValidationError(field: "type", code: "required", message: "Validation failed for 'type': value is required")
        }
        self.type = try container.sdkDecodeRequired(.type)
        self.timestamp = try container.sdkDecodeIfPresent(.timestamp)
    }
}
