// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif

// Canonical v1PaymentIntents operation model declarations
extension PostPaymentIntentsIntentRequestBodyShippingVariant0Address {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.city = try container.sdkDecodeIfPresent(.city)
        self.country = try container.sdkDecodeIfPresent(.country)
        self.line1 = try container.sdkDecodeIfPresent(.line1)
        self.line2 = try container.sdkDecodeIfPresent(.line2)
        self.postalCode = try container.sdkDecodeIfPresent(.postalCode)
        self.state = try container.sdkDecodeIfPresent(.state)
        if let value = self.city {
            try validateLength("city", value, min: nil, max: 5000)
        }
        if let value = self.country {
            try validateLength("country", value, min: nil, max: 5000)
        }
        if let value = self.line1 {
            try validateLength("line1", value, min: nil, max: 5000)
        }
        if let value = self.line2 {
            try validateLength("line2", value, min: nil, max: 5000)
        }
        if let value = self.postalCode {
            try validateLength("postal_code", value, min: nil, max: 5000)
        }
        if let value = self.state {
            try validateLength("state", value, min: nil, max: 5000)
        }
    }
}

extension PostPaymentIntentsIntentRequestBodyShippingVariant0Address {
    public init(city: String? = nil, country: String? = nil, line1: String? = nil, line2: String? = nil, postalCode: String? = nil, state: String? = nil) throws {
        self.init()
        (self.city, self.country) = (city, country)
        (self.line1, self.line2) = (line1, line2)
        (self.postalCode, self.state) = (postalCode, state)
        if let value = self.city {
            try validateLength("city", value, min: nil, max: 5000)
        }
        if let value = self.country {
            try validateLength("country", value, min: nil, max: 5000)
        }
        if let value = self.line1 {
            try validateLength("line1", value, min: nil, max: 5000)
        }
        if let value = self.line2 {
            try validateLength("line2", value, min: nil, max: 5000)
        }
        if let value = self.postalCode {
            try validateLength("postal_code", value, min: nil, max: 5000)
        }
        if let value = self.state {
            try validateLength("state", value, min: nil, max: 5000)
        }
    }
}

public struct PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsPixVariant0: Codable {
    public var amountIncludesIof: PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsPixVarX8a049e7d87?
    public var expiresAfterSeconds: Int?
    public var expiresAt: Int?
    /// payment_method_options_mandate_options_param
    public var mandateOptions: PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsPixVarX3cd6f1f2bc?
    public var setupFutureUsage: PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsPixVarX9c9f2c14a1?

    enum CodingKeys: String, CodingKey {
        case amountIncludesIof = "amount_includes_iof"
        case expiresAfterSeconds = "expires_after_seconds"
        case expiresAt = "expires_at"
        case mandateOptions = "mandate_options"
        case setupFutureUsage = "setup_future_usage"
    }

    init() {
        (self.amountIncludesIof, self.expiresAfterSeconds, self.expiresAt, self.mandateOptions, self.setupFutureUsage) = (nil, nil, nil, nil, nil)
    }
}

extension PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsPixVariant0 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.amountIncludesIof = try container.sdkDecodeIfPresent(.amountIncludesIof)
        self.expiresAfterSeconds = try container.sdkDecodeIfPresent(.expiresAfterSeconds)
        self.expiresAt = try container.sdkDecodeIfPresent(.expiresAt)
        self.mandateOptions = try container.sdkDecodeIfPresent(.mandateOptions)
        self.setupFutureUsage = try container.sdkDecodeIfPresent(.setupFutureUsage)
    }
}

extension PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsPixVariant0 {
    public init(amountIncludesIof: PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsPixVarX8a049e7d87? = nil, expiresAfterSeconds: Int? = nil, expiresAt: Int? = nil, mandateOptions: PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsPixVarX3cd6f1f2bc? = nil, setupFutureUsage: PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsPixVarX9c9f2c14a1? = nil) {
        self.init()
        (self.amountIncludesIof, self.expiresAfterSeconds) = (amountIncludesIof, expiresAfterSeconds)
        (self.expiresAt, self.mandateOptions) = (expiresAt, mandateOptions)
        self.setupFutureUsage = setupFutureUsage
    }
}

public struct PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsBizumVariant0: Codable {

    private init(sdkCopy value: Self) { self = value }
}

extension PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsBizumVariant0 {
    public init() {
    }
}

public enum PostPaymentIntentsRequestBodyAmountDetailsShippingVariant0FromPostalCode {
    case stringValue(String)
    case stringValue1(String)
}

extension PostPaymentIntentsRequestBodyAmountDetailsShippingVariant0FromPostalCode: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostPaymentIntentsRequestBodyAmountDetailsShippingVariant0FromPostalCode")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        if let value = try? container.decode(String.self) { return .stringValue1(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .stringValue1(value): try container.encode(value); return true
        }
    }

}

public enum PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsKlarna {
    case postPaymentIntentsIntentRequestBodyPaymentMethodOptionsKlarnaVariant0(
        PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsKlarnaVariant0
    )
    case stringValue(String)
}

extension PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsKlarna: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsKlarna")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsKlarnaVariant0.self
        ) {
            return             .postPaymentIntentsIntentRequestBodyPaymentMethodOptionsKlarnaVariant0(value)
        }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postPaymentIntentsIntentRequestBodyPaymentMethodOptionsKlarnaVariant0(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public enum PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsKonbinXc90eba0a85 {
    case intValue(Int)
    case stringValue(String)
}

extension PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsKonbinXc90eba0a85: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsKonbinXc90eba0a85")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(Int.self) { return .intValue(value) }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .intValue(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public enum PostPaymentIntentsRequestBodyPaymentMethodOptionsPaytoVariantXf18cf487e3 {
    case stringValue(String)
    case stringValue1(String)
}

extension PostPaymentIntentsRequestBodyPaymentMethodOptionsPaytoVariantXf18cf487e3: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostPaymentIntentsRequestBodyPaymentMethodOptionsPaytoVariantXf18cf487e3")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        if let value = try? container.decode(String.self) { return .stringValue1(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .stringValue1(value): try container.encode(value); return true
        }
    }

}

public struct PostPaymentIntentsIntentRequestBodyPaymentDetailsVariant0: Codable {
    public var customerReference: PostPaymentIntentsIntentRequestBodyPaymentDetailsVariant0CustXaca2c1686f?
    public var orderReference: PostPaymentIntentsIntentRequestBodyPaymentDetailsVariant0OrderReference?

    enum CodingKeys: String, CodingKey {
        case customerReference = "customer_reference"
        case orderReference = "order_reference"
    }

    init() {
        (self.customerReference, self.orderReference) = (nil, nil)
    }
}

extension PostPaymentIntentsIntentRequestBodyPaymentDetailsVariant0 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.customerReference = try container.sdkDecodeIfPresent(.customerReference)
        self.orderReference = try container.sdkDecodeIfPresent(.orderReference)
    }
}

extension PostPaymentIntentsIntentRequestBodyPaymentDetailsVariant0 {
    public init(customerReference: PostPaymentIntentsIntentRequestBodyPaymentDetailsVariant0CustXaca2c1686f? = nil, orderReference: PostPaymentIntentsIntentRequestBodyPaymentDetailsVariant0OrderReference? = nil) {
        self.init()
        (self.customerReference, self.orderReference) = (customerReference, orderReference)
    }
}

public struct PostPaymentIntentsRequestBodyPaymentMethodDataSwish: Codable {

    private init(sdkCopy value: Self) { self = value }
}

extension PostPaymentIntentsRequestBodyPaymentMethodDataSwish {
    public init() {
    }
}

public typealias PostPaymentIntentsRequestBodyPaymentMethodOptionsCardVariant0Xe0d6954308 = [PostPaymentIntentsRequestBodyPaymentMethodOptionsCardVariant0Xe8e4441fa0]

public struct PostPaymentIntentsRequestBodyPaymentMethodOptionsCardVariant0X0443951479: Codable {
    public var amount: Int
    public var amountType: PostPaymentIntentsRequestBodyPaymentMethodOptionsCardVariant0X98657e82d8
    public var interval: PostPaymentIntentsRequestBodyPaymentMethodOptionsCardVariant0X8821019292
    public var reference: String
    public var startDate: Int
    public var description: String?
    public var endDate: Int?
    public var intervalCount: Int?
    public var supportedTypes: PostPaymentIntentsRequestBodyPaymentMethodOptionsCardVariant0Xe0d6954308?

    enum CodingKeys: String, CodingKey {
        case amount
        case amountType = "amount_type"
        case interval
        case reference
        case startDate = "start_date"
        case description
        case endDate = "end_date"
        case intervalCount = "interval_count"
        case supportedTypes = "supported_types"
    }

    private init(sdkCopy value: Self) { self = value }
}

extension PostPaymentIntentsRequestBodyPaymentMethodOptionsCardVariant0X0443951479 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.amount) else {
            throw SdkValidationError(field: "amount", code: "required", message: "Validation failed for 'amount': value is required")
        }
        guard container.contains(.amountType) else {
            throw SdkValidationError(field: "amount_type", code: "required", message: "Validation failed for 'amount_type': value is required")
        }
        guard container.contains(.interval) else {
            throw SdkValidationError(field: "interval", code: "required", message: "Validation failed for 'interval': value is required")
        }
        guard container.contains(.reference) else {
            throw SdkValidationError(field: "reference", code: "required", message: "Validation failed for 'reference': value is required")
        }
        guard container.contains(.startDate) else {
            throw SdkValidationError(field: "start_date", code: "required", message: "Validation failed for 'start_date': value is required")
        }
        self.amount = try container.sdkDecodeRequired(.amount)
        self.amountType = try container.sdkDecodeRequired(.amountType)
        self.interval = try container.sdkDecodeRequired(.interval)
        self.reference = try container.sdkDecodeRequired(.reference)
        self.startDate = try container.sdkDecodeRequired(.startDate)
        self.description = try container.sdkDecodeIfPresent(.description)
        self.endDate = try container.sdkDecodeIfPresent(.endDate)
        self.intervalCount = try container.sdkDecodeIfPresent(.intervalCount)
        self.supportedTypes = try container.sdkDecodeIfPresent(.supportedTypes)
            try validateLength("reference", self.reference, min: nil, max: 80)
        if let value = self.description {
            try validateLength("description", value, min: nil, max: 200)
        }
    }
}

extension PostPaymentIntentsRequestBodyPaymentMethodOptionsCardVariant0X0443951479 {
    public init(amount: Int, amountType: PostPaymentIntentsRequestBodyPaymentMethodOptionsCardVariant0X98657e82d8, interval: PostPaymentIntentsRequestBodyPaymentMethodOptionsCardVariant0X8821019292, reference: String, startDate: Int, description: String? = nil, endDate: Int? = nil, intervalCount: Int? = nil, supportedTypes: PostPaymentIntentsRequestBodyPaymentMethodOptionsCardVariant0Xe0d6954308? = nil) throws {
        (self.amount, self.amountType) = (amount, amountType)
        (self.interval, self.reference) = (interval, reference)
        (self.startDate, self.description) = (startDate, description)
        (self.endDate, self.intervalCount) = (endDate, intervalCount)
        self.supportedTypes = supportedTypes
            try validateLength("reference", self.reference, min: nil, max: 80)
        if let value = self.description {
            try validateLength("description", value, min: nil, max: 200)
        }
    }
}

public struct PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsNzBankX4925b6160c: Codable {
    public var setupFutureUsage: PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsNzBankX32e8ec238b?
    public var targetDate: String?

    enum CodingKeys: String, CodingKey {
        case setupFutureUsage = "setup_future_usage"
        case targetDate = "target_date"
    }

    init() {
        (self.setupFutureUsage, self.targetDate) = (nil, nil)
    }
}

extension PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsNzBankX4925b6160c {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.setupFutureUsage = try container.sdkDecodeIfPresent(.setupFutureUsage)
        self.targetDate = try container.sdkDecodeIfPresent(.targetDate)
        if let value = self.targetDate {
            try validateLength("target_date", value, min: nil, max: 5000)
        }
    }
}

extension PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsNzBankX4925b6160c {
    public init(setupFutureUsage: PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsNzBankX32e8ec238b? = nil, targetDate: String? = nil) throws {
        self.init()
        (self.setupFutureUsage, self.targetDate) = (setupFutureUsage, targetDate)
        if let value = self.targetDate {
            try validateLength("target_date", value, min: nil, max: 5000)
        }
    }
}

public struct PostPaymentIntentsRequestBodyPaymentMethodDataKonbini: Codable {

    private init(sdkCopy value: Self) { self = value }
}

extension PostPaymentIntentsRequestBodyPaymentMethodDataKonbini {
    public init() {
    }
}

public enum PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsBancontact {
    case postPaymentIntentsIntentRequestBodyPaymentMethodOptionsBanconX857fed5846(
        PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsBanconX857fed5846
    )
    case stringValue(String)
}

extension PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsBancontact: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsBancontact")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsBanconX857fed5846.self
        ) {
            return             .postPaymentIntentsIntentRequestBodyPaymentMethodOptionsBanconX857fed5846(value)
        }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postPaymentIntentsIntentRequestBodyPaymentMethodOptionsBanconX857fed5846(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public struct PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUpiVarXaf79f9216b: Codable {
    public var amount: Int?
    public var amountType: PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUpiVarX0f64d41f4a?
    public var description: String?
    public var endDate: Int?

    enum CodingKeys: String, CodingKey {
        case amount
        case amountType = "amount_type"
        case description
        case endDate = "end_date"
    }

    init() {
        (self.amount, self.amountType, self.description, self.endDate) = (nil, nil, nil, nil)
    }
}

extension PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUpiVarXaf79f9216b {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.amount = try container.sdkDecodeIfPresent(.amount)
        self.amountType = try container.sdkDecodeIfPresent(.amountType)
        self.description = try container.sdkDecodeIfPresent(.description)
        self.endDate = try container.sdkDecodeIfPresent(.endDate)
        if let value = self.description {
            try validateLength("description", value, min: nil, max: 20)
        }
    }
}

extension PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUpiVarXaf79f9216b {
    public init(amount: Int? = nil, amountType: PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUpiVarX0f64d41f4a? = nil, description: String? = nil, endDate: Int? = nil) throws {
        self.init()
        (self.amount, self.amountType) = (amount, amountType)
        (self.description, self.endDate) = (description, endDate)
        if let value = self.description {
            try validateLength("description", value, min: nil, max: 20)
        }
    }
}

public enum PostPaymentIntentsRequestBodyPaymentMethodOptionsKonbiniVariaX25686ec367 {
    case intValue(Int)
    case stringValue(String)
}

extension PostPaymentIntentsRequestBodyPaymentMethodOptionsKonbiniVariaX25686ec367: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostPaymentIntentsRequestBodyPaymentMethodOptionsKonbiniVariaX25686ec367")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(Int.self) { return .intValue(value) }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .intValue(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}
