// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif

// Canonical v1IssuingDisputes operation model declarations
extension PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0 {
    public init(additionalDocumentation: String? = nil, canceledAt: PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0CanceledAt? = nil, cancellationPolicyProvided: PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0Xb83566f6a8? = nil, cancellationReason: PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0X7e87fbd4c4? = nil, expectedAt: PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0ExpectedAt? = nil, explanation: PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0Explanation? = nil, productDescription: PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0Xc2ce3f5115? = nil, productType: PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0ProductType? = nil, returnStatus: PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0Xae57ebcb41? = nil, returnedAt: PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0ReturnedAt? = nil) {
        self.init()
        (self.additionalDocumentation, self.canceledAt) = (additionalDocumentation, canceledAt)
        self.cancellationPolicyProvided = cancellationPolicyProvided
        (self.cancellationReason, self.expectedAt) = (cancellationReason, expectedAt)
        (self.explanation, self.productDescription) = (explanation, productDescription)
        (self.productType, self.returnStatus) = (productType, returnStatus)
        self.returnedAt = returnedAt
    }
}

public enum PostIssuingDisputesDisputeRequestBodyEvidenceMerchandiseNotAsX81f2f416af {
    case intValue(Int)
    case stringValue(String)
}

extension PostIssuingDisputesDisputeRequestBodyEvidenceMerchandiseNotAsX81f2f416af: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostIssuingDisputesDisputeRequestBodyEvidenceMerchandiseNotAsX81f2f416af")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(Int.self) { return .intValue(value) }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .intValue(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public enum PostIssuingDisputesRequestBodyEvidenceCanceledVariant0ExpectedAt {
    case intValue(Int)
    case stringValue(String)
}

extension PostIssuingDisputesRequestBodyEvidenceCanceledVariant0ExpectedAt: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostIssuingDisputesRequestBodyEvidenceCanceledVariant0ExpectedAt")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(Int.self) { return .intValue(value) }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .intValue(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public enum PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0ReturnedAt {
    case intValue(Int)
    case stringValue(String)
}

extension PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0ReturnedAt: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0ReturnedAt")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(Int.self) { return .intValue(value) }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .intValue(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

/// Evidence provided for the dispute.
public struct PostIssuingDisputesRequestBodyEvidence: Codable {
    public var canceled: PostIssuingDisputesRequestBodyEvidenceCanceled?
    public var duplicate: PostIssuingDisputesRequestBodyEvidenceDuplicate?
    public var fraudulent: PostIssuingDisputesRequestBodyEvidenceFraudulent?
    public var merchandiseNotAsDescribed: PostIssuingDisputesRequestBodyEvidenceMerchandiseNotAsDescribed?
    public var noValidAuthorization: PostIssuingDisputesRequestBodyEvidenceNoValidAuthorization?
    public var notReceived: PostIssuingDisputesRequestBodyEvidenceNotReceived?
    public var other: PostIssuingDisputesRequestBodyEvidenceOther?
    public var reason: PostIssuingDisputesRequestBodyEvidenceReason?
    public var serviceNotAsDescribed: PostIssuingDisputesRequestBodyEvidenceServiceNotAsDescribed?

    enum CodingKeys: String, CodingKey {
        case canceled
        case duplicate
        case fraudulent
        case merchandiseNotAsDescribed = "merchandise_not_as_described"
        case noValidAuthorization = "no_valid_authorization"
        case notReceived = "not_received"
        case other
        case reason
        case serviceNotAsDescribed = "service_not_as_described"
    }

    init() {
        (self.canceled, self.duplicate, self.fraudulent, self.merchandiseNotAsDescribed, self.noValidAuthorization) = (nil, nil, nil, nil, nil)
        (self.notReceived, self.other, self.reason, self.serviceNotAsDescribed) = (nil, nil, nil, nil)
    }
}

extension PostIssuingDisputesRequestBodyEvidence {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.canceled = try container.sdkDecodeIfPresent(.canceled)
        self.duplicate = try container.sdkDecodeIfPresent(.duplicate)
        self.fraudulent = try container.sdkDecodeIfPresent(.fraudulent)
        self.merchandiseNotAsDescribed = try container.sdkDecodeIfPresent(.merchandiseNotAsDescribed)
        self.noValidAuthorization = try container.sdkDecodeIfPresent(.noValidAuthorization)
        self.notReceived = try container.sdkDecodeIfPresent(.notReceived)
        self.other = try container.sdkDecodeIfPresent(.other)
        self.reason = try container.sdkDecodeIfPresent(.reason)
        self.serviceNotAsDescribed = try container.sdkDecodeIfPresent(.serviceNotAsDescribed)
    }
}

extension PostIssuingDisputesRequestBodyEvidence {
    public init(canceled: PostIssuingDisputesRequestBodyEvidenceCanceled? = nil, duplicate: PostIssuingDisputesRequestBodyEvidenceDuplicate? = nil, fraudulent: PostIssuingDisputesRequestBodyEvidenceFraudulent? = nil, merchandiseNotAsDescribed: PostIssuingDisputesRequestBodyEvidenceMerchandiseNotAsDescribed? = nil, noValidAuthorization: PostIssuingDisputesRequestBodyEvidenceNoValidAuthorization? = nil, notReceived: PostIssuingDisputesRequestBodyEvidenceNotReceived? = nil, other: PostIssuingDisputesRequestBodyEvidenceOther? = nil, reason: PostIssuingDisputesRequestBodyEvidenceReason? = nil, serviceNotAsDescribed: PostIssuingDisputesRequestBodyEvidenceServiceNotAsDescribed? = nil) {
        self.init()
        (self.canceled, self.duplicate) = (canceled, duplicate)
        (self.fraudulent, self.merchandiseNotAsDescribed) = (fraudulent, merchandiseNotAsDescribed)
        (self.noValidAuthorization, self.notReceived) = (noValidAuthorization, notReceived)
        (self.other, self.reason) = (other, reason)
        self.serviceNotAsDescribed = serviceNotAsDescribed
    }
}

public enum PostIssuingDisputesDisputeRequestBodyEvidenceMerchandiseNotAsDescribed {
    case postIssuingDisputesDisputeRequestBodyEvidenceMerchandiseNotAsX7066c328b0(
        PostIssuingDisputesDisputeRequestBodyEvidenceMerchandiseNotAsX7066c328b0
    )
    case stringValue(String)
}

extension PostIssuingDisputesDisputeRequestBodyEvidenceMerchandiseNotAsDescribed: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostIssuingDisputesDisputeRequestBodyEvidenceMerchandiseNotAsDescribed")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PostIssuingDisputesDisputeRequestBodyEvidenceMerchandiseNotAsX7066c328b0.self
        ) {
            return             .postIssuingDisputesDisputeRequestBodyEvidenceMerchandiseNotAsX7066c328b0(value)
        }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postIssuingDisputesDisputeRequestBodyEvidenceMerchandiseNotAsX7066c328b0(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public struct PostIssuingDisputesDisputeRequestBodyEvidenceFraudulentVariant0: Codable {
    public var additionalDocumentation: String?
    public var explanation: PostIssuingDisputesDisputeRequestBodyEvidenceFraudulentVarianX10b0f220b4?

    enum CodingKeys: String, CodingKey {
        case additionalDocumentation = "additional_documentation"
        case explanation
    }

    init() {
        (self.additionalDocumentation, self.explanation) = (nil, nil)
    }
}

extension PostIssuingDisputesDisputeRequestBodyEvidenceFraudulentVariant0 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.additionalDocumentation = try container.sdkDecodeIfPresent(.additionalDocumentation)
        self.explanation = try container.sdkDecodeIfPresent(.explanation)
    }
}

extension PostIssuingDisputesDisputeRequestBodyEvidenceFraudulentVariant0 {
    public init(additionalDocumentation: String? = nil, explanation: PostIssuingDisputesDisputeRequestBodyEvidenceFraudulentVarianX10b0f220b4? = nil) {
        self.init()
        (self.additionalDocumentation, self.explanation) = (additionalDocumentation, explanation)
    }
}

public enum PostIssuingDisputesRequestBodyEvidenceOther {
    case postIssuingDisputesRequestBodyEvidenceOtherVariant0(PostIssuingDisputesRequestBodyEvidenceOtherVariant0)
    case stringValue(String)
}

extension PostIssuingDisputesRequestBodyEvidenceOther: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostIssuingDisputesRequestBodyEvidenceOther")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PostIssuingDisputesRequestBodyEvidenceOtherVariant0.self
        ) {
            return             .postIssuingDisputesRequestBodyEvidenceOtherVariant0(value)
        }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postIssuingDisputesRequestBodyEvidenceOtherVariant0(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public enum PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0Xb83566f6a8 {
    case boolValue(Bool)
    case stringValue(String)
}

extension PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0Xb83566f6a8: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0Xb83566f6a8")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(Bool.self) { return .boolValue(value) }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .boolValue(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public struct PostIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescX5bc66057ad: Codable {
    public var additionalDocumentation: String?
    public var canceledAt: PostIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescX63dff78f0e?
    public var cancellationReason: PostIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescX9de991455b?
    public var explanation: PostIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescX3fc872a9af?
    public var receivedAt: PostIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescXfc2f092be9?

    enum CodingKeys: String, CodingKey {
        case additionalDocumentation = "additional_documentation"
        case canceledAt = "canceled_at"
        case cancellationReason = "cancellation_reason"
        case explanation
        case receivedAt = "received_at"
    }

    init() {
        (self.additionalDocumentation, self.canceledAt, self.cancellationReason, self.explanation, self.receivedAt) = (nil, nil, nil, nil, nil)
    }
}

extension PostIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescX5bc66057ad {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.additionalDocumentation = try container.sdkDecodeIfPresent(.additionalDocumentation)
        self.canceledAt = try container.sdkDecodeIfPresent(.canceledAt)
        self.cancellationReason = try container.sdkDecodeIfPresent(.cancellationReason)
        self.explanation = try container.sdkDecodeIfPresent(.explanation)
        self.receivedAt = try container.sdkDecodeIfPresent(.receivedAt)
    }
}

extension PostIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescX5bc66057ad {
    public init(additionalDocumentation: String? = nil, canceledAt: PostIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescX63dff78f0e? = nil, cancellationReason: PostIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescX9de991455b? = nil, explanation: PostIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescX3fc872a9af? = nil, receivedAt: PostIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescXfc2f092be9? = nil) {
        self.init()
        (self.additionalDocumentation, self.canceledAt) = (additionalDocumentation, canceledAt)
        (self.cancellationReason, self.explanation) = (cancellationReason, explanation)
        self.receivedAt = receivedAt
    }
}

public enum PostIssuingDisputesDisputeRequestBodyEvidenceDuplicateVariantX323e95696e {
    case stringValue(String)
    case stringValue1(String)
}

extension PostIssuingDisputesDisputeRequestBodyEvidenceDuplicateVariantX323e95696e: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostIssuingDisputesDisputeRequestBodyEvidenceDuplicateVariantX323e95696e")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        if let value = try? container.decode(String.self) { return .stringValue1(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .stringValue1(value): try container.encode(value); return true
        }
    }

}

public enum PostIssuingDisputesRequestBodyEvidenceNoValidAuthorizationVarXb6cbed05dc {
    case stringValue(String)
    case stringValue1(String)
}

extension PostIssuingDisputesRequestBodyEvidenceNoValidAuthorizationVarXb6cbed05dc: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostIssuingDisputesRequestBodyEvidenceNoValidAuthorizationVarXb6cbed05dc")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        if let value = try? container.decode(String.self) { return .stringValue1(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .stringValue1(value): try container.encode(value); return true
        }
    }

}

public enum PostIssuingDisputesRequestBodyEvidenceNotReceivedVariant0ExpectedAt {
    case intValue(Int)
    case stringValue(String)
}

extension PostIssuingDisputesRequestBodyEvidenceNotReceivedVariant0ExpectedAt: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostIssuingDisputesRequestBodyEvidenceNotReceivedVariant0ExpectedAt")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(Int.self) { return .intValue(value) }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .intValue(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public enum PostIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescribed {
    case postIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescX5bc66057ad(
        PostIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescX5bc66057ad
    )
    case stringValue(String)
}

extension PostIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescribed: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescribed")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PostIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescX5bc66057ad.self
        ) {
            return             .postIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescX5bc66057ad(value)
        }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postIssuingDisputesDisputeRequestBodyEvidenceServiceNotAsDescX5bc66057ad(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public enum PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0CanceledAt {
    case intValue(Int)
    case stringValue(String)
}

extension PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0CanceledAt: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostIssuingDisputesDisputeRequestBodyEvidenceCanceledVariant0CanceledAt")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(Int.self) { return .intValue(value) }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .intValue(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public enum PostIssuingDisputesRequestBodyEvidenceCanceledVariant0CanceledAt {
    case intValue(Int)
    case stringValue(String)
}
