// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif

// Canonical v1TaxRegistrations operation model declarations
public extension PostTaxRegistrationsRequestBodyCountryOptionsEs {
    public init(type: PostTaxRegistrationsRequestBodyCountryOptionsEsType, igic: PostTaxRegistrationsRequestBodyCountryOptionsEsIgic? = nil, standard: PostTaxRegistrationsRequestBodyCountryOptionsEsStandard? = nil) {
        (self.type, self.igic) = (type, igic)
        self.standard = standard
    }
}

public struct PostTaxRegistrationsRequestBodyCountryOptionsBeIgic: Codable {
    public var placeOfSupplyScheme: PostTaxRegistrationsRequestBodyCountryOptionsBeIgicPlaceOfSupplyScheme

    enum CodingKeys: String, CodingKey {
        case placeOfSupplyScheme = "place_of_supply_scheme"
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsBeIgic {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.placeOfSupplyScheme) else {
            throw SdkValidationError(field: "place_of_supply_scheme", code: "required", message: "Validation failed for 'place_of_supply_scheme': value is required")
        }
        self.placeOfSupplyScheme = try container.sdkDecodeRequired(.placeOfSupplyScheme)
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsBeIgic {
    public init(placeOfSupplyScheme: PostTaxRegistrationsRequestBodyCountryOptionsBeIgicPlaceOfSupplyScheme) {
        self.placeOfSupplyScheme = placeOfSupplyScheme
    }
}

public struct PostTaxRegistrationsRequestBodyCountryOptionsZw: Codable {
    public var type: PostTaxRegistrationsRequestBodyCountryOptionsZwType
    /// standard
    public var standard: PostTaxRegistrationsRequestBodyCountryOptionsZwStandard?

    enum CodingKeys: String, CodingKey {
        case type
        case standard
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsZw {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.type) else {
            throw SdkValidationError(field: "type", code: "required", message: "Validation failed for 'type': value is required")
        }
        self.type = try container.sdkDecodeRequired(.type)
        self.standard = try container.sdkDecodeIfPresent(.standard)
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsZw {
    public init(type: PostTaxRegistrationsRequestBodyCountryOptionsZwType, standard: PostTaxRegistrationsRequestBodyCountryOptionsZwStandard? = nil) {
        (self.type, self.standard) = (type, standard)
    }
}

public struct PostTaxRegistrationsRequestBodyCountryOptionsBbStandard: Codable {
    public var placeOfSupplyScheme: PostTaxRegistrationsRequestBodyCountryOptionsBbStandardPlaceOX805f09d28a?

    enum CodingKeys: String, CodingKey {
        case placeOfSupplyScheme = "place_of_supply_scheme"
    }

    init() {
        self.placeOfSupplyScheme = nil
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsBbStandard {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.placeOfSupplyScheme = try container.sdkDecodeIfPresent(.placeOfSupplyScheme)
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsBbStandard {
    public init(placeOfSupplyScheme: PostTaxRegistrationsRequestBodyCountryOptionsBbStandardPlaceOX805f09d28a? = nil) {
        self.init()
        self.placeOfSupplyScheme = placeOfSupplyScheme
    }
}

public struct PostTaxRegistrationsRequestBodyCountryOptionsEc: Codable {
    public var type: PostTaxRegistrationsRequestBodyCountryOptionsEcType

    enum CodingKeys: String, CodingKey {
        case type
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsEc {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.type) else {
            throw SdkValidationError(field: "type", code: "required", message: "Validation failed for 'type': value is required")
        }
        self.type = try container.sdkDecodeRequired(.type)
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsEc {
    public init(type: PostTaxRegistrationsRequestBodyCountryOptionsEcType) {
        self.type = type
    }
}

public struct PostTaxRegistrationsRequestBodyCountryOptionsRu: Codable {
    public var type: PostTaxRegistrationsRequestBodyCountryOptionsRuType

    enum CodingKeys: String, CodingKey {
        case type
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsRu {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.type) else {
            throw SdkValidationError(field: "type", code: "required", message: "Validation failed for 'type': value is required")
        }
        self.type = try container.sdkDecodeRequired(.type)
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsRu {
    public init(type: PostTaxRegistrationsRequestBodyCountryOptionsRuType) {
        self.type = type
    }
}

public struct PostTaxRegistrationsRequestBodyCountryOptionsBs: Codable {
    public var type: PostTaxRegistrationsRequestBodyCountryOptionsBsType
    /// standard
    public var standard: PostTaxRegistrationsRequestBodyCountryOptionsBsStandard?

    enum CodingKeys: String, CodingKey {
        case type
        case standard
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsBs {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.type) else {
            throw SdkValidationError(field: "type", code: "required", message: "Validation failed for 'type': value is required")
        }
        self.type = try container.sdkDecodeRequired(.type)
        self.standard = try container.sdkDecodeIfPresent(.standard)
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsBs {
    public init(type: PostTaxRegistrationsRequestBodyCountryOptionsBsType, standard: PostTaxRegistrationsRequestBodyCountryOptionsBsStandard? = nil) {
        (self.type, self.standard) = (type, standard)
    }
}

public struct PostTaxRegistrationsRequestBodyCountryOptionsBh: Codable {
    public var type: PostTaxRegistrationsRequestBodyCountryOptionsBhType
    /// standard
    public var standard: PostTaxRegistrationsRequestBodyCountryOptionsBhStandard?

    enum CodingKeys: String, CodingKey {
        case type
        case standard
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsBh {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.type) else {
            throw SdkValidationError(field: "type", code: "required", message: "Validation failed for 'type': value is required")
        }
        self.type = try container.sdkDecodeRequired(.type)
        self.standard = try container.sdkDecodeIfPresent(.standard)
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsBh {
    public init(type: PostTaxRegistrationsRequestBodyCountryOptionsBhType, standard: PostTaxRegistrationsRequestBodyCountryOptionsBhStandard? = nil) {
        (self.type, self.standard) = (type, standard)
    }
}

public struct PostTaxRegistrationsRequestBodyCountryOptionsAlStandard: Codable {
    public var placeOfSupplyScheme: PostTaxRegistrationsRequestBodyCountryOptionsAlStandardPlaceOXb5478cb6c4?

    enum CodingKeys: String, CodingKey {
        case placeOfSupplyScheme = "place_of_supply_scheme"
    }

    init() {
        self.placeOfSupplyScheme = nil
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsAlStandard {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.placeOfSupplyScheme = try container.sdkDecodeIfPresent(.placeOfSupplyScheme)
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsAlStandard {
    public init(placeOfSupplyScheme: PostTaxRegistrationsRequestBodyCountryOptionsAlStandardPlaceOXb5478cb6c4? = nil) {
        self.init()
        self.placeOfSupplyScheme = placeOfSupplyScheme
    }
}

public struct PostTaxRegistrationsRequestBodyCountryOptionsChStandard: Codable {
    public var placeOfSupplyScheme: PostTaxRegistrationsRequestBodyCountryOptionsChStandardPlaceOX6bdccede61?

    enum CodingKeys: String, CodingKey {
        case placeOfSupplyScheme = "place_of_supply_scheme"
    }

    init() {
        self.placeOfSupplyScheme = nil
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsChStandard {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.placeOfSupplyScheme = try container.sdkDecodeIfPresent(.placeOfSupplyScheme)
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsChStandard {
    public init(placeOfSupplyScheme: PostTaxRegistrationsRequestBodyCountryOptionsChStandardPlaceOX6bdccede61? = nil) {
        self.init()
        self.placeOfSupplyScheme = placeOfSupplyScheme
    }
}

public struct PostTaxRegistrationsRequestBodyCountryOptionsZwStandard: Codable {
    public var placeOfSupplyScheme: PostTaxRegistrationsRequestBodyCountryOptionsZwStandardPlaceOX7f3d4dde41?

    enum CodingKeys: String, CodingKey {
        case placeOfSupplyScheme = "place_of_supply_scheme"
    }

    init() {
        self.placeOfSupplyScheme = nil
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsZwStandard {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.placeOfSupplyScheme = try container.sdkDecodeIfPresent(.placeOfSupplyScheme)
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsZwStandard {
    public init(placeOfSupplyScheme: PostTaxRegistrationsRequestBodyCountryOptionsZwStandardPlaceOX7f3d4dde41? = nil) {
        self.init()
        self.placeOfSupplyScheme = placeOfSupplyScheme
    }
}

public struct PostTaxRegistrationsRequestBodyCountryOptionsZa: Codable {
    public var type: PostTaxRegistrationsRequestBodyCountryOptionsZaType
    /// standard
    public var standard: PostTaxRegistrationsRequestBodyCountryOptionsZaStandard?

    enum CodingKeys: String, CodingKey {
        case type
        case standard
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsZa {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.type) else {
            throw SdkValidationError(field: "type", code: "required", message: "Validation failed for 'type': value is required")
        }
        self.type = try container.sdkDecodeRequired(.type)
        self.standard = try container.sdkDecodeIfPresent(.standard)
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsZa {
    public init(type: PostTaxRegistrationsRequestBodyCountryOptionsZaType, standard: PostTaxRegistrationsRequestBodyCountryOptionsZaStandard? = nil) {
        (self.type, self.standard) = (type, standard)
    }
}

public struct PostTaxRegistrationsRequestBodyCountryOptionsLt: Codable {
    public var type: PostTaxRegistrationsRequestBodyCountryOptionsLtType
    /// igic
    public var igic: PostTaxRegistrationsRequestBodyCountryOptionsLtIgic?
    /// standard
    public var standard: PostTaxRegistrationsRequestBodyCountryOptionsLtStandard?

    enum CodingKeys: String, CodingKey {
        case type
        case igic
        case standard
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsLt {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.type) else {
            throw SdkValidationError(field: "type", code: "required", message: "Validation failed for 'type': value is required")
        }
        self.type = try container.sdkDecodeRequired(.type)
        self.igic = try container.sdkDecodeIfPresent(.igic)
        self.standard = try container.sdkDecodeIfPresent(.standard)
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsLt {
    public init(type: PostTaxRegistrationsRequestBodyCountryOptionsLtType, igic: PostTaxRegistrationsRequestBodyCountryOptionsLtIgic? = nil, standard: PostTaxRegistrationsRequestBodyCountryOptionsLtStandard? = nil) {
        (self.type, self.igic) = (type, igic)
        self.standard = standard
    }
}

public struct PostTaxRegistrationsRequestBodyCountryOptionsSeIgic: Codable {
    public var placeOfSupplyScheme: PostTaxRegistrationsRequestBodyCountryOptionsSeIgicPlaceOfSupplyScheme

    enum CodingKeys: String, CodingKey {
        case placeOfSupplyScheme = "place_of_supply_scheme"
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsSeIgic {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.placeOfSupplyScheme) else {
            throw SdkValidationError(field: "place_of_supply_scheme", code: "required", message: "Validation failed for 'place_of_supply_scheme': value is required")
        }
        self.placeOfSupplyScheme = try container.sdkDecodeRequired(.placeOfSupplyScheme)
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsSeIgic {
    public init(placeOfSupplyScheme: PostTaxRegistrationsRequestBodyCountryOptionsSeIgicPlaceOfSupplyScheme) {
        self.placeOfSupplyScheme = placeOfSupplyScheme
    }
}

public struct PostTaxRegistrationsRequestBodyCountryOptionsKh: Codable {
    public var type: PostTaxRegistrationsRequestBodyCountryOptionsKhType

    enum CodingKeys: String, CodingKey {
        case type
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsKh {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.type) else {
            throw SdkValidationError(field: "type", code: "required", message: "Validation failed for 'type': value is required")
        }
        self.type = try container.sdkDecodeRequired(.type)
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsKh {
    public init(type: PostTaxRegistrationsRequestBodyCountryOptionsKhType) {
        self.type = type
    }
}

public struct PostTaxRegistrationsRequestBodyCountryOptionsPt: Codable {
    public var type: PostTaxRegistrationsRequestBodyCountryOptionsPtType
    /// igic
    public var igic: PostTaxRegistrationsRequestBodyCountryOptionsPtIgic?
    /// standard
    public var standard: PostTaxRegistrationsRequestBodyCountryOptionsPtStandard?

    enum CodingKeys: String, CodingKey {
        case type
        case igic
        case standard
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsPt {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.type) else {
            throw SdkValidationError(field: "type", code: "required", message: "Validation failed for 'type': value is required")
        }
        self.type = try container.sdkDecodeRequired(.type)
        self.igic = try container.sdkDecodeIfPresent(.igic)
        self.standard = try container.sdkDecodeIfPresent(.standard)
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsPt {
    public init(type: PostTaxRegistrationsRequestBodyCountryOptionsPtType, igic: PostTaxRegistrationsRequestBodyCountryOptionsPtIgic? = nil, standard: PostTaxRegistrationsRequestBodyCountryOptionsPtStandard? = nil) {
        (self.type, self.igic) = (type, igic)
        self.standard = standard
    }
}

public struct PostTaxRegistrationsRequestBodyCountryOptionsGrStandard: Codable {
    public var placeOfSupplyScheme: PostTaxRegistrationsRequestBodyCountryOptionsGrStandardPlaceOXac0aede6ac

    enum CodingKeys: String, CodingKey {
        case placeOfSupplyScheme = "place_of_supply_scheme"
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsGrStandard {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.placeOfSupplyScheme) else {
            throw SdkValidationError(field: "place_of_supply_scheme", code: "required", message: "Validation failed for 'place_of_supply_scheme': value is required")
        }
        self.placeOfSupplyScheme = try container.sdkDecodeRequired(.placeOfSupplyScheme)
    }
}

public extension PostTaxRegistrationsRequestBodyCountryOptionsGrStandard {
    public init(placeOfSupplyScheme: PostTaxRegistrationsRequestBodyCountryOptionsGrStandardPlaceOXac0aede6ac) {
        self.placeOfSupplyScheme = placeOfSupplyScheme
    }
}
