// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif

// Canonical v1CheckoutSessions operation model declarations
public extension PostCheckoutSessionsRequestBodySubscriptionDataTrialSettings {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.endBehavior) else {
            throw SdkValidationError(field: "end_behavior", code: "required", message: "Validation failed for 'end_behavior': value is required")
        }
        self.endBehavior = try container.sdkDecodeRequired(.endBehavior)
    }
}

public extension PostCheckoutSessionsRequestBodySubscriptionDataTrialSettings {
    public init(endBehavior: PostCheckoutSessionsRequestBodySubscriptionDataTrialSettingsEndBehavior) {
        self.endBehavior = endBehavior
    }
}

/// Settings for Managed Payments for this Checkout Session and resulting PaymentIntents, Invoices, and
/// Subscriptions.
public struct PostCheckoutSessionsRequestBodyManagedPayments: Codable {
    public var enabled: Bool?

    enum CodingKeys: String, CodingKey {
        case enabled
    }

    init() {
        self.enabled = nil
    }
}

public extension PostCheckoutSessionsRequestBodyManagedPayments {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.enabled = try container.sdkDecodeIfPresent(.enabled)
    }
}

public extension PostCheckoutSessionsRequestBodyManagedPayments {
    public init(enabled: Bool? = nil) {
        self.init()
        self.enabled = enabled
    }
}

public struct PostCheckoutSessionsRequestBodyPaymentMethodOptionsFpx: Codable {
    public var setupFutureUsage: PostCheckoutSessionsRequestBodyPaymentMethodOptionsFpxSetupFutureUsage?

    enum CodingKeys: String, CodingKey {
        case setupFutureUsage = "setup_future_usage"
    }

    init() {
        self.setupFutureUsage = nil
    }
}

public extension PostCheckoutSessionsRequestBodyPaymentMethodOptionsFpx {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.setupFutureUsage = try container.sdkDecodeIfPresent(.setupFutureUsage)
    }
}

public extension PostCheckoutSessionsRequestBodyPaymentMethodOptionsFpx {
    public init(setupFutureUsage: PostCheckoutSessionsRequestBodyPaymentMethodOptionsFpxSetupFutureUsage? = nil) {
        self.init()
        self.setupFutureUsage = setupFutureUsage
    }
}

public struct PostCheckoutSessionsRequestBodyOptionalItemsItemAdjustableQuantity: Codable {
    public var enabled: Bool
    public var maximum: Int?
    public var minimum: Int?

    enum CodingKeys: String, CodingKey {
        case enabled
        case maximum
        case minimum
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostCheckoutSessionsRequestBodyOptionalItemsItemAdjustableQuantity {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.enabled) else {
            throw SdkValidationError(field: "enabled", code: "required", message: "Validation failed for 'enabled': value is required")
        }
        self.enabled = try container.sdkDecodeRequired(.enabled)
        self.maximum = try container.sdkDecodeIfPresent(.maximum)
        self.minimum = try container.sdkDecodeIfPresent(.minimum)
    }
}

public extension PostCheckoutSessionsRequestBodyOptionalItemsItemAdjustableQuantity {
    public init(enabled: Bool, maximum: Int? = nil, minimum: Int? = nil) {
        (self.enabled, self.maximum) = (enabled, maximum)
        self.minimum = minimum
    }
}

public struct PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0X130941da40: Codable {
    public var displayName: String
    /// delivery_estimate
    public var deliveryEstimate: PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0X22021e911f?
    /// fixed_amount
    public var fixedAmount: PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0X8d5cdd1e7e?
    public var metadata: [String: String]?
    public var taxBehavior: PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0X757448cdd1?
    public var taxCode: String?
    public var type: PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0Xca99a12f27?

    enum CodingKeys: String, CodingKey {
        case displayName = "display_name"
        case deliveryEstimate = "delivery_estimate"
        case fixedAmount = "fixed_amount"
        case metadata
        case taxBehavior = "tax_behavior"
        case taxCode = "tax_code"
        case type
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0X130941da40 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.displayName) else {
            throw SdkValidationError(field: "display_name", code: "required", message: "Validation failed for 'display_name': value is required")
        }
        self.displayName = try container.sdkDecodeRequired(.displayName)
        self.deliveryEstimate = try container.sdkDecodeIfPresent(.deliveryEstimate)
        self.fixedAmount = try container.sdkDecodeIfPresent(.fixedAmount)
        self.metadata = try container.sdkDecodeIfPresent(.metadata)
        self.taxBehavior = try container.sdkDecodeIfPresent(.taxBehavior)
        self.taxCode = try container.sdkDecodeIfPresent(.taxCode)
        self.type = try container.sdkDecodeIfPresent(.type)
            try validateLength("display_name", self.displayName, min: nil, max: 100)
    }
}

public extension PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0X130941da40 {
    public init(displayName: String, deliveryEstimate: PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0X22021e911f? = nil, fixedAmount: PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0X8d5cdd1e7e? = nil, metadata: [String: String]? = nil, taxBehavior: PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0X757448cdd1? = nil, taxCode: String? = nil, type: PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0Xca99a12f27? = nil) throws {
        (self.displayName, self.deliveryEstimate) = (displayName, deliveryEstimate)
        (self.fixedAmount, self.metadata) = (fixedAmount, metadata)
        (self.taxBehavior, self.taxCode) = (taxBehavior, taxCode)
        self.type = type
            try validateLength("display_name", self.displayName, min: nil, max: 100)
    }
}

/// A subset of parameters to be passed to PaymentIntent creation for Checkout Sessions in `payment` mode.
public struct PostCheckoutSessionsRequestBodyPaymentIntentData: Codable {
    public var applicationFeeAmount: Int?
    public var captureMethod: PostCheckoutSessionsRequestBodyPaymentIntentDataCaptureMethod?
    public var description: String?
    public var metadata: [String: String]?
    public var onBehalfOf: String?
    public var receiptEmail: String?
    public var setupFutureUsage: PostCheckoutSessionsRequestBodyPaymentIntentDataSetupFutureUsage?
    /// shipping
    public var shipping: PostCheckoutSessionsRequestBodyPaymentIntentDataShipping?
    public var statementDescriptor: String?
    public var statementDescriptorSuffix: String?
    /// transfer_data_params
    public var transferData: PostCheckoutSessionsRequestBodyPaymentIntentDataTransferData?
    public var transferGroup: String?

    enum CodingKeys: String, CodingKey {
        case applicationFeeAmount = "application_fee_amount"
        case captureMethod = "capture_method"
        case description
        case metadata
        case onBehalfOf = "on_behalf_of"
        case receiptEmail = "receipt_email"
        case setupFutureUsage = "setup_future_usage"
        case shipping
        case statementDescriptor = "statement_descriptor"
        case statementDescriptorSuffix = "statement_descriptor_suffix"
        case transferData = "transfer_data"
        case transferGroup = "transfer_group"
    }

    init() {
        (self.applicationFeeAmount, self.captureMethod, self.description, self.metadata, self.onBehalfOf) = (nil, nil, nil, nil, nil)
        (self.receiptEmail, self.setupFutureUsage, self.shipping, self.statementDescriptor, self.statementDescriptorSuffix) = (nil, nil, nil, nil, nil)
        (self.transferData, self.transferGroup) = (nil, nil)
    }
}

public extension PostCheckoutSessionsRequestBodyPaymentIntentData {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.applicationFeeAmount = try container.sdkDecodeIfPresent(.applicationFeeAmount)
        self.captureMethod = try container.sdkDecodeIfPresent(.captureMethod)
        self.description = try container.sdkDecodeIfPresent(.description)
        self.metadata = try container.sdkDecodeIfPresent(.metadata)
        self.onBehalfOf = try container.sdkDecodeIfPresent(.onBehalfOf)
        self.receiptEmail = try container.sdkDecodeIfPresent(.receiptEmail)
        self.setupFutureUsage = try container.sdkDecodeIfPresent(.setupFutureUsage)
        self.shipping = try container.sdkDecodeIfPresent(.shipping)
        self.statementDescriptor = try container.sdkDecodeIfPresent(.statementDescriptor)
        self.statementDescriptorSuffix = try container.sdkDecodeIfPresent(.statementDescriptorSuffix)
        self.transferData = try container.sdkDecodeIfPresent(.transferData)
        self.transferGroup = try container.sdkDecodeIfPresent(.transferGroup)
        if let value = self.description {
            try validateLength("description", value, min: nil, max: 1000)
        }
        if let value = self.statementDescriptor {
            try validateLength("statement_descriptor", value, min: nil, max: 22)
        }
        if let value = self.statementDescriptorSuffix {
            try validateLength("statement_descriptor_suffix", value, min: nil, max: 22)
        }
    }
}

public extension PostCheckoutSessionsRequestBodyPaymentIntentData {
    public init(applicationFeeAmount: Int? = nil, captureMethod: PostCheckoutSessionsRequestBodyPaymentIntentDataCaptureMethod? = nil, description: String? = nil, metadata: [String: String]? = nil, onBehalfOf: String? = nil, receiptEmail: String? = nil, setupFutureUsage: PostCheckoutSessionsRequestBodyPaymentIntentDataSetupFutureUsage? = nil, shipping: PostCheckoutSessionsRequestBodyPaymentIntentDataShipping? = nil, statementDescriptor: String? = nil, statementDescriptorSuffix: String? = nil, transferData: PostCheckoutSessionsRequestBodyPaymentIntentDataTransferData? = nil, transferGroup: String? = nil) throws {
        self.init()
        (self.applicationFeeAmount, self.captureMethod) = (applicationFeeAmount, captureMethod)
        (self.description, self.metadata) = (description, metadata)
        (self.onBehalfOf, self.receiptEmail) = (onBehalfOf, receiptEmail)
        (self.setupFutureUsage, self.shipping) = (setupFutureUsage, shipping)
        self.statementDescriptor = statementDescriptor
        (self.statementDescriptorSuffix, self.transferData) = (statementDescriptorSuffix, transferData)
        self.transferGroup = transferGroup
        if let value = self.description {
            try validateLength("description", value, min: nil, max: 1000)
        }
        if let value = self.statementDescriptor {
            try validateLength("statement_descriptor", value, min: nil, max: 22)
        }
        if let value = self.statementDescriptorSuffix {
            try validateLength("statement_descriptor_suffix", value, min: nil, max: 22)
        }
    }
}

public struct PostCheckoutSessionsRequestBodyCustomTextSubmitVariant0: Codable {
    public var message: String

    enum CodingKeys: String, CodingKey {
        case message
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostCheckoutSessionsRequestBodyCustomTextSubmitVariant0 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.message) else {
            throw SdkValidationError(field: "message", code: "required", message: "Validation failed for 'message': value is required")
        }
        self.message = try container.sdkDecodeRequired(.message)
            try validateLength("message", self.message, min: nil, max: 1200)
    }
}

public extension PostCheckoutSessionsRequestBodyCustomTextSubmitVariant0 {
    public init(message: String) throws {
        self.message = message
            try validateLength("message", self.message, min: nil, max: 1200)
    }
}

public struct PostCheckoutSessionsRequestBodyCustomFieldsItemNumeric: Codable {
    public var defaultValue: String?
    public var maximumLength: Int?
    public var minimumLength: Int?

    enum CodingKeys: String, CodingKey {
        case defaultValue = "default_value"
        case maximumLength = "maximum_length"
        case minimumLength = "minimum_length"
    }

    init() {
        (self.defaultValue, self.maximumLength, self.minimumLength) = (nil, nil, nil)
    }
}

public extension PostCheckoutSessionsRequestBodyCustomFieldsItemNumeric {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.defaultValue = try container.sdkDecodeIfPresent(.defaultValue)
        self.maximumLength = try container.sdkDecodeIfPresent(.maximumLength)
        self.minimumLength = try container.sdkDecodeIfPresent(.minimumLength)
        if let value = self.defaultValue {
            try validateLength("default_value", value, min: nil, max: 255)
        }
    }
}

public extension PostCheckoutSessionsRequestBodyCustomFieldsItemNumeric {
    public init(defaultValue: String? = nil, maximumLength: Int? = nil, minimumLength: Int? = nil) throws {
        self.init()
        (self.defaultValue, self.maximumLength) = (defaultValue, maximumLength)
        self.minimumLength = minimumLength
        if let value = self.defaultValue {
            try validateLength("default_value", value, min: nil, max: 255)
        }
    }
}

public struct PostCheckoutSessionsRequestBodySubscriptionDataInvoiceSettings: Codable {
    /// param
    public var issuer: PostCheckoutSessionsRequestBodySubscriptionDataInvoiceSettingsIssuer?

    enum CodingKeys: String, CodingKey {
        case issuer
    }

    init() {
        self.issuer = nil
    }
}

public extension PostCheckoutSessionsRequestBodySubscriptionDataInvoiceSettings {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.issuer = try container.sdkDecodeIfPresent(.issuer)
    }
}

public extension PostCheckoutSessionsRequestBodySubscriptionDataInvoiceSettings {
    public init(issuer: PostCheckoutSessionsRequestBodySubscriptionDataInvoiceSettingsIssuer? = nil) {
        self.init()
        self.issuer = issuer
    }
}

public struct PostCheckoutSessionsRequestBodyPaymentMethodOptionsBoleto: Codable {
    public var expiresAfterDays: Int?
    public var setupFutureUsage: PostCheckoutSessionsRequestBodyPaymentMethodOptionsBoletoSetuXeb111b7ecc?

    enum CodingKeys: String, CodingKey {
        case expiresAfterDays = "expires_after_days"
        case setupFutureUsage = "setup_future_usage"
    }

    init() {
        (self.expiresAfterDays, self.setupFutureUsage) = (nil, nil)
    }
}

public extension PostCheckoutSessionsRequestBodyPaymentMethodOptionsBoleto {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.expiresAfterDays = try container.sdkDecodeIfPresent(.expiresAfterDays)
        self.setupFutureUsage = try container.sdkDecodeIfPresent(.setupFutureUsage)
    }
}

public extension PostCheckoutSessionsRequestBodyPaymentMethodOptionsBoleto {
    public init(expiresAfterDays: Int? = nil, setupFutureUsage: PostCheckoutSessionsRequestBodyPaymentMethodOptionsBoletoSetuXeb111b7ecc? = nil) {
        self.init()
        (self.expiresAfterDays, self.setupFutureUsage) = (expiresAfterDays, setupFutureUsage)
    }
}

public enum PostCheckoutSessionsRequestBodyCustomTextSubmit {
    case postCheckoutSessionsRequestBodyCustomTextSubmitVariant0(PostCheckoutSessionsRequestBodyCustomTextSubmitVariant0)
    case stringValue(String)
}

extension PostCheckoutSessionsRequestBodyCustomTextSubmit: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostCheckoutSessionsRequestBodyCustomTextSubmit")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PostCheckoutSessionsRequestBodyCustomTextSubmitVariant0.self
        ) {
            return             .postCheckoutSessionsRequestBodyCustomTextSubmitVariant0(value)
        }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postCheckoutSessionsRequestBodyCustomTextSubmitVariant0(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public struct PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0X22021e911f: Codable {
    /// delivery_estimate_bound
    public var maximum: PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0X5f4513584b?
    /// delivery_estimate_bound
    public var minimum: PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0X27f99e5cec?

    enum CodingKeys: String, CodingKey {
        case maximum
        case minimum
    }

    init() {
        (self.maximum, self.minimum) = (nil, nil)
    }
}

public extension PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0X22021e911f {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.maximum = try container.sdkDecodeIfPresent(.maximum)
        self.minimum = try container.sdkDecodeIfPresent(.minimum)
    }
}

public extension PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0X22021e911f {
    public init(maximum: PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0X5f4513584b? = nil, minimum: PostCheckoutSessionsSessionRequestBodyShippingOptionsVariant0X27f99e5cec? = nil) {
        self.init()
        (self.maximum, self.minimum) = (maximum, minimum)
    }
}

/// Controls tax ID collection during checkout.
public struct PostCheckoutSessionsRequestBodyTaxIdCollection: Codable {
    public var enabled: Bool
    public var required: PostCheckoutSessionsRequestBodyTaxIdCollectionRequired?

    enum CodingKeys: String, CodingKey {
        case enabled
        case required
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostCheckoutSessionsRequestBodyTaxIdCollection {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.enabled) else {
            throw SdkValidationError(field: "enabled", code: "required", message: "Validation failed for 'enabled': value is required")
        }
        self.enabled = try container.sdkDecodeRequired(.enabled)
        self.required = try container.sdkDecodeIfPresent(.required)
    }
}

public extension PostCheckoutSessionsRequestBodyTaxIdCollection {
    public init(enabled: Bool, required: PostCheckoutSessionsRequestBodyTaxIdCollectionRequired? = nil) {
        (self.enabled, self.required) = (enabled, required)
    }
}

public struct PostCheckoutSessionsRequestBodyPaymentMethodOptionsAfterpayClearpay: Codable {
    public var captureMethod: PostCheckoutSessionsRequestBodyPaymentMethodOptionsAfterpayClXec64155fa1?
    public var setupFutureUsage: PostCheckoutSessionsRequestBodyPaymentMethodOptionsAfterpayClXb434c8d3a9?

    enum CodingKeys: String, CodingKey {
        case captureMethod = "capture_method"
        case setupFutureUsage = "setup_future_usage"
    }

    init() {
        (self.captureMethod, self.setupFutureUsage) = (nil, nil)
    }
}

public extension PostCheckoutSessionsRequestBodyPaymentMethodOptionsAfterpayClearpay {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.captureMethod = try container.sdkDecodeIfPresent(.captureMethod)
        self.setupFutureUsage = try container.sdkDecodeIfPresent(.setupFutureUsage)
    }
}

public extension PostCheckoutSessionsRequestBodyPaymentMethodOptionsAfterpayClearpay {
    public init(captureMethod: PostCheckoutSessionsRequestBodyPaymentMethodOptionsAfterpayClXec64155fa1? = nil, setupFutureUsage: PostCheckoutSessionsRequestBodyPaymentMethodOptionsAfterpayClXb434c8d3a9? = nil) {
        self.init()
        (self.captureMethod, self.setupFutureUsage) = (captureMethod, setupFutureUsage)
    }
}

public struct PostCheckoutSessionsRequestBodyLineItemsItemAdjustableQuantity: Codable {
    public var enabled: Bool
    public var maximum: Int?
    public var minimum: Int?

    enum CodingKeys: String, CodingKey {
        case enabled
        case maximum
        case minimum
    }

    private init(sdkCopy value: Self) { self = value }
}

public extension PostCheckoutSessionsRequestBodyLineItemsItemAdjustableQuantity {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.enabled) else {
            throw SdkValidationError(field: "enabled", code: "required", message: "Validation failed for 'enabled': value is required")
        }
        self.enabled = try container.sdkDecodeRequired(.enabled)
        self.maximum = try container.sdkDecodeIfPresent(.maximum)
        self.minimum = try container.sdkDecodeIfPresent(.minimum)
    }
}

public extension PostCheckoutSessionsRequestBodyLineItemsItemAdjustableQuantity {
    public init(enabled: Bool, maximum: Int? = nil, minimum: Int? = nil) {
        (self.enabled, self.maximum) = (enabled, maximum)
        self.minimum = minimum
    }
}

public struct GetCheckoutSessionsParameterX4956649c: Codable {
    public var email: String

    enum CodingKeys: String, CodingKey {
        case email
    }

    private init(sdkCopy value: Self) { self = value }
}
