// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif

/// Canonical v1PaymentIntents operation model declarations
public enum PostPaymentIntentsRequestBodyPaymentMethodOptionsUsBankAccount {
    case postPaymentIntentsRequestBodyPaymentMethodOptionsUsBankAccountVariant0(
        PostPaymentIntentsRequestBodyPaymentMethodOptionsUsBankAccountVariant0
    )
    case stringValue(String)
}

extension PostPaymentIntentsRequestBodyPaymentMethodOptionsUsBankAccount: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for PostPaymentIntentsRequestBodyPaymentMethodOptionsUsBankAccount"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PostPaymentIntentsRequestBodyPaymentMethodOptionsUsBankAccountVariant0.self
        ) {
            return .postPaymentIntentsRequestBodyPaymentMethodOptionsUsBankAccountVariant0(value)
        }
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postPaymentIntentsRequestBodyPaymentMethodOptionsUsBankAccountVariant0(value): try container
            .encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }
}

public enum PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsAlma {
    case postPaymentIntentsIntentRequestBodyPaymentMethodOptionsAlmaVariant0(
        PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsAlmaVariant0
    )
    case stringValue(String)
}

extension PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsAlma: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsAlma"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsAlmaVariant0.self
        ) {
            return .postPaymentIntentsIntentRequestBodyPaymentMethodOptionsAlmaVariant0(value)
        }
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postPaymentIntentsIntentRequestBodyPaymentMethodOptionsAlmaVariant0(value): try container
            .encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }
}

public struct PostPaymentIntentsRequestBodyPaymentMethodOptionsRevolutPayVariant0: Codable {
    public var captureMethod: PostPaymentIntentsRequestBodyPaymentMethodOptionsRevolutPayVaX62499ec712?
    public var setupFutureUsage: PostPaymentIntentsRequestBodyPaymentMethodOptionsRevolutPayVaXe8e4294c12?

    enum CodingKeys: String, CodingKey {
        case captureMethod = "capture_method"
        case setupFutureUsage = "setup_future_usage"
    }

    init() {
        (captureMethod, setupFutureUsage) = (nil, nil)
    }
}

public extension PostPaymentIntentsRequestBodyPaymentMethodOptionsRevolutPayVariant0 {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        captureMethod = try container.sdkDecodeIfPresent(.captureMethod)
        setupFutureUsage = try container.sdkDecodeIfPresent(.setupFutureUsage)
    }
}

public extension PostPaymentIntentsRequestBodyPaymentMethodOptionsRevolutPayVariant0 {
    init(
        captureMethod: PostPaymentIntentsRequestBodyPaymentMethodOptionsRevolutPayVaX62499ec712? = nil,
        setupFutureUsage: PostPaymentIntentsRequestBodyPaymentMethodOptionsRevolutPayVaXe8e4294c12? = nil
    ) {
        self.init()
        (self.captureMethod, self.setupFutureUsage) = (captureMethod, setupFutureUsage)
    }
}

public struct PostPaymentIntentsIntentRequestBodyAmountDetailsVariant0LineIX586c188a8a: Codable {
    public var commodityCode: String?

    enum CodingKeys: String, CodingKey {
        case commodityCode = "commodity_code"
    }

    init() {
        commodityCode = nil
    }
}

public extension PostPaymentIntentsIntentRequestBodyAmountDetailsVariant0LineIX586c188a8a {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        commodityCode = try container.sdkDecodeIfPresent(.commodityCode)
        if let value = commodityCode {
            try validateLength("commodity_code", value, min: nil, max: 12)
        }
    }
}

public extension PostPaymentIntentsIntentRequestBodyAmountDetailsVariant0LineIX586c188a8a {
    init(commodityCode: String? = nil) throws {
        self.init()
        self.commodityCode = commodityCode
        if let value = self.commodityCode {
            try validateLength("commodity_code", value, min: nil, max: 12)
        }
    }
}

public enum PostPaymentIntentsRequestBodyPaymentMethodOptionsTwint {
    case postPaymentIntentsRequestBodyPaymentMethodOptionsTwintVariant0(
        PostPaymentIntentsRequestBodyPaymentMethodOptionsTwintVariant0
    )
    case stringValue(String)
}

extension PostPaymentIntentsRequestBodyPaymentMethodOptionsTwint: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for PostPaymentIntentsRequestBodyPaymentMethodOptionsTwint"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PostPaymentIntentsRequestBodyPaymentMethodOptionsTwintVariant0.self
        ) {
            return .postPaymentIntentsRequestBodyPaymentMethodOptionsTwintVariant0(value)
        }
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postPaymentIntentsRequestBodyPaymentMethodOptionsTwintVariant0(value): try container
            .encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }
}

public struct PostPaymentIntentsIntentRequestBodyPaymentMethodDataEps: Codable {
    public var bank: PostPaymentIntentsIntentRequestBodyPaymentMethodDataEpsBank?

    enum CodingKeys: String, CodingKey {
        case bank
    }

    init() {
        bank = nil
    }
}

public extension PostPaymentIntentsIntentRequestBodyPaymentMethodDataEps {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        bank = try container.sdkDecodeIfPresent(.bank)
        if let value = bank {
            try validateLength("bank", sdkWireString(value), min: nil, max: 5000)
        }
    }
}

public extension PostPaymentIntentsIntentRequestBodyPaymentMethodDataEps {
    init(bank: PostPaymentIntentsIntentRequestBodyPaymentMethodDataEpsBank? = nil) throws {
        self.init()
        self.bank = bank
        if let value = self.bank {
            try validateLength("bank", sdkWireString(value), min: nil, max: 5000)
        }
    }
}

public enum PostPaymentIntentsRequestBodyPaymentMethodOptionsPayto {
    case postPaymentIntentsRequestBodyPaymentMethodOptionsPaytoVariant0(
        PostPaymentIntentsRequestBodyPaymentMethodOptionsPaytoVariant0
    )
    case stringValue(String)
}

extension PostPaymentIntentsRequestBodyPaymentMethodOptionsPayto: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for PostPaymentIntentsRequestBodyPaymentMethodOptionsPayto"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PostPaymentIntentsRequestBodyPaymentMethodOptionsPaytoVariant0.self
        ) {
            return .postPaymentIntentsRequestBodyPaymentMethodOptionsPaytoVariant0(value)
        }
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postPaymentIntentsRequestBodyPaymentMethodOptionsPaytoVariant0(value): try container
            .encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }
}

public enum PostPaymentIntentsRequestBodyPaymentMethodOptionsCrypto {
    case postPaymentIntentsRequestBodyPaymentMethodOptionsCryptoVariant0(
        PostPaymentIntentsRequestBodyPaymentMethodOptionsCryptoVariant0
    )
    case stringValue(String)
}

extension PostPaymentIntentsRequestBodyPaymentMethodOptionsCrypto: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for PostPaymentIntentsRequestBodyPaymentMethodOptionsCrypto"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PostPaymentIntentsRequestBodyPaymentMethodOptionsCryptoVariant0.self
        ) {
            return .postPaymentIntentsRequestBodyPaymentMethodOptionsCryptoVariant0(value)
        }
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postPaymentIntentsRequestBodyPaymentMethodOptionsCryptoVariant0(value): try container
            .encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }
}

public struct PostPaymentIntentsIntentRequestBodyPaymentMethodDataPix: Codable {
    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension PostPaymentIntentsIntentRequestBodyPaymentMethodDataPix {
    init() {}
}

public struct PostPaymentIntentsRequestBodyPaymentMethodOptionsPixVariant0MX90b1e2c23b: Codable {
    public var amount: Int?
    public var amountIncludesIof: PostPaymentIntentsRequestBodyPaymentMethodOptionsPixVariant0MXf61b5b0968?
    public var amountType: PostPaymentIntentsRequestBodyPaymentMethodOptionsPixVariant0MX40a66912cb?
    public var currency: String?
    public var endDate: String?
    public var paymentSchedule: PostPaymentIntentsRequestBodyPaymentMethodOptionsPixVariant0MX641532534c?
    public var reference: String?
    public var startDate: String?

    enum CodingKeys: String, CodingKey {
        case amount
        case amountIncludesIof = "amount_includes_iof"
        case amountType = "amount_type"
        case currency
        case endDate = "end_date"
        case paymentSchedule = "payment_schedule"
        case reference
        case startDate = "start_date"
    }

    init() {
        (amount, amountIncludesIof, amountType, currency, endDate) = (nil, nil, nil, nil, nil)
        (paymentSchedule, reference, startDate) = (nil, nil, nil)
    }
}

public extension PostPaymentIntentsRequestBodyPaymentMethodOptionsPixVariant0MX90b1e2c23b {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        amount = try container.sdkDecodeIfPresent(.amount)
        amountIncludesIof = try container.sdkDecodeIfPresent(.amountIncludesIof)
        amountType = try container.sdkDecodeIfPresent(.amountType)
        currency = try container.sdkDecodeIfPresent(.currency)
        endDate = try container.sdkDecodeIfPresent(.endDate)
        paymentSchedule = try container.sdkDecodeIfPresent(.paymentSchedule)
        reference = try container.sdkDecodeIfPresent(.reference)
        startDate = try container.sdkDecodeIfPresent(.startDate)
        if let value = endDate {
            try validateLength("end_date", value, min: nil, max: 5000)
        }
        if let value = reference {
            try validateLength("reference", value, min: nil, max: 35)
        }
        if let value = startDate {
            try validateLength("start_date", value, min: nil, max: 5000)
        }
    }
}

public extension PostPaymentIntentsRequestBodyPaymentMethodOptionsPixVariant0MX90b1e2c23b {
    init(
        amount: Int? = nil,
        amountIncludesIof: PostPaymentIntentsRequestBodyPaymentMethodOptionsPixVariant0MXf61b5b0968? = nil,
        amountType: PostPaymentIntentsRequestBodyPaymentMethodOptionsPixVariant0MX40a66912cb? = nil,
        currency: String? = nil,
        endDate: String? = nil,
        paymentSchedule: PostPaymentIntentsRequestBodyPaymentMethodOptionsPixVariant0MX641532534c? = nil,
        reference: String? = nil,
        startDate: String? = nil
    ) throws {
        self.init()
        (self.amount, self.amountIncludesIof) = (amount, amountIncludesIof)
        (self.amountType, self.currency) = (amountType, currency)
        (self.endDate, self.paymentSchedule) = (endDate, paymentSchedule)
        (self.reference, self.startDate) = (reference, startDate)
        if let value = self.endDate {
            try validateLength("end_date", value, min: nil, max: 5000)
        }
        if let value = self.reference {
            try validateLength("reference", value, min: nil, max: 35)
        }
        if let value = self.startDate {
            try validateLength("start_date", value, min: nil, max: 5000)
        }
    }
}

public enum PostPaymentIntentsRequestBodyPaymentMethodOptionsEps {
    case postPaymentIntentsRequestBodyPaymentMethodOptionsEpsVariant0(
        PostPaymentIntentsRequestBodyPaymentMethodOptionsEpsVariant0
    )
    case stringValue(String)
}

extension PostPaymentIntentsRequestBodyPaymentMethodOptionsEps: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for PostPaymentIntentsRequestBodyPaymentMethodOptionsEps"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PostPaymentIntentsRequestBodyPaymentMethodOptionsEpsVariant0.self
        ) {
            return .postPaymentIntentsRequestBodyPaymentMethodOptionsEpsVariant0(value)
        }
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postPaymentIntentsRequestBodyPaymentMethodOptionsEpsVariant0(value): try container
            .encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }
}

/// Options to configure Radar. Learn more about Radar Sessions.
public struct PostPaymentIntentsRequestBodyRadarOptions: Codable {
    public var referrer: PostPaymentIntentsRequestBodyRadarOptionsReferrer?
    public var session: String?

    enum CodingKeys: String, CodingKey {
        case referrer
        case session
    }

    init() {
        (referrer, session) = (nil, nil)
    }
}

public extension PostPaymentIntentsRequestBodyRadarOptions {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        referrer = try container.sdkDecodeIfPresent(.referrer)
        session = try container.sdkDecodeIfPresent(.session)
        if let value = session {
            try validateLength("session", value, min: nil, max: 5000)
        }
    }
}

public extension PostPaymentIntentsRequestBodyRadarOptions {
    init(referrer: PostPaymentIntentsRequestBodyRadarOptionsReferrer? = nil, session: String? = nil) throws {
        self.init()
        (self.referrer, self.session) = (referrer, session)
        if let value = self.session {
            try validateLength("session", value, min: nil, max: 5000)
        }
    }
}

public typealias PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankXad42a7a9d6 =
    [PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankX6084dfa2c4]

public struct PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankX760aecb439: Codable {
    public var accountSubcategories: PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankXad42a7a9d6?

    enum CodingKeys: String, CodingKey {
        case accountSubcategories = "account_subcategories"
    }

    init() {
        accountSubcategories = nil
    }
}

public extension PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankX760aecb439 {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        accountSubcategories = try container.sdkDecodeIfPresent(.accountSubcategories)
    }
}

public extension PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankX760aecb439 {
    init(accountSubcategories: PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankXad42a7a9d6? = nil) {
        self.init()
        self.accountSubcategories = accountSubcategories
    }
}

public struct PostPaymentIntentsRequestBodyPaymentMethodDataCustomerBalance: Codable {
    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension PostPaymentIntentsRequestBodyPaymentMethodDataCustomerBalance {
    init() {}
}

public enum PostPaymentIntentsRequestBodyPaymentMethodOptionsMobilepay {
    case postPaymentIntentsRequestBodyPaymentMethodOptionsMobilepayVariant0(
        PostPaymentIntentsRequestBodyPaymentMethodOptionsMobilepayVariant0
    )
    case stringValue(String)
}

extension PostPaymentIntentsRequestBodyPaymentMethodOptionsMobilepay: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for PostPaymentIntentsRequestBodyPaymentMethodOptionsMobilepay"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PostPaymentIntentsRequestBodyPaymentMethodOptionsMobilepayVariant0.self
        ) {
            return .postPaymentIntentsRequestBodyPaymentMethodOptionsMobilepayVariant0(value)
        }
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .postPaymentIntentsRequestBodyPaymentMethodOptionsMobilepayVariant0(value): try container
            .encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }
}

public struct PostPaymentIntentsRequestBodyPaymentMethodDataBancontact: Codable {
    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension PostPaymentIntentsRequestBodyPaymentMethodDataBancontact {
    init() {}
}

public struct PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsAmazonPayVariant0: Codable {
    public var captureMethod: PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsAmazonX7c9968d5ee?
    public var setupFutureUsage: PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsAmazonX1c325f6040?

    enum CodingKeys: String, CodingKey {
        case captureMethod = "capture_method"
        case setupFutureUsage = "setup_future_usage"
    }

    init() {
        (captureMethod, setupFutureUsage) = (nil, nil)
    }
}

public extension PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsAmazonPayVariant0 {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        captureMethod = try container.sdkDecodeIfPresent(.captureMethod)
        setupFutureUsage = try container.sdkDecodeIfPresent(.setupFutureUsage)
    }
}
