// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif

// Canonical v1Accounts operation model declarations
extension PostAccountsRequestBodyCapabilities {
    mutating func sdkSet10(_ paynowPayments: PostAccountsRequestBodyCapabilitiesPaynowPayments?, _ paytoPayments: PostAccountsRequestBodyCapabilitiesPaytoPayments?, _ pixPayments: PostAccountsRequestBodyCapabilitiesPixPayments?, _ promptpayPayments: PostAccountsRequestBodyCapabilitiesPromptpayPayments?, _ revolutPayPayments: PostAccountsRequestBodyCapabilitiesRevolutPayPayments?) {
        self.paynowPayments = paynowPayments
        self.paytoPayments = paytoPayments
        self.pixPayments = pixPayments
        self.promptpayPayments = promptpayPayments
        self.revolutPayPayments = revolutPayPayments
    }
}

extension PostAccountsRequestBodyCapabilities {
    mutating func sdkSet11(_ samsungPayPayments: PostAccountsRequestBodyCapabilitiesSamsungPayPayments?, _ satispayPayments: PostAccountsRequestBodyCapabilitiesSatispayPayments?, _ scalapayPayments: PostAccountsRequestBodyCapabilitiesScalapayPayments?, _ sepaBankTransferPayments: PostAccountsRequestBodyCapabilitiesSepaBankTransferPayments?, _ sepaDebitPayments: PostAccountsRequestBodyCapabilitiesSepaDebitPayments?) {
        self.samsungPayPayments = samsungPayPayments
        self.satispayPayments = satispayPayments
        self.scalapayPayments = scalapayPayments
        self.sepaBankTransferPayments = sepaBankTransferPayments
        self.sepaDebitPayments = sepaDebitPayments
    }
}

extension PostAccountsRequestBodyCapabilities {
    mutating func sdkSet12(_ sofortPayments: PostAccountsRequestBodyCapabilitiesSofortPayments?, _ sunbitPayments: PostAccountsRequestBodyCapabilitiesSunbitPayments?, _ swishPayments: PostAccountsRequestBodyCapabilitiesSwishPayments?, _ taxReportingUs1099K: PostAccountsRequestBodyCapabilitiesTaxReportingUs1099K?, _ taxReportingUs1099Misc: PostAccountsRequestBodyCapabilitiesTaxReportingUs1099Misc?) {
        self.sofortPayments = sofortPayments
        self.sunbitPayments = sunbitPayments
        self.swishPayments = swishPayments
        self.taxReportingUs1099K = taxReportingUs1099K
        self.taxReportingUs1099Misc = taxReportingUs1099Misc
    }
}

extension PostAccountsRequestBodyCapabilities {
    mutating func sdkSet13(_ transfers: PostAccountsRequestBodyCapabilitiesTransfers?, _ treasury: PostAccountsRequestBodyCapabilitiesTreasury?, _ twintPayments: PostAccountsRequestBodyCapabilitiesTwintPayments?, _ upiPayments: PostAccountsRequestBodyCapabilitiesUpiPayments?, _ usBankAccountAchPayments: PostAccountsRequestBodyCapabilitiesUsBankAccountAchPayments?) {
        self.transfers = transfers
        self.treasury = treasury
        self.twintPayments = twintPayments
        self.upiPayments = upiPayments
        self.usBankAccountAchPayments = usBankAccountAchPayments
    }
}

extension PostAccountsRequestBodyCapabilities {
    mutating func sdkSet14(_ usBankTransferPayments: PostAccountsRequestBodyCapabilitiesUsBankTransferPayments?, _ zipPayments: PostAccountsRequestBodyCapabilitiesZipPayments?) {
        self.usBankTransferPayments = usBankTransferPayments
        self.zipPayments = zipPayments
    }
}

extension PostAccountsRequestBodyCapabilities {
    mutating func sdkDecodeFieldsPart1(_ container: KeyedDecodingContainer<CodingKeys>) throws {
        self.acssDebitPayments = try container.sdkDecodeIfPresent(.acssDebitPayments)
        self.affirmPayments = try container.sdkDecodeIfPresent(.affirmPayments)
        self.afterpayClearpayPayments = try container.sdkDecodeIfPresent(.afterpayClearpayPayments)
        self.almaPayments = try container.sdkDecodeIfPresent(.almaPayments)
        self.amazonPayPayments = try container.sdkDecodeIfPresent(.amazonPayPayments)
        self.appDistribution = try container.sdkDecodeIfPresent(.appDistribution)
        self.auBecsDebitPayments = try container.sdkDecodeIfPresent(.auBecsDebitPayments)
        self.bacsDebitPayments = try container.sdkDecodeIfPresent(.bacsDebitPayments)
        self.bancontactPayments = try container.sdkDecodeIfPresent(.bancontactPayments)
        self.bankTransferPayments = try container.sdkDecodeIfPresent(.bankTransferPayments)
        self.billiePayments = try container.sdkDecodeIfPresent(.billiePayments)
        self.bizumPayments = try container.sdkDecodeIfPresent(.bizumPayments)
    }
}

extension PostAccountsRequestBodyCapabilities {
    mutating func sdkDecodeFieldsPart2(_ container: KeyedDecodingContainer<CodingKeys>) throws {
        self.blikPayments = try container.sdkDecodeIfPresent(.blikPayments)
        self.boletoPayments = try container.sdkDecodeIfPresent(.boletoPayments)
        self.cardIssuing = try container.sdkDecodeIfPresent(.cardIssuing)
        self.cardPayments = try container.sdkDecodeIfPresent(.cardPayments)
        self.cartesBancairesPayments = try container.sdkDecodeIfPresent(.cartesBancairesPayments)
        self.cashappPayments = try container.sdkDecodeIfPresent(.cashappPayments)
        self.cryptoPayments = try container.sdkDecodeIfPresent(.cryptoPayments)
        self.epsPayments = try container.sdkDecodeIfPresent(.epsPayments)
        self.fpxPayments = try container.sdkDecodeIfPresent(.fpxPayments)
        self.gbBankTransferPayments = try container.sdkDecodeIfPresent(.gbBankTransferPayments)
        self.giropayPayments = try container.sdkDecodeIfPresent(.giropayPayments)
        self.grabpayPayments = try container.sdkDecodeIfPresent(.grabpayPayments)
    }
}

extension PostAccountsRequestBodyCapabilities {
    mutating func sdkDecodeFieldsPart3(_ container: KeyedDecodingContainer<CodingKeys>) throws {
        self.idealPayments = try container.sdkDecodeIfPresent(.idealPayments)
        self.indiaInternationalPayments = try container.sdkDecodeIfPresent(.indiaInternationalPayments)
        self.jcbPayments = try container.sdkDecodeIfPresent(.jcbPayments)
        self.jpBankTransferPayments = try container.sdkDecodeIfPresent(.jpBankTransferPayments)
        self.kakaoPayPayments = try container.sdkDecodeIfPresent(.kakaoPayPayments)
        self.klarnaPayments = try container.sdkDecodeIfPresent(.klarnaPayments)
        self.konbiniPayments = try container.sdkDecodeIfPresent(.konbiniPayments)
        self.krCardPayments = try container.sdkDecodeIfPresent(.krCardPayments)
        self.legacyPayments = try container.sdkDecodeIfPresent(.legacyPayments)
        self.linkPayments = try container.sdkDecodeIfPresent(.linkPayments)
        self.mbWayPayments = try container.sdkDecodeIfPresent(.mbWayPayments)
        self.mobilepayPayments = try container.sdkDecodeIfPresent(.mobilepayPayments)
    }
}

extension PostAccountsRequestBodyCapabilities {
    mutating func sdkDecodeFieldsPart4(_ container: KeyedDecodingContainer<CodingKeys>) throws {
        self.multibancoPayments = try container.sdkDecodeIfPresent(.multibancoPayments)
        self.mxBankTransferPayments = try container.sdkDecodeIfPresent(.mxBankTransferPayments)
        self.naverPayPayments = try container.sdkDecodeIfPresent(.naverPayPayments)
        self.nzBankAccountBecsDebitPayments = try container.sdkDecodeIfPresent(.nzBankAccountBecsDebitPayments)
        self.oxxoPayments = try container.sdkDecodeIfPresent(.oxxoPayments)
        self.p24Payments = try container.sdkDecodeIfPresent(.p24Payments)
        self.payByBankPayments = try container.sdkDecodeIfPresent(.payByBankPayments)
        self.paycoPayments = try container.sdkDecodeIfPresent(.paycoPayments)
        self.paynowPayments = try container.sdkDecodeIfPresent(.paynowPayments)
        self.paytoPayments = try container.sdkDecodeIfPresent(.paytoPayments)
        self.pixPayments = try container.sdkDecodeIfPresent(.pixPayments)
        self.promptpayPayments = try container.sdkDecodeIfPresent(.promptpayPayments)
    }
}

extension PostAccountsRequestBodyCapabilities {
    mutating func sdkDecodeFieldsPart5(_ container: KeyedDecodingContainer<CodingKeys>) throws {
        self.revolutPayPayments = try container.sdkDecodeIfPresent(.revolutPayPayments)
        self.samsungPayPayments = try container.sdkDecodeIfPresent(.samsungPayPayments)
        self.satispayPayments = try container.sdkDecodeIfPresent(.satispayPayments)
        self.scalapayPayments = try container.sdkDecodeIfPresent(.scalapayPayments)
        self.sepaBankTransferPayments = try container.sdkDecodeIfPresent(.sepaBankTransferPayments)
        self.sepaDebitPayments = try container.sdkDecodeIfPresent(.sepaDebitPayments)
        self.sofortPayments = try container.sdkDecodeIfPresent(.sofortPayments)
        self.sunbitPayments = try container.sdkDecodeIfPresent(.sunbitPayments)
        self.swishPayments = try container.sdkDecodeIfPresent(.swishPayments)
        self.taxReportingUs1099K = try container.sdkDecodeIfPresent(.taxReportingUs1099K)
        self.taxReportingUs1099Misc = try container.sdkDecodeIfPresent(.taxReportingUs1099Misc)
        self.transfers = try container.sdkDecodeIfPresent(.transfers)
    }
}

extension PostAccountsRequestBodyCapabilities {
    mutating func sdkDecodeFieldsPart6(_ container: KeyedDecodingContainer<CodingKeys>) throws {
        self.treasury = try container.sdkDecodeIfPresent(.treasury)
        self.twintPayments = try container.sdkDecodeIfPresent(.twintPayments)
        self.upiPayments = try container.sdkDecodeIfPresent(.upiPayments)
        self.usBankAccountAchPayments = try container.sdkDecodeIfPresent(.usBankAccountAchPayments)
        self.usBankTransferPayments = try container.sdkDecodeIfPresent(.usBankTransferPayments)
        self.zipPayments = try container.sdkDecodeIfPresent(.zipPayments)
    }
}

public struct PostAccountsRequestBodyCapabilitiesKrCardPayments: Codable {
    public var requested: Bool?

    enum CodingKeys: String, CodingKey {
        case requested
    }

    init() {
        self.requested = nil
    }
}

extension PostAccountsRequestBodyCapabilitiesKrCardPayments {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.requested = try container.sdkDecodeIfPresent(.requested)
    }
}

extension PostAccountsRequestBodyCapabilitiesKrCardPayments {
    public init(requested: Bool? = nil) {
        self.init()
        self.requested = requested
    }
}

public struct PostAccountsRequestBodyDocumentsProofOfAddress: Codable {
    public var files: [String]?

    enum CodingKeys: String, CodingKey {
        case files
    }

    init() {
        self.files = nil
    }
}

extension PostAccountsRequestBodyDocumentsProofOfAddress {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.files = try container.sdkDecodeIfPresent(.files)
    }
}

extension PostAccountsRequestBodyDocumentsProofOfAddress {
    public init(files: [String]? = nil) {
        self.init()
        self.files = files
    }
}

public struct PostAccountsRequestBodyBusinessProfileSupportAddress: Codable {
    public var city: String?
    public var country: String?
    public var line1: String?
    public var line2: String?
    public var postalCode: String?
    public var state: String?

    enum CodingKeys: String, CodingKey {
        case city
        case country
        case line1
        case line2
        case postalCode = "postal_code"
        case state
    }

    init() {
        (self.city, self.country, self.line1, self.line2, self.postalCode) = (nil, nil, nil, nil, nil)
        self.state = nil
    }
}

extension PostAccountsRequestBodyBusinessProfileSupportAddress {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.city = try container.sdkDecodeIfPresent(.city)
        self.country = try container.sdkDecodeIfPresent(.country)
        self.line1 = try container.sdkDecodeIfPresent(.line1)
        self.line2 = try container.sdkDecodeIfPresent(.line2)
        self.postalCode = try container.sdkDecodeIfPresent(.postalCode)
        self.state = try container.sdkDecodeIfPresent(.state)
        if let value = self.city {
            try validateLength("city", value, min: nil, max: 100)
        }
        if let value = self.country {
            try validateLength("country", value, min: nil, max: 5000)
        }
        if let value = self.line1 {
            try validateLength("line1", value, min: nil, max: 200)
        }
        if let value = self.line2 {
            try validateLength("line2", value, min: nil, max: 200)
        }
        if let value = self.postalCode {
            try validateLength("postal_code", value, min: nil, max: 5000)
        }
        if let value = self.state {
            try validateLength("state", value, min: nil, max: 5000)
        }
    }
}

extension PostAccountsRequestBodyBusinessProfileSupportAddress {
    public init(city: String? = nil, country: String? = nil, line1: String? = nil, line2: String? = nil, postalCode: String? = nil, state: String? = nil) throws {
        self.init()
        (self.city, self.country) = (city, country)
        (self.line1, self.line2) = (line1, line2)
        (self.postalCode, self.state) = (postalCode, state)
        if let value = self.city {
            try validateLength("city", value, min: nil, max: 100)
        }
        if let value = self.country {
            try validateLength("country", value, min: nil, max: 5000)
        }
        if let value = self.line1 {
            try validateLength("line1", value, min: nil, max: 200)
        }
        if let value = self.line2 {
            try validateLength("line2", value, min: nil, max: 200)
        }
        if let value = self.postalCode {
            try validateLength("postal_code", value, min: nil, max: 5000)
        }
        if let value = self.state {
            try validateLength("state", value, min: nil, max: 5000)
        }
    }
}

public struct PostAccountsRequestBodyCapabilitiesGbBankTransferPayments: Codable {
    public var requested: Bool?

    enum CodingKeys: String, CodingKey {
        case requested
    }

    init() {
        self.requested = nil
    }
}

extension PostAccountsRequestBodyCapabilitiesGbBankTransferPayments {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.requested = try container.sdkDecodeIfPresent(.requested)
    }
}

extension PostAccountsRequestBodyCapabilitiesGbBankTransferPayments {
    public init(requested: Bool? = nil) {
        self.init()
        self.requested = requested
    }
}

public struct PostAccountsAccountRequestBodyCapabilitiesAfterpayClearpayPayments: Codable {
    public var requested: Bool?

    enum CodingKeys: String, CodingKey {
        case requested
    }

    init() {
        self.requested = nil
    }
}

extension PostAccountsAccountRequestBodyCapabilitiesAfterpayClearpayPayments {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.requested = try container.sdkDecodeIfPresent(.requested)
    }
}

extension PostAccountsAccountRequestBodyCapabilitiesAfterpayClearpayPayments {
    public init(requested: Bool? = nil) {
        self.init()
        self.requested = requested
    }
}

public struct PostAccountsRequestBodyCapabilitiesBoletoPayments: Codable {
    public var requested: Bool?

    enum CodingKeys: String, CodingKey {
        case requested
    }

    init() {
        self.requested = nil
    }
}

extension PostAccountsRequestBodyCapabilitiesBoletoPayments {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.requested = try container.sdkDecodeIfPresent(.requested)
    }
}

extension PostAccountsRequestBodyCapabilitiesBoletoPayments {
    public init(requested: Bool? = nil) {
        self.init()
        self.requested = requested
    }
}

public enum PostAccountsRequestBodyMetadata {
    case dictionary([String: String])
    case stringValue(String)
}

extension PostAccountsRequestBodyMetadata: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PostAccountsRequestBodyMetadata")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode([String: String].self) { return .dictionary(value) }
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .dictionary(value): try container.encode(value); return true
        case let .stringValue(value): try container.encode(value); return true
        }
    }

}

public struct PostAccountsAccountRequestBodyCapabilitiesJpBankTransferPayments: Codable {
    public var requested: Bool?

    enum CodingKeys: String, CodingKey {
        case requested
    }

    init() {
        self.requested = nil
    }
}

extension PostAccountsAccountRequestBodyCapabilitiesJpBankTransferPayments {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.requested = try container.sdkDecodeIfPresent(.requested)
    }
}

extension PostAccountsAccountRequestBodyCapabilitiesJpBankTransferPayments {
    public init(requested: Bool? = nil) {
        self.init()
        self.requested = requested
    }
}

public struct PostAccountsRequestBodySettingsInvoices: Codable {
    public var hostedPaymentMethodSave: PostAccountsRequestBodySettingsInvoicesHostedPaymentMethodSave?

    enum CodingKeys: String, CodingKey {
        case hostedPaymentMethodSave = "hosted_payment_method_save"
    }

    init() {
        self.hostedPaymentMethodSave = nil
    }
}

extension PostAccountsRequestBodySettingsInvoices {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.hostedPaymentMethodSave = try container.sdkDecodeIfPresent(.hostedPaymentMethodSave)
    }
}

extension PostAccountsRequestBodySettingsInvoices {
    public init(hostedPaymentMethodSave: PostAccountsRequestBodySettingsInvoicesHostedPaymentMethodSave? = nil) {
        self.init()
        self.hostedPaymentMethodSave = hostedPaymentMethodSave
    }
}

public struct PostAccountsRequestBodyIndividualVerificationAdditionalDocument: Codable {
    public var back: String?
    public var front: String?

    enum CodingKeys: String, CodingKey {
        case back
        case front
    }

    init() {
        (self.back, self.front) = (nil, nil)
    }
}

extension PostAccountsRequestBodyIndividualVerificationAdditionalDocument {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.back = try container.sdkDecodeIfPresent(.back)
        self.front = try container.sdkDecodeIfPresent(.front)
        if let value = self.back {
            try validateLength("back", value, min: nil, max: 500)
        }
        if let value = self.front {
            try validateLength("front", value, min: nil, max: 500)
        }
    }
}

extension PostAccountsRequestBodyIndividualVerificationAdditionalDocument {
    public init(back: String? = nil, front: String? = nil) throws {
        self.init()
        (self.back, self.front) = (back, front)
        if let value = self.back {
            try validateLength("back", value, min: nil, max: 500)
        }
        if let value = self.front {
            try validateLength("front", value, min: nil, max: 500)
        }
    }
}

public struct PostAccountsRequestBodyCapabilitiesBilliePayments: Codable {
    public var requested: Bool?

    enum CodingKeys: String, CodingKey {
        case requested
    }

    init() {
        self.requested = nil
    }
}

extension PostAccountsRequestBodyCapabilitiesBilliePayments {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.requested = try container.sdkDecodeIfPresent(.requested)
    }
}

extension PostAccountsRequestBodyCapabilitiesBilliePayments {
    public init(requested: Bool? = nil) {
        self.init()
        self.requested = requested
    }
}

public struct PostAccountsRequestBodyBankAccountVariant0: Codable {
    public var accountNumber: String
    public var country: String
    public var accountHolderName: String?
    public var accountHolderType: PostAccountsRequestBodyBankAccountVariant0AccountHolderType?
    public var accountType: PostAccountsRequestBodyBankAccountVariant0AccountType?
    public var currency: String?
    /// external_account_documents_param
    public var documents: PostAccountsRequestBodyBankAccountVariant0Documents?
    public var object: PostAccountsRequestBodyBankAccountVariant0Object?
    public var routingNumber: String?

    enum CodingKeys: String, CodingKey {
        case accountNumber = "account_number"
        case country
        case accountHolderName = "account_holder_name"
        case accountHolderType = "account_holder_type"
        case accountType = "account_type"
        case currency
        case documents
        case object
        case routingNumber = "routing_number"
    }

    private init(sdkCopy value: Self) { self = value }
}

extension PostAccountsRequestBodyBankAccountVariant0 {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.accountNumber) else {
            throw SdkValidationError(field: "account_number", code: "required", message: "Validation failed for 'account_number': value is required")
        }
        guard container.contains(.country) else {
            throw SdkValidationError(field: "country", code: "required", message: "Validation failed for 'country': value is required")
        }
        self.accountNumber = try container.sdkDecodeRequired(.accountNumber)
        self.country = try container.sdkDecodeRequired(.country)
        self.accountHolderName = try container.sdkDecodeIfPresent(.accountHolderName)
        self.accountHolderType = try container.sdkDecodeIfPresent(.accountHolderType)
        self.accountType = try container.sdkDecodeIfPresent(.accountType)
        self.currency = try container.sdkDecodeIfPresent(.currency)
        self.documents = try container.sdkDecodeIfPresent(.documents)
        self.object = try container.sdkDecodeIfPresent(.object)
        self.routingNumber = try container.sdkDecodeIfPresent(.routingNumber)
        try sdkValidateConstraints()
    }
}

extension PostAccountsRequestBodyBankAccountVariant0 {
    public init(accountNumber: String, country: String, accountHolderName: String? = nil, accountHolderType: PostAccountsRequestBodyBankAccountVariant0AccountHolderType? = nil, accountType: PostAccountsRequestBodyBankAccountVariant0AccountType? = nil, currency: String? = nil, documents: PostAccountsRequestBodyBankAccountVariant0Documents? = nil, object: PostAccountsRequestBodyBankAccountVariant0Object? = nil, routingNumber: String? = nil) throws {
        (self.accountNumber, self.country) = (accountNumber, country)
        (self.accountHolderName, self.accountHolderType) = (accountHolderName, accountHolderType)
        (self.accountType, self.currency) = (accountType, currency)
        (self.documents, self.object) = (documents, object)
        self.routingNumber = routingNumber
        try sdkValidateConstraints()
    }
}
