// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

/// V1Custom domain models
/// Typed representation of the `CustomLogo` API schema.
public struct CustomLogo: Codable {
    /// URL of the Dashboard-only CustomPaymentMethodType logo.
    public var url: String
    /// Content type of the Dashboard-only CustomPaymentMethodType logo.
    public var contentType: String?

    enum CodingKeys: String, CodingKey {
        case url
        case contentType = "content_type"
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension CustomLogo {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.url) else {
            throw SdkValidationError(
                field: "url",
                code: "required",
                message: "Validation failed for 'url': value is required"
            )
        }
        url = try container.sdkDecodeRequired(.url)
        contentType = try container.sdkDecodeIfPresent(.contentType)
        try validateLength("url", url, min: nil, max: 5000)
        if let value = contentType {
            try validateLength("content_type", value, min: nil, max: 5000)
        }
    }
}

public extension CustomLogo {
    init(url: String, contentType: String? = nil) throws {
        (self.url, self.contentType) = (url, contentType)
        try validateLength("url", self.url, min: nil, max: 5000)
        if let value = self.contentType {
            try validateLength("content_type", value, min: nil, max: 5000)
        }
    }
}

/// Typed representation of the `CustomUnitAmount` API schema.
public struct CustomUnitAmount: Codable {
    /// The maximum unit amount the customer can specify for this item.
    public var maximum: Int?
    /// The minimum unit amount the customer can specify for this item. Must be at least the minimum charge amount.
    public var minimum: Int?
    /// The starting unit amount which can be updated by the customer.
    public var preset: Int?

    enum CodingKeys: String, CodingKey {
        case maximum
        case minimum
        case preset
    }

    init() {
        (maximum, minimum, preset) = (nil, nil, nil)
    }
}

public extension CustomUnitAmount {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        maximum = try container.sdkDecodeIfPresent(.maximum)
        minimum = try container.sdkDecodeIfPresent(.minimum)
        preset = try container.sdkDecodeIfPresent(.preset)
    }
}

public extension CustomUnitAmount {
    init(maximum: Int? = nil, minimum: Int? = nil, preset: Int? = nil) {
        self.init()
        (self.maximum, self.minimum) = (maximum, minimum)
        self.preset = preset
    }
}
