// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

/// V1 domain models
public extension PaymentMethodDetailsIdeal {
    init(
        bank: PaymentMethodDetailsIdealBank? = nil,
        bic: PaymentMethodDetailsIdealBic? = nil,
        generatedSepaDebit: PaymentMethodDetailsIdealGeneratedSepaDebit? = nil,
        generatedSepaDebitMandate: PaymentMethodDetailsIdealGeneratedSepaDebitMandate? = nil,
        ibanLast4: String? = nil,
        transactionId: String? = nil,
        verifiedName: String? = nil
    ) throws {
        self.init()
        (self.bank, self.bic) = (bank, bic)
        self.generatedSepaDebit = generatedSepaDebit
        (self.generatedSepaDebitMandate, self.ibanLast4) = (generatedSepaDebitMandate, ibanLast4)
        (self.transactionId, self.verifiedName) = (transactionId, verifiedName)
        if let value = self.ibanLast4 {
            try validateLength("iban_last4", value, min: nil, max: 5000)
        }
        if let value = self.transactionId {
            try validateLength("transaction_id", value, min: nil, max: 5000)
        }
        if let value = self.verifiedName {
            try validateLength("verified_name", value, min: nil, max: 5000)
        }
    }
}

public indirect enum PaymentMethodDetailsIdealGeneratedSepaDebit {
    case stringValue(String)
    case paymentMethod(PaymentMethod)
}

extension PaymentMethodDetailsIdealGeneratedSepaDebit: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for PaymentMethodDetailsIdealGeneratedSepaDebit"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        if let value = try? container.decode(PaymentMethod.self) {
            return .paymentMethod(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .paymentMethod(value): try container.encode(value); return true
        }
    }
}

public indirect enum PaymentMethodDetailsIdealGeneratedSepaDebitMandate {
    case stringValue(String)
    case mandate(Mandate)
}

extension PaymentMethodDetailsIdealGeneratedSepaDebitMandate: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for PaymentMethodDetailsIdealGeneratedSepaDebitMandate"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        if let value = try? container.decode(Mandate.self) {
            return .mandate(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .mandate(value): try container.encode(value); return true
        }
    }
}

/// Typed representation of the `PaymentMethodDetailsPaymentRecordBancontact` API schema.
public struct PaymentMethodDetailsPaymentRecordBancontact: Codable {
    /// Bank code of bank associated with the bank account.
    public var bankCode: String?
    /// Name of the bank associated with the bank account.
    public var bankName: String?
    /// Bank Identifier Code of the bank associated with the bank account.
    public var bic: String?
    /// The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
    public var generatedSepaDebit: PaymentMethodDetailsPaymentRecordBancontactGeneratedSepaDebit?
    /// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
    public var generatedSepaDebitMandate: PaymentMethodDetailsPaymentRecordBancontactGeneratedSepaDebitMandate?
    /// Last four characters of the IBAN.
    public var ibanLast4: String?
    /// Preferred language of the Bancontact authorization page that the customer is redirected to. Can be one of
    /// `en`, `de`, `fr`, or `nl`
    public var preferredLanguage: PaymentMethodDetailsPaymentRecordBancontactPreferredLanguage?
    /// Owner's verified full name. Values are verified or provided by Bancontact directly (if supported) at the
    /// time of authorization or settlement. They cannot be set or mutated.
    public var verifiedName: String?

    enum CodingKeys: String, CodingKey {
        case bankCode = "bank_code"
        case bankName = "bank_name"
        case bic
        case generatedSepaDebit = "generated_sepa_debit"
        case generatedSepaDebitMandate = "generated_sepa_debit_mandate"
        case ibanLast4 = "iban_last4"
        case preferredLanguage = "preferred_language"
        case verifiedName = "verified_name"
    }

    init() {
        (bankCode, bankName, bic, generatedSepaDebit, generatedSepaDebitMandate) = (nil, nil, nil, nil, nil)
        (ibanLast4, preferredLanguage, verifiedName) = (nil, nil, nil)
    }
}

public extension PaymentMethodDetailsPaymentRecordBancontact {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        bankCode = try container.sdkDecodeIfPresent(.bankCode)
        bankName = try container.sdkDecodeIfPresent(.bankName)
        bic = try container.sdkDecodeIfPresent(.bic)
        generatedSepaDebit = try container.sdkDecodeIfPresent(.generatedSepaDebit)
        generatedSepaDebitMandate = try container.sdkDecodeIfPresent(.generatedSepaDebitMandate)
        ibanLast4 = try container.sdkDecodeIfPresent(.ibanLast4)
        preferredLanguage = try container.sdkDecodeIfPresent(.preferredLanguage)
        verifiedName = try container.sdkDecodeIfPresent(.verifiedName)
        if let value = bankCode {
            try validateLength("bank_code", value, min: nil, max: 5000)
        }
        if let value = bankName {
            try validateLength("bank_name", value, min: nil, max: 5000)
        }
        if let value = bic {
            try validateLength("bic", value, min: nil, max: 5000)
        }
        if let value = ibanLast4 {
            try validateLength("iban_last4", value, min: nil, max: 5000)
        }
        if let value = verifiedName {
            try validateLength("verified_name", value, min: nil, max: 5000)
        }
    }
}

public extension PaymentMethodDetailsPaymentRecordBancontact {
    init(
        bankCode: String? = nil,
        bankName: String? = nil,
        bic: String? = nil,
        generatedSepaDebit: PaymentMethodDetailsPaymentRecordBancontactGeneratedSepaDebit? = nil,
        generatedSepaDebitMandate: PaymentMethodDetailsPaymentRecordBancontactGeneratedSepaDebitMandate? = nil,
        ibanLast4: String? = nil,
        preferredLanguage: PaymentMethodDetailsPaymentRecordBancontactPreferredLanguage? = nil,
        verifiedName: String? = nil
    ) throws {
        self.init()
        (self.bankCode, self.bankName) = (bankCode, bankName)
        (self.bic, self.generatedSepaDebit) = (bic, generatedSepaDebit)
        (self.generatedSepaDebitMandate, self.ibanLast4) = (generatedSepaDebitMandate, ibanLast4)
        (self.preferredLanguage, self.verifiedName) = (preferredLanguage, verifiedName)
        if let value = self.bankCode {
            try validateLength("bank_code", value, min: nil, max: 5000)
        }
        if let value = self.bankName {
            try validateLength("bank_name", value, min: nil, max: 5000)
        }
        if let value = self.bic {
            try validateLength("bic", value, min: nil, max: 5000)
        }
        if let value = self.ibanLast4 {
            try validateLength("iban_last4", value, min: nil, max: 5000)
        }
        if let value = self.verifiedName {
            try validateLength("verified_name", value, min: nil, max: 5000)
        }
    }
}

public enum PaymentMethodDetailsPaymentRecordBancontactGeneratedSepaDebit {
    case stringValue(String)
    case paymentMethod(PaymentMethod)
}

extension PaymentMethodDetailsPaymentRecordBancontactGeneratedSepaDebit: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for PaymentMethodDetailsPaymentRecordBancontactGeneratedSepaDebit"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        if let value = try? container.decode(PaymentMethod.self) {
            return .paymentMethod(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .paymentMethod(value): try container.encode(value); return true
        }
    }
}

public enum PaymentMethodDetailsPaymentRecordBancontactGeneratedSepaDebitMandate {
    case stringValue(String)
    case mandate(Mandate)
}

extension PaymentMethodDetailsPaymentRecordBancontactGeneratedSepaDebitMandate: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for PaymentMethodDetailsPaymentRecordBancontactGeneratedSepaDebitMandate"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        if let value = try? container.decode(Mandate.self) {
            return .mandate(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .mandate(value): try container.encode(value); return true
        }
    }
}

/// Typed representation of the `PaymentMethodDetailsPaymentRecordIdeal` API schema.
public struct PaymentMethodDetailsPaymentRecordIdeal: Codable {
    /// The customer's bank. Can be one of `abn_amro`, `adyen`, `asn_bank`, `bunq`, `buut`, `finom`,
    /// `handelsbanken`, `ing`, `knab`, `mollie`, `moneyou`, `n26`, `nn`, `rabobank`, `regiobank`, `revolut`,
    /// `sns_bank`, `triodos_bank`, `van_lanschot`, or `yoursafe`.
    public var bank: PaymentMethodDetailsPaymentRecordIdealBank?
    /// The Bank Identifier Code of the customer's bank.
    public var bic: PaymentMethodDetailsPaymentRecordIdealBic?
    /// The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
    public var generatedSepaDebit: PaymentMethodDetailsPaymentRecordIdealGeneratedSepaDebit?
    /// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
    public var generatedSepaDebitMandate: PaymentMethodDetailsPaymentRecordIdealGeneratedSepaDebitMandate?
    /// Last four characters of the IBAN.
    public var ibanLast4: String?
    /// Unique transaction ID generated by iDEAL.
    public var transactionId: String?
    /// Owner's verified full name. Values are verified or provided by iDEAL directly (if supported) at the time of
    /// authorization or settlement. They cannot be set or mutated.
    public var verifiedName: String?

    enum CodingKeys: String, CodingKey {
        case bank
        case bic
        case generatedSepaDebit = "generated_sepa_debit"
        case generatedSepaDebitMandate = "generated_sepa_debit_mandate"
        case ibanLast4 = "iban_last4"
        case transactionId = "transaction_id"
        case verifiedName = "verified_name"
    }

    init() {
        (bank, bic, generatedSepaDebit, generatedSepaDebitMandate, ibanLast4) = (nil, nil, nil, nil, nil)
        (transactionId, verifiedName) = (nil, nil)
    }
}

public extension PaymentMethodDetailsPaymentRecordIdeal {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        bank = try container.sdkDecodeIfPresent(.bank)
        bic = try container.sdkDecodeIfPresent(.bic)
        generatedSepaDebit = try container.sdkDecodeIfPresent(.generatedSepaDebit)
        generatedSepaDebitMandate = try container.sdkDecodeIfPresent(.generatedSepaDebitMandate)
        ibanLast4 = try container.sdkDecodeIfPresent(.ibanLast4)
        transactionId = try container.sdkDecodeIfPresent(.transactionId)
        verifiedName = try container.sdkDecodeIfPresent(.verifiedName)
        if let value = ibanLast4 {
            try validateLength("iban_last4", value, min: nil, max: 5000)
        }
        if let value = transactionId {
            try validateLength("transaction_id", value, min: nil, max: 5000)
        }
        if let value = verifiedName {
            try validateLength("verified_name", value, min: nil, max: 5000)
        }
    }
}

public extension PaymentMethodDetailsPaymentRecordIdeal {
    init(
        bank: PaymentMethodDetailsPaymentRecordIdealBank? = nil,
        bic: PaymentMethodDetailsPaymentRecordIdealBic? = nil,
        generatedSepaDebit: PaymentMethodDetailsPaymentRecordIdealGeneratedSepaDebit? = nil,
        generatedSepaDebitMandate: PaymentMethodDetailsPaymentRecordIdealGeneratedSepaDebitMandate? = nil,
        ibanLast4: String? = nil,
        transactionId: String? = nil,
        verifiedName: String? = nil
    ) throws {
        self.init()
        (self.bank, self.bic) = (bank, bic)
        self.generatedSepaDebit = generatedSepaDebit
        (self.generatedSepaDebitMandate, self.ibanLast4) = (generatedSepaDebitMandate, ibanLast4)
        (self.transactionId, self.verifiedName) = (transactionId, verifiedName)
        if let value = self.ibanLast4 {
            try validateLength("iban_last4", value, min: nil, max: 5000)
        }
        if let value = self.transactionId {
            try validateLength("transaction_id", value, min: nil, max: 5000)
        }
        if let value = self.verifiedName {
            try validateLength("verified_name", value, min: nil, max: 5000)
        }
    }
}

public enum PaymentMethodDetailsPaymentRecordIdealGeneratedSepaDebit {
    case stringValue(String)
    case paymentMethod(PaymentMethod)
}

extension PaymentMethodDetailsPaymentRecordIdealGeneratedSepaDebit: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for PaymentMethodDetailsPaymentRecordIdealGeneratedSepaDebit"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        if let value = try? container.decode(PaymentMethod.self) {
            return .paymentMethod(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .paymentMethod(value): try container.encode(value); return true
        }
    }
}

public enum PaymentMethodDetailsPaymentRecordIdealGeneratedSepaDebitMandate {
    case stringValue(String)
    case mandate(Mandate)
}

extension PaymentMethodDetailsPaymentRecordIdealGeneratedSepaDebitMandate: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for PaymentMethodDetailsPaymentRecordIdealGeneratedSepaDebitMandate"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        if let value = try? container.decode(Mandate.self) {
            return .mandate(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .mandate(value): try container.encode(value); return true
        }
    }
}

/// Typed representation of the `PaymentMethodDetailsPaymentRecordSofort` API schema.
public struct PaymentMethodDetailsPaymentRecordSofort: Codable {
    /// Bank code of bank associated with the bank account.
    public var bankCode: String?
    /// Name of the bank associated with the bank account.
    public var bankName: String?
    /// Bank Identifier Code of the bank associated with the bank account.
    public var bic: String?
    /// Two-letter ISO code representing the country the bank account is located in.
    public var country: String?
    /// The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
    public var generatedSepaDebit: PaymentMethodDetailsPaymentRecordSofortGeneratedSepaDebit?
    /// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
    public var generatedSepaDebitMandate: PaymentMethodDetailsPaymentRecordSofortGeneratedSepaDebitMandate?
    /// Last four characters of the IBAN.
    public var ibanLast4: String?
    /// Preferred language of the SOFORT authorization page that the customer is redirected to. Can be one of `de`,
    /// `en`, `es`, `fr`, `it`, `nl`, or `pl`
    public var preferredLanguage: PaymentMethodDetailsPaymentRecordSofortPreferredLanguage?
    /// Owner's verified full name. Values are verified or provided by SOFORT directly (if supported) at the time of
    /// authorization or settlement. They cannot be set or mutated.
    public var verifiedName: String?

    enum CodingKeys: String, CodingKey {
        case bankCode = "bank_code"
        case bankName = "bank_name"
        case bic
        case country
        case generatedSepaDebit = "generated_sepa_debit"
        case generatedSepaDebitMandate = "generated_sepa_debit_mandate"
        case ibanLast4 = "iban_last4"
        case preferredLanguage = "preferred_language"
        case verifiedName = "verified_name"
    }

    init() {
        (bankCode, bankName, bic, country, generatedSepaDebit) = (nil, nil, nil, nil, nil)
        (generatedSepaDebitMandate, ibanLast4, preferredLanguage, verifiedName) = (nil, nil, nil, nil)
    }
}

public extension PaymentMethodDetailsPaymentRecordSofort {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        bankCode = try container.sdkDecodeIfPresent(.bankCode)
        bankName = try container.sdkDecodeIfPresent(.bankName)
        bic = try container.sdkDecodeIfPresent(.bic)
        country = try container.sdkDecodeIfPresent(.country)
        generatedSepaDebit = try container.sdkDecodeIfPresent(.generatedSepaDebit)
        generatedSepaDebitMandate = try container.sdkDecodeIfPresent(.generatedSepaDebitMandate)
        ibanLast4 = try container.sdkDecodeIfPresent(.ibanLast4)
        preferredLanguage = try container.sdkDecodeIfPresent(.preferredLanguage)
        verifiedName = try container.sdkDecodeIfPresent(.verifiedName)
        if let value = bankCode {
            try validateLength("bank_code", value, min: nil, max: 5000)
        }
        if let value = bankName {
            try validateLength("bank_name", value, min: nil, max: 5000)
        }
        if let value = bic {
            try validateLength("bic", value, min: nil, max: 5000)
        }
        if let value = country {
            try validateLength("country", value, min: nil, max: 5000)
        }
        if let value = ibanLast4 {
            try validateLength("iban_last4", value, min: nil, max: 5000)
        }
        if let value = verifiedName {
            try validateLength("verified_name", value, min: nil, max: 5000)
        }
    }
}

public extension PaymentMethodDetailsPaymentRecordSofort {
    init(
        bankCode: String? = nil,
        bankName: String? = nil,
        bic: String? = nil,
        country: String? = nil,
        generatedSepaDebit: PaymentMethodDetailsPaymentRecordSofortGeneratedSepaDebit? = nil,
        generatedSepaDebitMandate: PaymentMethodDetailsPaymentRecordSofortGeneratedSepaDebitMandate? = nil,
        ibanLast4: String? = nil,
        preferredLanguage: PaymentMethodDetailsPaymentRecordSofortPreferredLanguage? = nil,
        verifiedName: String? = nil
    ) throws {
        self.init()
        (self.bankCode, self.bankName) = (bankCode, bankName)
        (self.bic, self.country) = (bic, country)
        self.generatedSepaDebit = generatedSepaDebit
        (self.generatedSepaDebitMandate, self.ibanLast4) = (generatedSepaDebitMandate, ibanLast4)
        (self.preferredLanguage, self.verifiedName) = (preferredLanguage, verifiedName)
        if let value = self.bankCode {
            try validateLength("bank_code", value, min: nil, max: 5000)
        }
        if let value = self.bankName {
            try validateLength("bank_name", value, min: nil, max: 5000)
        }
        if let value = self.bic {
            try validateLength("bic", value, min: nil, max: 5000)
        }
        if let value = self.country {
            try validateLength("country", value, min: nil, max: 5000)
        }
        if let value = self.ibanLast4 {
            try validateLength("iban_last4", value, min: nil, max: 5000)
        }
        if let value = self.verifiedName {
            try validateLength("verified_name", value, min: nil, max: 5000)
        }
    }
}

public enum PaymentMethodDetailsPaymentRecordSofortGeneratedSepaDebit {
    case stringValue(String)
    case paymentMethod(PaymentMethod)
}

extension PaymentMethodDetailsPaymentRecordSofortGeneratedSepaDebit: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for PaymentMethodDetailsPaymentRecordSofortGeneratedSepaDebit"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        if let value = try? container.decode(PaymentMethod.self) {
            return .paymentMethod(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .paymentMethod(value): try container.encode(value); return true
        }
    }
}

public enum PaymentMethodDetailsPaymentRecordSofortGeneratedSepaDebitMandate {
    case stringValue(String)
    case mandate(Mandate)
}
