// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

// V1PaymentLinks domain models
extension PaymentLinksResourceCustomFieldsDropdownOption {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.label) else {
            throw SdkValidationError(field: "label", code: "required", message: "Validation failed for 'label': value is required")
        }
        guard container.contains(.value) else {
            throw SdkValidationError(field: "value", code: "required", message: "Validation failed for 'value': value is required")
        }
        self.label = try container.sdkDecodeRequired(.label)
        self.value = try container.sdkDecodeRequired(.value)
            try validateLength("label", self.label, min: nil, max: 5000)
            try validateLength("value", self.value, min: nil, max: 5000)
    }
}

extension PaymentLinksResourceCustomFieldsDropdownOption {
    public init(label: String, value: String) throws {
        (self.label, self.value) = (label, value)
            try validateLength("label", self.label, min: nil, max: 5000)
            try validateLength("value", self.value, min: nil, max: 5000)
    }
}

/// Typed representation of the `PaymentLinksResourceCustomFieldsLabel` API schema.
public struct PaymentLinksResourceCustomFieldsLabel: Codable {
    /// The type of the label.
    public var type: PaymentLinksResourceCustomFieldsLabelType
    /// Custom text for the label, displayed to the customer. Up to 50 characters.
    public var custom: String?

    enum CodingKeys: String, CodingKey {
        case type
        case custom
    }

    private init(sdkCopy value: Self) { self = value }
}

extension PaymentLinksResourceCustomFieldsLabel {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.type) else {
            throw SdkValidationError(field: "type", code: "required", message: "Validation failed for 'type': value is required")
        }
        self.type = try container.sdkDecodeRequired(.type)
        self.custom = try container.sdkDecodeIfPresent(.custom)
        if let value = self.custom {
            try validateLength("custom", value, min: nil, max: 5000)
        }
    }
}

extension PaymentLinksResourceCustomFieldsLabel {
    public init(type: PaymentLinksResourceCustomFieldsLabelType, custom: String? = nil) throws {
        (self.type, self.custom) = (type, custom)
        if let value = self.custom {
            try validateLength("custom", value, min: nil, max: 5000)
        }
    }
}

/// Typed representation of the `PaymentLinksResourceCustomFieldsNumeric` API schema.
public struct PaymentLinksResourceCustomFieldsNumeric: Codable {
    /// The value that pre-fills the field on the payment page.
    public var defaultValue: String?
    /// The maximum character length constraint for the customer's input.
    public var maximumLength: Int?
    /// The minimum character length requirement for the customer's input.
    public var minimumLength: Int?

    enum CodingKeys: String, CodingKey {
        case defaultValue = "default_value"
        case maximumLength = "maximum_length"
        case minimumLength = "minimum_length"
    }

    init() {
        (self.defaultValue, self.maximumLength, self.minimumLength) = (nil, nil, nil)
    }
}

extension PaymentLinksResourceCustomFieldsNumeric {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.defaultValue = try container.sdkDecodeIfPresent(.defaultValue)
        self.maximumLength = try container.sdkDecodeIfPresent(.maximumLength)
        self.minimumLength = try container.sdkDecodeIfPresent(.minimumLength)
        if let value = self.defaultValue {
            try validateLength("default_value", value, min: nil, max: 5000)
        }
    }
}

extension PaymentLinksResourceCustomFieldsNumeric {
    public init(defaultValue: String? = nil, maximumLength: Int? = nil, minimumLength: Int? = nil) throws {
        self.init()
        (self.defaultValue, self.maximumLength) = (defaultValue, maximumLength)
        self.minimumLength = minimumLength
        if let value = self.defaultValue {
            try validateLength("default_value", value, min: nil, max: 5000)
        }
    }
}

/// Typed representation of the `PaymentLinksResourceCustomFieldsText` API schema.
public struct PaymentLinksResourceCustomFieldsText: Codable {
    /// The value that pre-fills the field on the payment page.
    public var defaultValue: String?
    /// The maximum character length constraint for the customer's input.
    public var maximumLength: Int?
    /// The minimum character length requirement for the customer's input.
    public var minimumLength: Int?

    enum CodingKeys: String, CodingKey {
        case defaultValue = "default_value"
        case maximumLength = "maximum_length"
        case minimumLength = "minimum_length"
    }

    init() {
        (self.defaultValue, self.maximumLength, self.minimumLength) = (nil, nil, nil)
    }
}

extension PaymentLinksResourceCustomFieldsText {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.defaultValue = try container.sdkDecodeIfPresent(.defaultValue)
        self.maximumLength = try container.sdkDecodeIfPresent(.maximumLength)
        self.minimumLength = try container.sdkDecodeIfPresent(.minimumLength)
        if let value = self.defaultValue {
            try validateLength("default_value", value, min: nil, max: 5000)
        }
    }
}

extension PaymentLinksResourceCustomFieldsText {
    public init(defaultValue: String? = nil, maximumLength: Int? = nil, minimumLength: Int? = nil) throws {
        self.init()
        (self.defaultValue, self.maximumLength) = (defaultValue, maximumLength)
        self.minimumLength = minimumLength
        if let value = self.defaultValue {
            try validateLength("default_value", value, min: nil, max: 5000)
        }
    }
}

/// Typed representation of the `PaymentLinksResourceCustomText` API schema.
public struct PaymentLinksResourceCustomText: Codable {
    /// Custom text that should be displayed after the payment confirmation button.
    public var afterSubmit: PaymentLinksResourceCustomTextAfterSubmit?
    /// Custom text that should be displayed alongside shipping address collection.
    public var shippingAddress: PaymentLinksResourceCustomTextShippingAddress?
    /// Custom text that should be displayed alongside the payment confirmation button.
    public var submit: PaymentLinksResourceCustomTextSubmit?
    /// Custom text that should be displayed in place of the default terms of service agreement text.
    public var termsOfServiceAcceptance: PaymentLinksResourceCustomTextTermsOfServiceAcceptance?

    enum CodingKeys: String, CodingKey {
        case afterSubmit = "after_submit"
        case shippingAddress = "shipping_address"
        case submit
        case termsOfServiceAcceptance = "terms_of_service_acceptance"
    }

    init() {
        (self.afterSubmit, self.shippingAddress, self.submit, self.termsOfServiceAcceptance) = (nil, nil, nil, nil)
    }
}

extension PaymentLinksResourceCustomText {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.afterSubmit = try container.sdkDecodeIfPresent(.afterSubmit)
        self.shippingAddress = try container.sdkDecodeIfPresent(.shippingAddress)
        self.submit = try container.sdkDecodeIfPresent(.submit)
        self.termsOfServiceAcceptance = try container.sdkDecodeIfPresent(.termsOfServiceAcceptance)
    }
}

extension PaymentLinksResourceCustomText {
    public init(afterSubmit: PaymentLinksResourceCustomTextAfterSubmit? = nil, shippingAddress: PaymentLinksResourceCustomTextShippingAddress? = nil, submit: PaymentLinksResourceCustomTextSubmit? = nil, termsOfServiceAcceptance: PaymentLinksResourceCustomTextTermsOfServiceAcceptance? = nil) {
        self.init()
        (self.afterSubmit, self.shippingAddress) = (afterSubmit, shippingAddress)
        (self.submit, self.termsOfServiceAcceptance) = (submit, termsOfServiceAcceptance)
    }
}

public enum PaymentLinksResourceCustomTextAfterSubmit {
    case paymentLinksResourceCustomTextPosition(PaymentLinksResourceCustomTextPosition)
}

extension PaymentLinksResourceCustomTextAfterSubmit: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PaymentLinksResourceCustomTextAfterSubmit")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PaymentLinksResourceCustomTextPosition.self
        ) {
            return             .paymentLinksResourceCustomTextPosition(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .paymentLinksResourceCustomTextPosition(value): try container.encode(value); return true
        }
    }

}

public enum PaymentLinksResourceCustomTextShippingAddress {
    case paymentLinksResourceCustomTextPosition(PaymentLinksResourceCustomTextPosition)
}

extension PaymentLinksResourceCustomTextShippingAddress: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PaymentLinksResourceCustomTextShippingAddress")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PaymentLinksResourceCustomTextPosition.self
        ) {
            return             .paymentLinksResourceCustomTextPosition(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .paymentLinksResourceCustomTextPosition(value): try container.encode(value); return true
        }
    }

}

public enum PaymentLinksResourceCustomTextSubmit {
    case paymentLinksResourceCustomTextPosition(PaymentLinksResourceCustomTextPosition)
}

extension PaymentLinksResourceCustomTextSubmit: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PaymentLinksResourceCustomTextSubmit")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PaymentLinksResourceCustomTextPosition.self
        ) {
            return             .paymentLinksResourceCustomTextPosition(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .paymentLinksResourceCustomTextPosition(value): try container.encode(value); return true
        }
    }

}

public enum PaymentLinksResourceCustomTextTermsOfServiceAcceptance {
    case paymentLinksResourceCustomTextPosition(PaymentLinksResourceCustomTextPosition)
}

extension PaymentLinksResourceCustomTextTermsOfServiceAcceptance: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PaymentLinksResourceCustomTextTermsOfServiceAcceptance")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PaymentLinksResourceCustomTextPosition.self
        ) {
            return             .paymentLinksResourceCustomTextPosition(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .paymentLinksResourceCustomTextPosition(value): try container.encode(value); return true
        }
    }

}

/// Typed representation of the `PaymentLinksResourceCustomTextPosition` API schema.
public struct PaymentLinksResourceCustomTextPosition: Codable {
    /// Text can be up to 1200 characters in length.
    public var message: String

    enum CodingKeys: String, CodingKey {
        case message
    }

    private init(sdkCopy value: Self) { self = value }
}

extension PaymentLinksResourceCustomTextPosition {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.message) else {
            throw SdkValidationError(field: "message", code: "required", message: "Validation failed for 'message': value is required")
        }
        self.message = try container.sdkDecodeRequired(.message)
            try validateLength("message", self.message, min: nil, max: 1200)
    }
}

extension PaymentLinksResourceCustomTextPosition {
    public init(message: String) throws {
        self.message = message
            try validateLength("message", self.message, min: nil, max: 1200)
    }
}

/// Typed representation of the `PaymentLinksResourceIndividualName` API schema.
public struct PaymentLinksResourceIndividualName: Codable {
    /// Indicates whether individual name collection is enabled for the payment link.
    public var enabled: Bool
    /// Whether the customer is required to complete the field before checking out. Defaults to `false`.
    public var optional: Bool

    enum CodingKeys: String, CodingKey {
        case enabled
        case optional
    }

    private init(sdkCopy value: Self) { self = value }
}

extension PaymentLinksResourceIndividualName {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.enabled) else {
            throw SdkValidationError(field: "enabled", code: "required", message: "Validation failed for 'enabled': value is required")
        }
        guard container.contains(.optional) else {
            throw SdkValidationError(field: "optional", code: "required", message: "Validation failed for 'optional': value is required")
        }
        self.enabled = try container.sdkDecodeRequired(.enabled)
        self.optional = try container.sdkDecodeRequired(.optional)
    }
}

extension PaymentLinksResourceIndividualName {
    public init(enabled: Bool, optional: Bool) {
        (self.enabled, self.optional) = (enabled, optional)
    }
}

/// Typed representation of the `PaymentLinksResourceInvoiceCreation` API schema.
public struct PaymentLinksResourceInvoiceCreation: Codable {
    /// Enable creating an invoice on successful payment.
    public var enabled: Bool
    /// Configuration for the invoice. Default invoice values will be used if unspecified.
    public var invoiceData: PaymentLinksResourceInvoiceCreationInvoiceData?

    enum CodingKeys: String, CodingKey {
        case enabled
        case invoiceData = "invoice_data"
    }

    private init(sdkCopy value: Self) { self = value }
}

extension PaymentLinksResourceInvoiceCreation {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.enabled) else {
            throw SdkValidationError(field: "enabled", code: "required", message: "Validation failed for 'enabled': value is required")
        }
        self.enabled = try container.sdkDecodeRequired(.enabled)
        self.invoiceData = try container.sdkDecodeIfPresent(.invoiceData)
    }
}

extension PaymentLinksResourceInvoiceCreation {
    public init(enabled: Bool, invoiceData: PaymentLinksResourceInvoiceCreationInvoiceData? = nil) {
        (self.enabled, self.invoiceData) = (enabled, invoiceData)
    }
}

public enum PaymentLinksResourceInvoiceCreationInvoiceData {
    case paymentLinksResourceInvoiceSettings(PaymentLinksResourceInvoiceSettings)
}

extension PaymentLinksResourceInvoiceCreationInvoiceData: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PaymentLinksResourceInvoiceCreationInvoiceData")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(
            PaymentLinksResourceInvoiceSettings.self
        ) {
            return             .paymentLinksResourceInvoiceSettings(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .paymentLinksResourceInvoiceSettings(value): try container.encode(value); return true
        }
    }

}

/// Typed representation of the `PaymentLinksResourceInvoiceSettings` API schema.
public struct PaymentLinksResourceInvoiceSettings: Codable {
    /// The account tax IDs associated with the invoice.
    public var accountTaxIds: [PaymentLinksResourceInvoiceSettingsAccountTaxIdsItem]?
    /// A list of up to 4 custom fields to be displayed on the invoice.
    public var customFields: [InvoiceSettingCustomField]?
    /// An arbitrary string attached to the object. Often useful for displaying to users.
    public var description: String?
    /// Footer to be displayed on the invoice.
    public var footer: String?
    /// The connected account that issues the invoice. The invoice is presented with the branding and support
    /// information of the specified account.
    public var issuer: PaymentLinksResourceInvoiceSettingsIssuer?
    /// Set of key-value pairs that you can attach to an object. This can be useful for storing additional
    /// information about the object in a structured format.
    public var metadata: [String: String]?
    /// Options for invoice PDF rendering.
    public var renderingOptions: PaymentLinksResourceInvoiceSettingsRenderingOptions?

    enum CodingKeys: String, CodingKey {
        case accountTaxIds = "account_tax_ids"
        case customFields = "custom_fields"
        case description
        case footer
        case issuer
        case metadata
        case renderingOptions = "rendering_options"
    }

    init() {
        (self.accountTaxIds, self.customFields, self.description, self.footer, self.issuer) = (nil, nil, nil, nil, nil)
        (self.metadata, self.renderingOptions) = (nil, nil)
    }
}

extension PaymentLinksResourceInvoiceSettings {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.accountTaxIds = try container.sdkDecodeIfPresent(.accountTaxIds)
        self.customFields = try container.sdkDecodeIfPresent(.customFields)
        self.description = try container.sdkDecodeIfPresent(.description)
        self.footer = try container.sdkDecodeIfPresent(.footer)
        self.issuer = try container.sdkDecodeIfPresent(.issuer)
        self.metadata = try container.sdkDecodeIfPresent(.metadata)
        self.renderingOptions = try container.sdkDecodeIfPresent(.renderingOptions)
        if let value = self.description {
            try validateLength("description", value, min: nil, max: 5000)
        }
        if let value = self.footer {
            try validateLength("footer", value, min: nil, max: 5000)
        }
    }
}

extension PaymentLinksResourceInvoiceSettings {
    public init(accountTaxIds: [PaymentLinksResourceInvoiceSettingsAccountTaxIdsItem]? = nil, customFields: [InvoiceSettingCustomField]? = nil, description: String? = nil, footer: String? = nil, issuer: PaymentLinksResourceInvoiceSettingsIssuer? = nil, metadata: [String: String]? = nil, renderingOptions: PaymentLinksResourceInvoiceSettingsRenderingOptions? = nil) throws {
        self.init()
        (self.accountTaxIds, self.customFields) = (accountTaxIds, customFields)
        (self.description, self.footer) = (description, footer)
        (self.issuer, self.metadata) = (issuer, metadata)
        self.renderingOptions = renderingOptions
        if let value = self.description {
            try validateLength("description", value, min: nil, max: 5000)
        }
        if let value = self.footer {
            try validateLength("footer", value, min: nil, max: 5000)
        }
    }
}

public enum PaymentLinksResourceInvoiceSettingsAccountTaxIdsItem {
    case stringValue(String)
    case taxId(TaxId)
    case deletedTaxId(DeletedTaxId)
}

extension PaymentLinksResourceInvoiceSettingsAccountTaxIdsItem: Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) { self = value; return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "No variant matched for PaymentLinksResourceInvoiceSettingsAccountTaxIdsItem")
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) { return .stringValue(value) }
        if let value = try? container.decode(TaxId.self) { return .taxId(value) }
        if let value = try? container.decode(DeletedTaxId.self) { return .deletedTaxId(value) }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) { return }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .taxId(value): try container.encode(value); return true
        case let .deletedTaxId(value): try container.encode(value); return true
        }
    }

}
