// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

/// V1PaymentLinks domain models
extension PaymentLinksResourceShippingAddressCollectionAllowedCountriesItem {
    static let allCasesPart1: [PaymentLinksResourceShippingAddressCollectionAllowedCountriesItem] = [
        .ac,
        .ad,
        .ae,
        .af,
        .ag,
        .ai,
        .al,
        .am,
        .ao,
        .aq,
        .ar,
        .at,
        .au,
        .aw,
        .ax,
        .az,
        .ba,
        .bb,
        .bd,
        .be,
        .bf,
        .bg,
        .bh,
        .bi,
        .bj,
        .bl,
        .bm,
        .bn,
        .bo,
        .bq,
        .br,
        .bs,
        .bt,
        .bv,
        .bw,
        .by,
        .bz,
        .ca,
        .cd,
        .cf,
        .cg,
        .ch,
        .ci,
        .ck,
        .cl,
        .cm,
        .cn,
        .co,
        .cr,
        .cv,
        .cw,
        .cy,
        .cz,
        .de,
        .dj,
        .dk,
        .dm,
        .do,
        .dz,
        .ec,
        .ee,
        .eg,
        .eh,
        .er,
        .es,
        .et,
        .fi,
        .fj,
        .fk,
        .fo,
        .fr,
        .ga,
        .gb,
        .gd,
        .ge,
        .gf,
        .gg,
        .gh,
        .gi,
        .gl,
    ]
}

extension PaymentLinksResourceShippingAddressCollectionAllowedCountriesItem {
    static let allCasesPart2: [PaymentLinksResourceShippingAddressCollectionAllowedCountriesItem] = [
        .gm,
        .gn,
        .gp,
        .gq,
        .gr,
        .gs,
        .gt,
        .gu,
        .gw,
        .gy,
        .hk,
        .hn,
        .hr,
        .ht,
        .hu,
        .id,
        .ie,
        .il,
        .im,
        .in,
        .io,
        .iq,
        .is,
        .it,
        .je,
        .jm,
        .jo,
        .jp,
        .ke,
        .kg,
        .kh,
        .ki,
        .km,
        .kn,
        .kr,
        .kw,
        .ky,
        .kz,
        .la,
        .lb,
        .lc,
        .li,
        .lk,
        .lr,
        .ls,
        .lt,
        .lu,
        .lv,
        .ly,
        .ma,
        .mc,
        .md,
        .me,
        .mf,
        .mg,
        .mk,
        .ml,
        .mm,
        .mn,
        .mo,
        .mq,
        .mr,
        .ms,
        .mt,
        .mu,
        .mv,
        .mw,
        .mx,
        .my,
        .mz,
        .na,
        .nc,
        .ne,
        .ng,
        .ni,
        .nl,
        .no,
        .np,
        .nr,
        .nu,
    ]
}

extension PaymentLinksResourceShippingAddressCollectionAllowedCountriesItem {
    static let allCasesPart3: [PaymentLinksResourceShippingAddressCollectionAllowedCountriesItem] = [
        .nz,
        .om,
        .pa,
        .pe,
        .pf,
        .pg,
        .ph,
        .pk,
        .pl,
        .pm,
        .pn,
        .pr,
        .ps,
        .pt,
        .py,
        .qa,
        .re,
        .ro,
        .rs,
        .ru,
        .rw,
        .sa,
        .sb,
        .sc,
        .sd,
        .se,
        .sg,
        .sh,
        .si,
        .sj,
        .sk,
        .sl,
        .sm,
        .sn,
        .so,
        .sr,
        .ss,
        .st,
        .sv,
        .sx,
        .sz,
        .ta,
        .tc,
        .td,
        .tf,
        .tg,
        .th,
        .tj,
        .tk,
        .tl,
        .tm,
        .tn,
        .to,
        .tr,
        .tt,
        .tv,
        .tw,
        .tz,
        .ua,
        .ug,
        .us,
        .uy,
        .uz,
        .va,
        .vc,
        .ve,
        .vg,
        .vn,
        .vu,
        .wf,
        .ws,
        .xk,
        .ye,
        .yt,
        .za,
        .zm,
        .zw,
        .zz,
    ]
}

extension PaymentLinksResourceShippingAddressCollectionAllowedCountriesItem: CaseIterable {
    public static var allCases: [PaymentLinksResourceShippingAddressCollectionAllowedCountriesItem] {
        allCasesPart1
            + allCasesPart2
            + allCasesPart3
    }
}

/// Indicates when the funds will be captured from the customer's account.
public struct PaymentLinksResourcePaymentIntentDataCaptureMethod: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let automatic = PaymentLinksResourcePaymentIntentDataCaptureMethod(rawValue: "automatic")
    public static let automaticAsync = PaymentLinksResourcePaymentIntentDataCaptureMethod(rawValue: "automatic_async")
    public static let manual = PaymentLinksResourcePaymentIntentDataCaptureMethod(rawValue: "manual")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// The type of the label.
public struct PaymentLinksResourceCustomFieldsLabelType: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let custom = PaymentLinksResourceCustomFieldsLabelType(rawValue: "custom")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// The specified behavior after the purchase is complete.
public struct PaymentLinksResourceAfterCompletionType: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let hostedConfirmation = PaymentLinksResourceAfterCompletionType(rawValue: "hosted_confirmation")
    public static let redirect = PaymentLinksResourceAfterCompletionType(rawValue: "redirect")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// If set to `required`, it requires cutomers to accept the terms of service before being able to pay. If set
/// to `none`, customers won't be shown a checkbox to accept the terms of service.
public struct PaymentLinksResourceConsentCollectionTermsOfService: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let none = PaymentLinksResourceConsentCollectionTermsOfService(rawValue: "none")
    public static let required = PaymentLinksResourceConsentCollectionTermsOfService(rawValue: "required")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Indicates that you intend to make future payments with the payment method collected during checkout.
public struct PaymentLinksResourcePaymentIntentDataSetupFutureUsage: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let offSession = PaymentLinksResourcePaymentIntentDataSetupFutureUsage(rawValue: "off_session")
    public static let onSession = PaymentLinksResourcePaymentIntentDataSetupFutureUsage(rawValue: "on_session")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// If set to `auto`, enables the collection of customer consent for promotional communications.
public struct PaymentLinksResourceConsentCollectionPromotions: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let auto = PaymentLinksResourceConsentCollectionPromotions(rawValue: "auto")
    public static let none = PaymentLinksResourceConsentCollectionPromotions(rawValue: "none")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Required enumerated value serialized in the `required` wire field.
public struct PaymentLinksResourceTaxIdCollectionRequired: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let ifSupported = PaymentLinksResourceTaxIdCollectionRequired(rawValue: "if_supported")
    public static let never = PaymentLinksResourceTaxIdCollectionRequired(rawValue: "never")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}
