// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

/// V1Thresholds domain models
/// Typed representation of the `ThresholdsResourceUsageAlertFilter` API schema.
public struct ThresholdsResourceUsageAlertFilter: Codable {
    /// Required enumerated value serialized in the `type` wire field.
    public var type: ThresholdsResourceUsageAlertFilterType
    /// Limit the scope of the alert to this customer ID
    public var customer: ThresholdsResourceUsageAlertFilterCustomer?

    enum CodingKeys: String, CodingKey {
        case type
        case customer
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension ThresholdsResourceUsageAlertFilter {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.type) else {
            throw SdkValidationError(
                field: "type",
                code: "required",
                message: "Validation failed for 'type': value is required"
            )
        }
        type = try container.sdkDecodeRequired(.type)
        customer = try container.sdkDecodeIfPresent(.customer)
    }
}

public extension ThresholdsResourceUsageAlertFilter {
    init(type: ThresholdsResourceUsageAlertFilterType, customer: ThresholdsResourceUsageAlertFilterCustomer? = nil) {
        (self.type, self.customer) = (type, customer)
    }
}

public enum ThresholdsResourceUsageAlertFilterCustomer {
    case stringValue(String)
    case customer(Customer)
}

extension ThresholdsResourceUsageAlertFilterCustomer: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for ThresholdsResourceUsageAlertFilterCustomer"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        if let value = try? container.decode(Customer.self) {
            return .customer(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .customer(value): try container.encode(value); return true
        }
    }
}

/// The usage threshold alert configuration enables setting up alerts for when a certain usage threshold on a
/// specific meter is crossed.
public struct ThresholdsResourceUsageThresholdConfig: Codable {
    /// The value at which this alert will trigger.
    public var gte: Int
    /// The Billing Meter ID whose usage is monitored.
    public var meter: ThresholdsResourceUsageThresholdConfigMeter
    /// Defines how the alert will behave.
    public var recurrence: ThresholdsResourceUsageThresholdConfigRecurrence
    /// The filters allow limiting the scope of this usage alert. You can only specify up to one filter at this
    /// time.
    public var filters: [ThresholdsResourceUsageAlertFilter]?

    enum CodingKeys: String, CodingKey {
        case gte
        case meter
        case recurrence
        case filters
    }

    private init(sdkCopy value: Self) {
        self = value
    }
}

public extension ThresholdsResourceUsageThresholdConfig {
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.contains(.gte) else {
            throw SdkValidationError(
                field: "gte",
                code: "required",
                message: "Validation failed for 'gte': value is required"
            )
        }
        guard container.contains(.meter) else {
            throw SdkValidationError(
                field: "meter",
                code: "required",
                message: "Validation failed for 'meter': value is required"
            )
        }
        guard container.contains(.recurrence) else {
            throw SdkValidationError(
                field: "recurrence",
                code: "required",
                message: "Validation failed for 'recurrence': value is required"
            )
        }
        gte = try container.sdkDecodeRequired(.gte)
        meter = try container.sdkDecodeRequired(.meter)
        recurrence = try container.sdkDecodeRequired(.recurrence)
        filters = try container.sdkDecodeIfPresent(.filters)
    }
}

public extension ThresholdsResourceUsageThresholdConfig {
    init(
        gte: Int,
        meter: ThresholdsResourceUsageThresholdConfigMeter,
        recurrence: ThresholdsResourceUsageThresholdConfigRecurrence,
        filters: [ThresholdsResourceUsageAlertFilter]? = nil
    ) {
        (self.gte, self.meter) = (gte, meter)
        (self.recurrence, self.filters) = (recurrence, filters)
    }
}

public enum ThresholdsResourceUsageThresholdConfigMeter {
    case stringValue(String)
    case billingMeter(BillingMeter)
}

extension ThresholdsResourceUsageThresholdConfigMeter: Codable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = Self.decodeGroup1(from: container) {
            self = value; return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "No variant matched for ThresholdsResourceUsageThresholdConfigMeter"
        )
    }

    private static func decodeGroup1(from container: SingleValueDecodingContainer) -> Self? {
        if let value = try? container.decode(String.self) {
            return .stringValue(value)
        }
        if let value = try? container.decode(BillingMeter.self) {
            return .billingMeter(value)
        }
        return nil
    }

    public func encode(to encoder: Encoder) throws {
        if try encodeGroup1(to: encoder) {
            return
        }
    }

    private func encodeGroup1(to encoder: Encoder) throws -> Bool {
        var container = encoder.singleValueContainer()
        switch self {
        case let .stringValue(value): try container.encode(value); return true
        case let .billingMeter(value): try container.encode(value); return true
        }
    }
}

/// Required enumerated value serialized in the `type` wire field.
public struct ThresholdsResourceUsageAlertFilterType: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let customer = ThresholdsResourceUsageAlertFilterType(rawValue: "customer")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Defines how the alert will behave.
public struct ThresholdsResourceUsageThresholdConfigRecurrence: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let oneTime = ThresholdsResourceUsageThresholdConfigRecurrence(rawValue: "one_time")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}
