// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif
/// String representing the object's type. Objects of the same type share the same value. Always has the value
/// `list`.
public struct GetEntitlementsActiveEntitlementsResponseObject: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let list = GetEntitlementsActiveEntitlementsResponseObject(rawValue: "list")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// String representing the object's type. Objects of the same type share the same value. Always has the value
/// `list`.
public struct GetEntitlementsFeaturesResponseObject: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let list = GetEntitlementsFeaturesResponseObject(rawValue: "list")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostEntitlementsFeaturesIdRequestBodyMetadataVariant1: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let unknown = PostEntitlementsFeaturesIdRequestBodyMetadataVariant1(rawValue: "")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// String representing the object's type. Objects of the same type share the same value. Always has the value
/// `list`.
public struct GetEventsResponseObject: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let list = GetEventsResponseObject(rawValue: "list")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// String representing the object's type. Objects of the same type share the same value. Always has the value
/// `list`.
public struct GetExchangeRatesResponseObject: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let list = GetExchangeRatesResponseObject(rawValue: "list")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// The type of entity that holds the account. This can be either `individual` or `company`.
public struct PostExternalAccountsIdRequestBodyAccountHolderType: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let unknown = PostExternalAccountsIdRequestBodyAccountHolderType(rawValue: "")
    public static let company = PostExternalAccountsIdRequestBodyAccountHolderType(rawValue: "company")
    public static let individual = PostExternalAccountsIdRequestBodyAccountHolderType(rawValue: "individual")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// The bank account type. This can only be `checking` or `savings` in most countries. In Japan, this can only
/// be `futsu` or `toza`.
public struct PostExternalAccountsIdRequestBodyAccountType: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let checking = PostExternalAccountsIdRequestBodyAccountType(rawValue: "checking")
    public static let futsu = PostExternalAccountsIdRequestBodyAccountType(rawValue: "futsu")
    public static let savings = PostExternalAccountsIdRequestBodyAccountType(rawValue: "savings")
    public static let toza = PostExternalAccountsIdRequestBodyAccountType(rawValue: "toza")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostExternalAccountsIdRequestBodyMetadataVariant1: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let unknown = PostExternalAccountsIdRequestBodyMetadataVariant1(rawValue: "")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// String representing the object's type. Objects of the same type share the same value. Always has the value
/// `list`.
public struct GetFileLinksResponseObject: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let list = GetFileLinksResponseObject(rawValue: "list")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostFileLinksRequestBodyMetadataVariant1: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let unknown = PostFileLinksRequestBodyMetadataVariant1(rawValue: "")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostFileLinksLinkRequestBodyExpiresAtVariant0: RawRepresentable, Hashable, Codable, Sendable,
    SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let now = PostFileLinksLinkRequestBodyExpiresAtVariant0(rawValue: "now")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        try self.init(rawValue: container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}
