// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif
public struct PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankX8d8a73f1cc: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let unknown = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankX8d8a73f1cc(rawValue: "")
    public static let none = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankX8d8a73f1cc(rawValue: "none")
    public static let offSession = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankX8d8a73f1cc(rawValue: "off_session")
    public static let onSession = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankX8d8a73f1cc(rawValue: "on_session")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankXe28ea9311e: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let unknown = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankXe28ea9311e(rawValue: "")
    public static let goods = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankXe28ea9311e(rawValue: "goods")
    public static let other = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankXe28ea9311e(rawValue: "other")
    public static let services = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankXe28ea9311e(rawValue: "services")
    public static let unspecified = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankXe28ea9311e(rawValue: "unspecified")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankXb4f06a630d: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let automatic = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankXb4f06a630d(rawValue: "automatic")
    public static let instant = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankXb4f06a630d(rawValue: "instant")
    public static let microdeposits = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankXb4f06a630d(rawValue: "microdeposits")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankX8b191ac470: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let unknown = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsUsBankX8b191ac470(rawValue: "")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsWechatX95aecc0b3b: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let android = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsWechatX95aecc0b3b(rawValue: "android")
    public static let ios = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsWechatX95aecc0b3b(rawValue: "ios")
    public static let web = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsWechatX95aecc0b3b(rawValue: "web")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsWechatX545a634d6a: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let none = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsWechatX545a634d6a(rawValue: "none")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsWechatPayVariant1: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let unknown = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsWechatPayVariant1(rawValue: "")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsZipVarX5d899a7c28: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let none = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsZipVarX5d899a7c28(rawValue: "none")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsZipVariant1: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let unknown = PostPaymentIntentsIntentRequestBodyPaymentMethodOptionsZipVariant1(rawValue: "")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

/// Indicates that you intend to make future payments with this PaymentIntent's payment method. If you provide a
/// Customer with the PaymentIntent, you can use this parameter to attach the payment method to the Customer
/// after the PaymentIntent is confirmed and the customer completes any required actions. If you don't provide a
/// Customer, you can still attach the payment method to a Customer after the transaction completes. If the
/// payment method is `card_present` and isn't a digital…
public struct PostPaymentIntentsIntentRequestBodySetupFutureUsage: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let unknown = PostPaymentIntentsIntentRequestBodySetupFutureUsage(rawValue: "")
    public static let offSession = PostPaymentIntentsIntentRequestBodySetupFutureUsage(rawValue: "off_session")
    public static let onSession = PostPaymentIntentsIntentRequestBodySetupFutureUsage(rawValue: "on_session")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsIntentRequestBodyShippingVariant1: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let unknown = PostPaymentIntentsIntentRequestBodyShippingVariant1(rawValue: "")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}
