// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif
public struct PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let acssDebit = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "acss_debit")
    public static let affirm = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "affirm")
    public static let afterpayClearpay = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "afterpay_clearpay")
    public static let alipay = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "alipay")
    public static let alma = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "alma")
    public static let amazonPay = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "amazon_pay")
    public static let auBecsDebit = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "au_becs_debit")
    public static let bacsDebit = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "bacs_debit")
    public static let bancontact = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "bancontact")
    public static let billie = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "billie")
    public static let bizum = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "bizum")
    public static let blik = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "blik")
    public static let boleto = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "boleto")
    public static let card = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "card")
    public static let cashapp = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "cashapp")
    public static let crypto = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "crypto")
    public static let customerBalance = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "customer_balance")
    public static let eps = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "eps")
    public static let fpx = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "fpx")
    public static let giropay = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "giropay")
    public static let grabpay = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "grabpay")
    public static let ideal = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "ideal")
    public static let kakaoPay = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "kakao_pay")
    public static let klarna = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "klarna")
    public static let konbini = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "konbini")
    public static let krCard = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "kr_card")
    public static let mbWay = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "mb_way")
    public static let mobilepay = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "mobilepay")
    public static let multibanco = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "multibanco")
    public static let naverPay = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "naver_pay")
    public static let nzBankAccount = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "nz_bank_account")
    public static let oxxo = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "oxxo")
    public static let p24 = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "p24")
    public static let payByBank = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "pay_by_bank")
    public static let payco = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "payco")
    public static let paynow = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "paynow")
    public static let paypal = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "paypal")
    public static let payto = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "payto")
    public static let pix = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "pix")
    public static let promptpay = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "promptpay")
    public static let revolutPay = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "revolut_pay")
    public static let samsungPay = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "samsung_pay")
    public static let satispay = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "satispay")
    public static let scalapay = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "scalapay")
    public static let sepaDebit = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "sepa_debit")
    public static let sofort = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "sofort")
    public static let sunbit = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "sunbit")
    public static let swish = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "swish")
    public static let twint = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "twint")
    public static let upi = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "upi")
    public static let usBankAccount = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "us_bank_account")
    public static let wechatPay = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "wechat_pay")
    public static let zip = PostPaymentIntentsRequestBodyExcludedPaymentMethodTypesItem(rawValue: "zip")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsRequestBodyHooksInputsTaxCalculationVariant1: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let unknown = PostPaymentIntentsRequestBodyHooksInputsTaxCalculationVariant1(rawValue: "")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsRequestBodyMandateDataVariant0CustomerAcceptanceType: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let offline = PostPaymentIntentsRequestBodyMandateDataVariant0CustomerAcceptanceType(rawValue: "offline")
    public static let online = PostPaymentIntentsRequestBodyMandateDataVariant0CustomerAcceptanceType(rawValue: "online")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsRequestBodyMandateDataVariant1: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let unknown = PostPaymentIntentsRequestBodyMandateDataVariant1(rawValue: "")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsRequestBodyOffSessionVariant1: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let oneOff = PostPaymentIntentsRequestBodyOffSessionVariant1(rawValue: "one_off")
    public static let recurring = PostPaymentIntentsRequestBodyOffSessionVariant1(rawValue: "recurring")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsRequestBodyPaymentDetailsCustomerReferenceVariant1: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let unknown = PostPaymentIntentsRequestBodyPaymentDetailsCustomerReferenceVariant1(rawValue: "")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsRequestBodyPaymentDetailsOrderReferenceVariant1: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let unknown = PostPaymentIntentsRequestBodyPaymentDetailsOrderReferenceVariant1(rawValue: "")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsRequestBodyPaymentMethodDataAllowRedisplay: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let always = PostPaymentIntentsRequestBodyPaymentMethodDataAllowRedisplay(rawValue: "always")
    public static let limited = PostPaymentIntentsRequestBodyPaymentMethodDataAllowRedisplay(rawValue: "limited")
    public static let unspecified = PostPaymentIntentsRequestBodyPaymentMethodDataAllowRedisplay(rawValue: "unspecified")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PostPaymentIntentsRequestBodyPaymentMethodDataBillingDetailsAXf602f5f35e: RawRepresentable, Hashable, Codable, Sendable, SdkWireConvertible {
    public let rawValue: String

    public init(rawValue: String) { self.rawValue = rawValue }
    public static let unknown = PostPaymentIntentsRequestBodyPaymentMethodDataBillingDetailsAXf602f5f35e(rawValue: "")

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.init(rawValue: try container.decode(String.self))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}
